// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         name: "www.example.com",
 *         "name.exact": "www.example.com",
 *         "name.contains": "w.example.",
 *         "name.startswith": "www.example",
 *         "name.endswith": ".example.com",
 *         content: "127.0.0.1",
 *         "content.exact": "127.0.0.1",
 *         "content.contains": "7.0.0.",
 *         "content.startswith": "127.0.",
 *         "content.endswith": ".0.1",
 *         proxied: true,
 *         comment: "Hello, world",
 *         "comment.exact": "Hello, world",
 *         "comment.contains": "ello, worl",
 *         "comment.startswith": "Hello, w",
 *         "comment.endswith": "o, world",
 *         tag: "team:DNS",
 *         "tag.present": "important",
 *         "tag.absent": "important",
 *         "tag.exact": "greeting:Hello, world",
 *         "tag.contains": "greeting:ello, worl",
 *         "tag.startswith": "greeting:Hello, w",
 *         "tag.endswith": "greeting:o, world",
 *         search: "www.cloudflare.com",
 *         per_page: 5,
 *         include_shadow_metadata: true,
 *         shadowed_by_name: "sub.example.com",
 *         shadowing_name: "www.sub.example.com"
 *     }
 */
export interface ListRecordsRequest {
    /** Identifier. */
    zone_id: string;
    /** Exact value of the DNS record name. This is a convenience alias for `name.exact`. */
    name?: string;
    /** Exact value of the DNS record name. Name filters are case-insensitive. */
    "name.exact"?: string;
    /** Substring of the DNS record name. Name filters are case-insensitive. */
    "name.contains"?: string;
    /** Prefix of the DNS record name. Name filters are case-insensitive. */
    "name.startswith"?: string;
    /** Suffix of the DNS record name. Name filters are case-insensitive. */
    "name.endswith"?: string;
    type?: CloudflareApi.DnsRecordsType;
    /** Exact value of the DNS record content. This is a convenience alias for `content.exact`. */
    content?: string;
    /** Exact value of the DNS record content. Content filters are case-insensitive. */
    "content.exact"?: string;
    /** Substring of the DNS record content. Content filters are case-insensitive. */
    "content.contains"?: string;
    /** Prefix of the DNS record content. Content filters are case-insensitive. */
    "content.startswith"?: string;
    /** Suffix of the DNS record content. Content filters are case-insensitive. */
    "content.endswith"?: string;
    proxied?: CloudflareApi.DnsRecordsProxied;
    match?: CloudflareApi.DnsRecordsMatch;
    /** Exact value of the DNS record comment. This is a convenience alias for `comment.exact`. */
    comment?: string;
    /** If this parameter is present, only records *with* a comment are returned. */
    "comment.present"?: string;
    /** If this parameter is present, only records *without* a comment are returned. */
    "comment.absent"?: string;
    /** Exact value of the DNS record comment. Comment filters are case-insensitive. */
    "comment.exact"?: string;
    /** Substring of the DNS record comment. Comment filters are case-insensitive. */
    "comment.contains"?: string;
    /** Prefix of the DNS record comment. Comment filters are case-insensitive. */
    "comment.startswith"?: string;
    /** Suffix of the DNS record comment. Comment filters are case-insensitive. */
    "comment.endswith"?: string;
    /**
     * Condition on the DNS record tag.
     *
     * Parameter values can be of the form `<tag-name>:<tag-value>` to search for an exact `name:value` pair, or just `<tag-name>` to search for records with a specific tag name regardless of its value.
     *
     * This is a convenience shorthand for the more powerful `tag.<predicate>` parameters.
     * Examples:
     * - `tag=important` is equivalent to `tag.present=important`
     * - `tag=team:DNS` is equivalent to `tag.exact=team:DNS`
     */
    tag?: string;
    /** Name of a tag which must be present on the DNS record. Tag filters are case-insensitive. */
    "tag.present"?: string;
    /** Name of a tag which must *not* be present on the DNS record. Tag filters are case-insensitive. */
    "tag.absent"?: string;
    /** A tag and value, of the form `<tag-name>:<tag-value>`. The API will only return DNS records that have a tag named `<tag-name>` whose value is `<tag-value>`. Tag filters are case-insensitive. */
    "tag.exact"?: string;
    /** A tag and value, of the form `<tag-name>:<tag-value>`. The API will only return DNS records that have a tag named `<tag-name>` whose value contains `<tag-value>`. Tag filters are case-insensitive. */
    "tag.contains"?: string;
    /** A tag and value, of the form `<tag-name>:<tag-value>`. The API will only return DNS records that have a tag named `<tag-name>` whose value starts with `<tag-value>`. Tag filters are case-insensitive. */
    "tag.startswith"?: string;
    /** A tag and value, of the form `<tag-name>:<tag-value>`. The API will only return DNS records that have a tag named `<tag-name>` whose value ends with `<tag-value>`. Tag filters are case-insensitive. */
    "tag.endswith"?: string;
    search?: CloudflareApi.DnsRecordsSearch;
    tag_match?: CloudflareApi.DnsRecordsTagMatch;
    page?: CloudflareApi.DnsRecordsPage;
    per_page?: CloudflareApi.DnsRecordsPerPage;
    order?: CloudflareApi.DnsRecordsOrder;
    direction?: CloudflareApi.DnsRecordsDirection;
    /** Whether to include shadow metadata in the `meta` field of each record in the response. See [Shadowed records](https://developers.cloudflare.com/dns/manage-dns-records/reference/shadowed-records). */
    include_shadow_metadata?: boolean;
    /** Filters the response to records at or below the specified NS delegation name. NS, DS, and NSEC records at the delegation name are excluded because they are not shadowed by that delegation. Those record types are included only when they exist below the delegation. The value must be a non-apex subdomain of the zone. Requires `include_shadow_metadata=true`. See [Shadowed records](https://developers.cloudflare.com/dns/manage-dns-records/reference/shadowed-records). */
    shadowed_by_name?: string;
    /** Returns NS records that shadow the given name, searching at the name itself and each of its ancestor names within the zone, excluding the zone apex. The value must be a subdomain of the zone; the zone apex is not accepted. See [Shadowed records](https://developers.cloudflare.com/dns/manage-dns-records/reference/shadowed-records). */
    shadowing_name?: string;
}
