// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import {
    normalizeClientOptionsWithAuth,
    type NormalizedClientOptionsWithAuth,
} from "../../../../../../../../BaseClient.js";
import * as core from "../../../../../../../../core/index.js";
import { mergeHeaders } from "../../../../../../../../core/headers.js";
import * as environments from "../../../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../../../errors/index.js";
import type * as CloudflareApi from "../../../../../../../index.js";
import * as CloudflareApiErrors from "../../../../../../../errors/index.js";

export declare namespace SummaryClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SummaryClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SummaryClient.Options>;

    constructor(options: SummaryClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of bot-generated HTTP requests to genuine human traffic, as classified by Cloudflare. Visit https://developers.cloudflare.com/radar/concepts/bot-classes/ for more information.
     *
     * @param {CloudflareApi.radar.http.BotClassSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.summary.botClass({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public botClass(
        request: CloudflareApi.radar.http.BotClassSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.BotClassSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__botClass(request, requestOptions));
    }

    private async __botClass(
        request: CloudflareApi.radar.http.BotClassSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.BotClassSummaryResponse>> {
        const {
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/summary/bot_class",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.BotClassSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/radar/http/summary/bot_class");
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests generated by mobile, desktop, and other types of devices.
     *
     * @param {CloudflareApi.radar.http.DeviceTypeSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.summary.deviceType({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public deviceType(
        request: CloudflareApi.radar.http.DeviceTypeSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.DeviceTypeSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deviceType(request, requestOptions));
    }

    private async __deviceType(
        request: CloudflareApi.radar.http.DeviceTypeSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.DeviceTypeSummaryResponse>> {
        const {
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/summary/device_type",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.DeviceTypeSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/summary/device_type",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by HTTP protocol (HTTP vs. HTTPS).
     *
     * @param {CloudflareApi.radar.http.HttpProtocolSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.summary.httpProtocol({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public httpProtocol(
        request: CloudflareApi.radar.http.HttpProtocolSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.HttpProtocolSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__httpProtocol(request, requestOptions));
    }

    private async __httpProtocol(
        request: CloudflareApi.radar.http.HttpProtocolSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.HttpProtocolSummaryResponse>> {
        const {
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/summary/http_protocol",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.HttpProtocolSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/summary/http_protocol",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by HTTP version.
     *
     * @param {CloudflareApi.radar.http.HttpVersionSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.summary.httpVersion({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public httpVersion(
        request: CloudflareApi.radar.http.HttpVersionSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.HttpVersionSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__httpVersion(request, requestOptions));
    }

    private async __httpVersion(
        request: CloudflareApi.radar.http.HttpVersionSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.HttpVersionSummaryResponse>> {
        const {
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/summary/http_version",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.HttpVersionSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/summary/http_version",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by IP version.
     *
     * @param {CloudflareApi.radar.http.IpVersionSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.summary.ipVersion({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public ipVersion(
        request: CloudflareApi.radar.http.IpVersionSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.IpVersionSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__ipVersion(request, requestOptions));
    }

    private async __ipVersion(
        request: CloudflareApi.radar.http.IpVersionSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.IpVersionSummaryResponse>> {
        const {
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/summary/ip_version",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.IpVersionSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/summary/ip_version",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by operating system (Windows, macOS, Android, iOS, and others).
     *
     * @param {CloudflareApi.radar.http.OsSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.summary.os({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public os(
        request: CloudflareApi.radar.http.OsSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.OsSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__os(request, requestOptions));
    }

    private async __os(
        request: CloudflareApi.radar.http.OsSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.OsSummaryResponse>> {
        const {
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/summary/os",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.OsSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/radar/http/summary/os");
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by post-quantum support.
     *
     * @param {CloudflareApi.radar.http.PostQuantumSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.summary.postQuantum({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public postQuantum(
        request: CloudflareApi.radar.http.PostQuantumSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.PostQuantumSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postQuantum(request, requestOptions));
    }

    private async __postQuantum(
        request: CloudflareApi.radar.http.PostQuantumSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.PostQuantumSummaryResponse>> {
        const {
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/summary/post_quantum",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.PostQuantumSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/summary/post_quantum",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by TLS version.
     *
     * @param {CloudflareApi.radar.http.TlsVersionSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.summary.tlsVersion({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public tlsVersion(
        request: CloudflareApi.radar.http.TlsVersionSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.TlsVersionSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__tlsVersion(request, requestOptions));
    }

    private async __tlsVersion(
        request: CloudflareApi.radar.http.TlsVersionSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.TlsVersionSummaryResponse>> {
        const {
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/summary/tls_version",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.TlsVersionSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/summary/tls_version",
        );
    }
}
