// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../../../BaseClient.js";
import {
    normalizeClientOptionsWithAuth,
    type NormalizedClientOptionsWithAuth,
} from "../../../../../../../../../../BaseClient.js";
import * as core from "../../../../../../../../../../core/index.js";
import { mergeHeaders } from "../../../../../../../../../../core/headers.js";
import * as environments from "../../../../../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../../../../../errors/index.js";
import type * as CloudflareApi from "../../../../../../../../../index.js";
import * as CloudflareApiErrors from "../../../../../../../../../errors/index.js";

export declare namespace SummaryClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SummaryClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SummaryClient.Options>;

    constructor(options: SummaryClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by ARC (Authenticated Received Chain) validation.
     *
     * @param {CloudflareApi.radar.email.security.ArcSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.summary.arc({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public arc(
        request: CloudflareApi.radar.email.security.ArcSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.ArcSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__arc(request, requestOptions));
    }

    private async __arc(
        request: CloudflareApi.radar.email.security.ArcSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.ArcSummaryResponse>> {
        const { name, dateRange, dateStart, dateEnd, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/summary/arc",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.ArcSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/summary/arc",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by DKIM (DomainKeys Identified Mail) validation.
     *
     * @param {CloudflareApi.radar.email.security.DkimSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.summary.dkim({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public dkim(
        request: CloudflareApi.radar.email.security.DkimSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.DkimSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__dkim(request, requestOptions));
    }

    private async __dkim(
        request: CloudflareApi.radar.email.security.DkimSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.DkimSummaryResponse>> {
        const { name, dateRange, dateStart, dateEnd, arc, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/summary/dkim",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.DkimSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/summary/dkim",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by DMARC (Domain-based Message Authentication, Reporting and Conformance) validation.
     *
     * @param {CloudflareApi.radar.email.security.DmarcSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.summary.dmarc({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public dmarc(
        request: CloudflareApi.radar.email.security.DmarcSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.DmarcSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__dmarc(request, requestOptions));
    }

    private async __dmarc(
        request: CloudflareApi.radar.email.security.DmarcSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.DmarcSummaryResponse>> {
        const { name, dateRange, dateStart, dateEnd, arc, dkim, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/summary/dmarc",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.DmarcSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/summary/dmarc",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by malicious classification.
     *
     * @param {CloudflareApi.radar.email.security.MaliciousSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.summary.malicious({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public malicious(
        request: CloudflareApi.radar.email.security.MaliciousSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.MaliciousSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__malicious(request, requestOptions));
    }

    private async __malicious(
        request: CloudflareApi.radar.email.security.MaliciousSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.MaliciousSummaryResponse>> {
        const { name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/summary/malicious",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.MaliciousSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/summary/malicious",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the proportion of emails by spam classification (spam vs. non-spam).
     *
     * @param {CloudflareApi.radar.email.security.SpamSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.summary.spam({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public spam(
        request: CloudflareApi.radar.email.security.SpamSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.SpamSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__spam(request, requestOptions));
    }

    private async __spam(
        request: CloudflareApi.radar.email.security.SpamSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.SpamSummaryResponse>> {
        const { name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/summary/spam",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.SpamSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/summary/spam",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by SPF (Sender Policy Framework) validation.
     *
     * @param {CloudflareApi.radar.email.security.SpfSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.summary.spf({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public spf(
        request: CloudflareApi.radar.email.security.SpfSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.SpfSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__spf(request, requestOptions));
    }

    private async __spf(
        request: CloudflareApi.radar.email.security.SpfSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.SpfSummaryResponse>> {
        const { name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/summary/spf",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.SpfSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/summary/spf",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the proportion of emails by spoof classification (spoof vs. non-spoof).
     *
     * @param {CloudflareApi.radar.email.security.SpoofSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.summary.spoof({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public spoof(
        request: CloudflareApi.radar.email.security.SpoofSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.SpoofSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__spoof(request, requestOptions));
    }

    private async __spoof(
        request: CloudflareApi.radar.email.security.SpoofSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.SpoofSummaryResponse>> {
        const { name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/summary/spoof",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.SpoofSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/summary/spoof",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by threat categories.
     *
     * @param {CloudflareApi.radar.email.security.ThreatCategorySummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.summary.threatCategory({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public threatCategory(
        request: CloudflareApi.radar.email.security.ThreatCategorySummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.ThreatCategorySummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__threatCategory(request, requestOptions));
    }

    private async __threatCategory(
        request: CloudflareApi.radar.email.security.ThreatCategorySummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.ThreatCategorySummaryResponse>> {
        const { name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/summary/threat_category",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.ThreatCategorySummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/summary/threat_category",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by TLS version.
     *
     * @param {CloudflareApi.radar.email.security.TlsVersionSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.summary.tlsVersion({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public tlsVersion(
        request: CloudflareApi.radar.email.security.TlsVersionSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.TlsVersionSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__tlsVersion(request, requestOptions));
    }

    private async __tlsVersion(
        request: CloudflareApi.radar.email.security.TlsVersionSummaryRequest = {},
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.TlsVersionSummaryResponse>> {
        const { name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, format } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/summary/tls_version",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.TlsVersionSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/summary/tls_version",
        );
    }
}
