// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../../../BaseClient.js";
import {
    normalizeClientOptionsWithAuth,
    type NormalizedClientOptionsWithAuth,
} from "../../../../../../../../../../BaseClient.js";
import * as core from "../../../../../../../../../../core/index.js";
import { mergeHeaders } from "../../../../../../../../../../core/headers.js";
import * as environments from "../../../../../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../../../../../errors/index.js";
import type * as CloudflareApi from "../../../../../../../../../index.js";
import * as CloudflareApiErrors from "../../../../../../../../../errors/index.js";

export declare namespace TimeseriesGroupsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TimeseriesGroupsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TimeseriesGroupsClient.Options>;

    constructor(options: TimeseriesGroupsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by ARC (Authenticated Received Chain) validation over time.
     *
     * @param {CloudflareApi.radar.email.security.ArcTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.timeseriesGroups.arc({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public arc(
        request: CloudflareApi.radar.email.security.ArcTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.ArcTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__arc(request, requestOptions));
    }

    private async __arc(
        request: CloudflareApi.radar.email.security.ArcTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.ArcTimeseriesGroupsResponse>> {
        const { aggInterval, name, dateRange, dateStart, dateEnd, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/timeseries_groups/arc",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.ArcTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/timeseries_groups/arc",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by DKIM (DomainKeys Identified Mail) validation over time.
     *
     * @param {CloudflareApi.radar.email.security.DkimTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.timeseriesGroups.dkim({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public dkim(
        request: CloudflareApi.radar.email.security.DkimTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.DkimTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__dkim(request, requestOptions));
    }

    private async __dkim(
        request: CloudflareApi.radar.email.security.DkimTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.DkimTimeseriesGroupsResponse>> {
        const { aggInterval, name, dateRange, dateStart, dateEnd, arc, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/timeseries_groups/dkim",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.DkimTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/timeseries_groups/dkim",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by DMARC (Domain-based Message Authentication, Reporting and Conformance) validation over time.
     *
     * @param {CloudflareApi.radar.email.security.DmarcTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.timeseriesGroups.dmarc({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public dmarc(
        request: CloudflareApi.radar.email.security.DmarcTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.DmarcTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__dmarc(request, requestOptions));
    }

    private async __dmarc(
        request: CloudflareApi.radar.email.security.DmarcTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.DmarcTimeseriesGroupsResponse>> {
        const { aggInterval, name, dateRange, dateStart, dateEnd, arc, dkim, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/timeseries_groups/dmarc",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.DmarcTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/timeseries_groups/dmarc",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by malicious classification over time.
     *
     * @param {CloudflareApi.radar.email.security.MaliciousTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.timeseriesGroups.malicious({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public malicious(
        request: CloudflareApi.radar.email.security.MaliciousTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.MaliciousTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__malicious(request, requestOptions));
    }

    private async __malicious(
        request: CloudflareApi.radar.email.security.MaliciousTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.MaliciousTimeseriesGroupsResponse>> {
        const { aggInterval, name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/timeseries_groups/malicious",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.MaliciousTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/timeseries_groups/malicious",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by spam classification (spam vs. non-spam) over time.
     *
     * @param {CloudflareApi.radar.email.security.SpamTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.timeseriesGroups.spam({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public spam(
        request: CloudflareApi.radar.email.security.SpamTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.SpamTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__spam(request, requestOptions));
    }

    private async __spam(
        request: CloudflareApi.radar.email.security.SpamTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.SpamTimeseriesGroupsResponse>> {
        const { aggInterval, name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/timeseries_groups/spam",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.SpamTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/timeseries_groups/spam",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by SPF (Sender Policy Framework) validation over time.
     *
     * @param {CloudflareApi.radar.email.security.SpfTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.timeseriesGroups.spf({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public spf(
        request: CloudflareApi.radar.email.security.SpfTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.SpfTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__spf(request, requestOptions));
    }

    private async __spf(
        request: CloudflareApi.radar.email.security.SpfTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.SpfTimeseriesGroupsResponse>> {
        const { aggInterval, name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/timeseries_groups/spf",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.SpfTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/timeseries_groups/spf",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by spoof classification (spoof vs. non-spoof) over time.
     *
     * @param {CloudflareApi.radar.email.security.SpoofTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.timeseriesGroups.spoof({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public spoof(
        request: CloudflareApi.radar.email.security.SpoofTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.SpoofTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__spoof(request, requestOptions));
    }

    private async __spoof(
        request: CloudflareApi.radar.email.security.SpoofTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.SpoofTimeseriesGroupsResponse>> {
        const { aggInterval, name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/timeseries_groups/spoof",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.SpoofTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/timeseries_groups/spoof",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by threat category over time.
     *
     * @param {CloudflareApi.radar.email.security.ThreatCategoryTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.timeseriesGroups.threatCategory({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public threatCategory(
        request: CloudflareApi.radar.email.security.ThreatCategoryTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.ThreatCategoryTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__threatCategory(request, requestOptions));
    }

    private async __threatCategory(
        request: CloudflareApi.radar.email.security.ThreatCategoryTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.ThreatCategoryTimeseriesGroupsResponse>> {
        const { aggInterval, name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, tlsVersion, format } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/timeseries_groups/threat_category",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.ThreatCategoryTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/timeseries_groups/threat_category",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of emails by TLS version over time.
     *
     * @param {CloudflareApi.radar.email.security.TlsVersionTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.email.security.timeseriesGroups.tlsVersion({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public tlsVersion(
        request: CloudflareApi.radar.email.security.TlsVersionTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.email.security.TlsVersionTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__tlsVersion(request, requestOptions));
    }

    private async __tlsVersion(
        request: CloudflareApi.radar.email.security.TlsVersionTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.email.security.TlsVersionTimeseriesGroupsResponse>> {
        const { aggInterval, name, dateRange, dateStart, dateEnd, arc, dkim, dmarc, spf, format } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            arc: Array.isArray(arc) ? arc.map((item) => item) : arc != null ? arc : undefined,
            dkim: Array.isArray(dkim) ? dkim.map((item) => item) : dkim != null ? dkim : undefined,
            dmarc: Array.isArray(dmarc) ? dmarc.map((item) => item) : dmarc != null ? dmarc : undefined,
            spf: Array.isArray(spf) ? spf.map((item) => item) : spf != null ? spf : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/email/security/timeseries_groups/tls_version",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.email.security.TlsVersionTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/email/security/timeseries_groups/tls_version",
        );
    }
}
