// Generated from cloudflare/workers-sdk@c2bb4c815. Do not rename cases.
import { describe, it } from "vite-plus/test";

const groups = [
	{
		file: "api/startDevWorker/ContainerImagePreparation.test.ts",
		ancestors: ["Container image preparation"],
		status: "skip",
		names: [
			"prepares the sidecar without application images or a build ID",
			"skips preparation when Containers are disabled",
			"skips preparation when Containers are absent",
			"deduplicates reloads and prepares after Containers are enabled or added",
			"retries failed sidecar preparation without caching success",
			"preserves the previous state after aborted preparation and retries",
			"still prepares and tracks configured images",
		],
	},
	{
		file: "autoconfig/run.test.ts",
		ancestors: ["autoconfig (deploy)"],
		status: "todo",
		names: [
			"should not run autoconfig when `deploy` is run with `--no-autoconfig`",
			"should not run autoconfig when `deploy` is run with `--autoconfig=false`",
			"should check for autoconfig with flag",
			"should run autoconfig if project is not configured",
			"should not run autoconfig if project is already configured",
			"should warn and prompt when Pages project is detected",
		],
	},
	{
		file: "autoconfig/run.test.ts",
		ancestors: ["autoconfig (deploy)", "runAutoConfig()"],
		status: "todo",
		names: [
			"happy path",
			"new gitignore should not have leading empty lines",
			"pre-existing gitignore with trailing newline gets one empty separator line",
			"allows users to edit the auto-detected settings",
			".assetsignore should contain Wrangler files if outputDir === projectPath",
			"pre-existing assetsignore with trailing newline gets one empty separator line",
			"errors if no output directory is specified in the autoconfig details",
			"errors with Pages-specific message when framework is cf-pages",
			"errors with generic message when unsupported framework is not cf-pages",
			"validateFrameworkVersion is called before configure for a supported framework",
		],
	},
	{
		file: "autoconfig/run.test.ts",
		ancestors: [
			"autoconfig (deploy)",
			"runAutoConfig()",
			"nodejs_compat compatibility flag",
		],
		status: "todo",
		names: [
			"should not add nodejs_compat when framework specifies no compatibility flags",
			"should preserve other compatibility flags",
			"should remove a redundant nodejs_compat provided by the framework",
			"should remove nodejs_als while preserving other flags",
		],
	},
	{
		file: "cloudchamber/common.test.ts",
		ancestors: ["isValidImageTag"],
		status: "skip",
		names: ["accepts OCI tags and rejects digest entries"],
	},
	{
		file: "cloudchamber/common.test.ts",
		ancestors: ["parseImageName"],
		status: "skip",
		names: ["works"],
	},
	{
		file: "config-validation-pages.test.ts",
		ancestors: ["validatePagesConfig()", "`main` field validation"],
		status: "skip",
		names: [
			"should error if configuration contains both `pages_build_output_dir` and `main` config fields",
		],
	},
	{
		file: "config-validation-pages.test.ts",
		ancestors: ["validatePagesConfig()", "`name` field validation"],
		status: "skip",
		names: ['should error if "name" field is not specififed at the top-level'],
	},
	{
		file: "config-validation-pages.test.ts",
		ancestors: ["validatePagesConfig()", "named environments validation"],
		status: "skip",
		names: [
			"should pass if no named environments are defined",
			"should pass for environments named 'preview' and/or 'production'",
			"should error for any other named environments",
		],
	},
	{
		file: "config-validation-pages.test.ts",
		ancestors: ["validatePagesConfig()", "unsupported fields validation"],
		status: "skip",
		names: [
			"should pass if configuration contains only Pages-supported configuration fields",
			"should fail if configuration contains any fields that are not supported by Pages projects",
		],
	},
	{
		file: "config-validation-pages.test.ts",
		ancestors: ["validatePagesConfig()", "DO bindings validation"],
		status: "skip",
		names: [
			"should pass if all Durable Objects bindings specify 'script_name'",
			"should fail if any of the Durable Object bindings does not specify 'script_name'",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: [
			"createWorkerUploadForm — bindings",
			"plain_text / json / secret_text bindings",
		],
		status: "skip",
		names: [
			"should include 'plain_text' binding in metadata",
			"should include 'json' binding in metadata",
			"should include 'secret_text' binding in metadata",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "kv_namespace bindings"],
		status: "skip",
		names: [
			"should include KV bindings with an ID",
			"should throw when KV namespace has no ID and not in dry run",
			"should convert KV namespace to inherit binding during dry run when ID is missing",
			"should convert KV namespace with INHERIT_SYMBOL to inherit binding",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "r2_bucket bindings"],
		status: "skip",
		names: [
			"should include R2 bindings with a bucket_name",
			"should throw when R2 bucket has no bucket_name and not in dry run",
			"should convert R2 bucket to inherit binding during dry run when bucket_name is missing",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "d1 bindings"],
		status: "skip",
		names: [
			"should include D1 bindings with a database_id",
			"should throw when D1 has no database_id and not in dry run",
			"should convert D1 to inherit binding during dry run when database_id is missing",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: [
			"createWorkerUploadForm — bindings",
			"durable_object_namespace bindings",
		],
		status: "skip",
		names: [
			"should include durable object bindings",
			"should omit optional script_name and environment when not provided",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "service bindings"],
		status: "skip",
		names: [
			"should include service bindings with optional environment and entrypoint",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "queue bindings"],
		status: "skip",
		names: ["should include queue bindings"],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "workflow bindings"],
		status: "skip",
		names: ["should include workflow bindings"],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: [
			"createWorkerUploadForm — bindings",
			"pass-through binding types",
		],
		status: "skip",
		names: [
			"should pass through 'vectorize' binding unchanged",
			"should pass through 'hyperdrive' binding unchanged",
			"should pass through 'analytics_engine' binding unchanged",
			"should pass through 'mtls_certificate' binding unchanged",
			"should pass through 'secrets_store_secret' binding unchanged",
			"should pass through 'ratelimit' binding unchanged",
			"should pass through 'ai_search_namespace' binding unchanged",
			"should pass through 'ai_search' binding unchanged",
			"should pass through 'agent_memory' binding unchanged",
			"should pass through 'inherit' binding unchanged",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "ai_search bindings"],
		status: "skip",
		names: [
			"should include ai_search binding with instance_name",
			"should include ai_search_namespace binding",
			"should throw when ai_search_namespace has no namespace and not in dry run",
			"should convert ai_search_namespace to inherit binding during dry run when namespace is missing",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "agent_memory bindings"],
		status: "skip",
		names: [
			"should include agent_memory binding with namespace",
			"should throw when agent_memory has no namespace and not in dry run",
			"should convert agent_memory to inherit binding during dry run when namespace is missing",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "pipeline bindings"],
		status: "skip",
		names: ["should transform type from pipeline to pipelines"],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "singleton bindings"],
		status: "skip",
		names: [
			"should include 'browser' binding",
			"should include 'ai' binding",
			"should include 'images' binding",
			"should include 'stream' binding",
			"should include 'media' binding",
			"should include 'version_metadata' binding",
			"should include 'assets' binding",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: [
			"createWorkerUploadForm — bindings",
			"dispatch_namespace bindings",
		],
		status: "skip",
		names: [
			"should include dispatch namespace bindings",
			"should include outbound config for dispatch namespace",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "wasm_module bindings"],
		status: "skip",
		names: ["should add wasm module as a form part and metadata binding"],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "text_blob bindings"],
		status: "skip",
		names: [
			"should add text blob as a form part and metadata binding",
			"should not add __STATIC_CONTENT_MANIFEST as a form part",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: ["createWorkerUploadForm — bindings", "data_blob bindings"],
		status: "skip",
		names: ["should add data blob as a form part and metadata binding"],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: [
			"createWorkerUploadForm — bindings",
			"provisionable name-only bindings",
		],
		status: "skip",
		names: [
			"should inherit a draft 'Queue' binding during dry run",
			"should inherit a draft 'Dispatch Namespace' binding during dry run",
			"should inherit a draft 'Flagship' binding during dry run",
		],
	},
	{
		file: "create-worker-upload-form/bindings.test.ts",
		ancestors: [
			"createWorkerUploadForm — bindings",
			"multiple binding types together",
		],
		status: "skip",
		names: ["should handle a worker with many different binding types"],
	},
	{
		file: "d1/utils.test.ts",
		ancestors: ["getDatabaseInfoFromConfig"],
		status: "skip",
		names: [
			"should handle no database",
			"should handle no matching database",
			"should handle matching database",
			"should handle matching a database with a custom migrations folder",
			"should handle matching a database with custom migrations table",
			"should handle matching a database when there are multiple databases",
		],
	},
	{
		file: "d1/utils.test.ts",
		ancestors: ["getDatabaseByNameOrBinding"],
		status: "skip",
		names: [
			"should handle no database",
			"should resolve a database by name via the D1 API",
			"should resolve an auto-provisioned binding (no database_id) via the D1 API",
			"resolves a binding-only config via the auto-provisioned name (worker name + binding)",
			"does not silently bind to an unrelated DB with the same name as the binding",
			"refuses to guess when binding has no database_name/id and worker has no name",
			"propagates non-404 API errors instead of masking them as not-found",
		],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "durable object migrations"],
		status: "todo",
		names: [
			"should warn when you try to deploy durable objects without a lifecycle declared",
			"does not warn if all the durable object bindings are to external classes",
			"should deploy all migrations on first deploy",
			"should upload migrations past a previously uploaded tag",
			"should not send migrations if they've all already been sent",
		],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "durable object migrations", "dispatch namespaces"],
		status: "todo",
		names: [
			"should deploy all migrations on first deploy",
			"should use a script's current migration tag when publishing migrations",
		],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "durable object exports (declarative)"],
		status: "todo",
		names: [
			"sends the `exports` payload (and omits `migrations`)",
			"renders the success-side reconciliation envelope",
			"renders the error-side reconciliation envelope with per-class detail",
		],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "tail consumers"],
		status: "todo",
		names: ["should allow specifying workers as tail consumers"],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "user limits"],
		status: "todo",
		names: [
			"should allow specifying a cpu millisecond limit",
			"should allow specifying a subrequests limit",
		],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "ai"],
		status: "todo",
		names: ["should upload ai bindings"],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "images"],
		status: "todo",
		names: ["should upload images bindings"],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "stream"],
		status: "todo",
		names: ["should upload stream bindings"],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "python"],
		status: "skip",
		names: [
			"should upload python module defined in wrangler.toml",
			"should print vendor modules correctly in table",
			"should upload python module specified in CLI args",
		],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "hyperdrive"],
		status: "todo",
		names: ["should upload hyperdrive bindings"],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "vpc_services"],
		status: "todo",
		names: [
			"should upload VPC services bindings",
			"should upload multiple VPC services bindings",
		],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "vpc_networks"],
		status: "todo",
		names: [
			"should upload VPC network bindings",
			"should upload multiple VPC network bindings",
			"should upload VPC network bindings with network_id",
		],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "mtls_certificates"],
		status: "todo",
		names: ["should upload mtls_certificate bindings"],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "pipelines"],
		status: "todo",
		names: ["should upload pipelines bindings"],
	},
	{
		file: "deploy/durable-objects.test.ts",
		ancestors: ["deploy", "secrets_store_secrets"],
		status: "todo",
		names: ["should upload secret store bindings"],
	},
	{
		file: "deploy/queues.test.ts",
		ancestors: ["deploy", "queues"],
		status: "todo",
		names: [
			"should upload producer bindings",
			"should update queue producers on deploy",
			"should post worker queue consumers on deploy",
			"should post worker queue consumers on deploy, using command line script name arg",
			"should update worker queue consumers on deploy",
			"should update worker (service) queue consumers with default environment on deploy",
			"should reject http_pull consumer type in config",
			"should support queue consumer concurrency with a max concurrency specified",
			"should support queue consumer concurrency with a null max concurrency",
			"should support queue consumer with max_batch_timeout of 0",
			"consumer should error when a queue doesn't exist",
			"producer should error when a queue doesn't exist",
		],
	},
	{
		file: "dev/remote-bindings.test.ts",
		ancestors: ["dev with remote bindings"],
		status: "skip",
		names: [
			"should attempt to setup remote 'service' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'ai' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'browser render' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'images' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'vectorize' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'dispatch namespace' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'kv namespace' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'flagship app' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'r2 bucket' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'd1' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'mtls' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'pipeline' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'artifacts' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'email' bindings when starting `wrangler dev`",
			"should attempt to setup remote $name bindings when updating config during a running `wrangler dev` session",
			"should not recreate the remote proxy session on reload when auth has not changed",
			"should allow both local and remote KV bindings to the same namespace in a single dev session",
			"does not create remote bindings when `--local` is passed",
			"uses the provided api token and account id when starting the remote proxy session",
			"uses the account_id in the config when starting the remote proxy session",
		],
	},
	{
		file: "guess-worker-format.test.ts",
		ancestors: ["guess worker format"],
		status: "skip",
		names: [
			'should detect a "modules" worker',
			'should detect a "service-worker" worker',
			'should detect a "service-worker" worker using `typeof module`',
			'should detect a "service-worker" worker using imports',
			"should not error if a .js entry point has jsx",
			"detects a legacy Service Worker with a named export using 'global scope'",
			"detects a legacy Service Worker with a named export using 'globalThis'",
			"detects a legacy Service Worker with a named export using 'self'",
			"detects a legacy Service Worker with a named export using 'static bracket notation'",
			"detects a legacy Service Worker with a named export using 'a method alias'",
			"chooses a Module Worker with a named export when using 'locally shadowed globals'",
			"chooses a Module Worker with a named export when using 'receiver aliases'",
			"detects a Module Worker with only a named WorkerEntrypoint",
			"detects a Module Worker with only a DurableObject",
			"detects a Module Worker with only a legacy DurableObject",
			"detects Module Worker via default export over named WorkerEntrypoint and addEventListener",
			"detects Service Worker format when a named Object and addEventListener are both present",
			"detects Service Worker format when a named Entrypoint and addEventListener are both present",
			"should list exports",
			"should detect a modules worker that uses source phase imports",
		],
	},
	{
		file: "middleware.scheduled.test.ts",
		ancestors: ["run scheduled events with middleware", "module workers"],
		status: "skip",
		names: [
			"should not intercept when middleware is not enabled",
			"should intercept when middleware is enabled",
			"should not trigger scheduled event on wrong route",
			"should respond with 404 for favicons",
			"should not respond with 404 for favicons if user-worker has a response",
		],
	},
	{
		file: "middleware.scheduled.test.ts",
		ancestors: ["run scheduled events with middleware", "service workers"],
		status: "skip",
		names: [
			"should not intercept when middleware is not enabled",
			"should intercept when middleware is enabled",
			"should not trigger scheduled event on wrong route",
			"should respond with 404 for favicons",
			"should not respond with 404 for favicons if user-worker has a response",
		],
	},
	{
		file: "pages/functions-build.test.ts",
		ancestors: ["pages functions build"],
		status: "todo",
		names: [
			"should throw an error if no worker script and no Functions directory was found",
			"converts an invalid route in [hyphen-not-allowed].ts to FatalError",
			"converts an invalid route in [[hyphen-not-allowed]].ts to FatalError",
			"should build functions",
			"should include any external modules imported by functions in the output bundle",
			"should output a directory with --outdir",
			"should output a metafile when --metafile is set",
			"should build _worker.js",
			"should include all external modules imported by _worker.js in the output bundle, when bundling _worker.js",
			"should build _worker.js over /functions, if both are present",
			"should leave Node.js imports when the `nodejs_compat` compatibility flag is set",
			"should warn at Node.js imports when the `nodejs_compat` compatibility flag is not set",
			"should compile a _worker.js/ directory",
		],
	},
	{
		file: "pages/functions-build.test.ts",
		ancestors: ["functions build w/ config"],
		status: "todo",
		names: [
			"should include all config in the _worker.bundle metadata",
			"should ignore config with a non-pages config file",
			"should ignore config with a non-pages config file w/ invalid environment",
			"should ignore unparseable config file",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "put", "interactive"],
		status: "todo",
		names: [
			"should trim stdin secret value",
			"should create a secret",
			"should create a secret: preview",
			"should error with invalid env",
			"should error without a project name",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "put", "non-interactive"],
		status: "todo",
		names: [
			"should trim stdin secret value, from piped input",
			"should create a secret, from piped input",
			"should error if the piped input fails",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: [
			"wrangler pages secret",
			"put",
			"non-interactive",
			"with accountId",
		],
		status: "todo",
		names: [
			"should error if request for available accounts fails",
			"should error if a user has no account",
			"should error if a user has multiple accounts, and has not specified an account",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: [
			"wrangler pages secret",
			"put",
			"non-interactive",
			"with accountId",
		],
		status: "skip",
		names: ["should error if request for available memberships fails"],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "delete"],
		status: "todo",
		names: [
			"should delete a secret",
			"should delete a secret: preview",
			"should fail to delete with invalid env",
			"should error without a project name",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "list"],
		status: "todo",
		names: [
			"should list secrets",
			"should list secrets: preview",
			"should fail with invalid env",
			"should error without a project name",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "secret bulk"],
		status: "todo",
		names: [
			"should fail secret bulk w/ no pipe or JSON input",
			"should use secret bulk w/ pipe input",
			"should create secret bulk",
			"should create secret bulk w/ env file",
			"should create secret bulk: preview",
			"should count success and network failure on secret bulk",
			"throws a meaningful error",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "account id resolution"],
		status: "skip",
		names: ["should prefer CLOUDFLARE_ACCOUNT_ID over cached account id"],
	},
	{
		file: "queues/queues-subscription.test.ts",
		ancestors: ["queues subscription", "create"],
		status: "todo",
		names: [
			"should create a subscription for images source",
			"should create a subscription for an Artifacts account source",
			"should create a subscription for an Artifacts repository source",
			"should create a subscription for the Browser Run account source",
			"should create a subscription for email.sending source",
			"should show error when zone-id is missing for email.sending source",
			"should show error when domain is missing for email.sending source",
		],
	},
	{
		file: "queues/queues-subscription.test.ts",
		ancestors: ["queues subscription", "get"],
		status: "skip",
		names: [
			"should render the sending domain as the resource for email.sending source",
		],
	},
	{
		file: "type-generation-pipeline-schema.test.ts",
		ancestors: ["streamNameToTypeName"],
		status: "skip",
		names: [
			"should convert snake_case to PascalCase with Record suffix",
			"should convert kebab-case to PascalCase with Record suffix",
			"should handle single word",
		],
	},
	{
		file: "type-generation-pipeline-schema.test.ts",
		ancestors: ["generatePipelineTypeFromSchema"],
		status: "skip",
		names: [
			"should return generic type for null schema",
			"should return generic type for schema with empty fields",
			"should return generic type for schema with empty fields even when stream name is provided",
			"should return generic type for schema with non-array fields",
			"should generate named type when stream name is provided",
			"should generate inline type when stream name is not provided",
			"should generate type for optional field",
			"should generate types for all primitive types",
			"should generate type for list field",
			"should generate type for nested struct field",
			"should generate type for complex schema with multiple field types",
			"should quote field names that are not valid identifiers",
			"should escape special characters in field names",
			"should handle list without items definition",
			"should handle struct without fields definition",
			"should handle unknown field types gracefully",
			"should limit nesting depth to prevent stack overflow",
		],
	},
	{
		file: "utils/getValidBindingName.test.ts",
		ancestors: ["getValidBindingName"],
		status: "skip",
		names: [
			"should replace dashes with underscores",
			"should replace consecutive underscores with single underscore",
			"should prepend an underscore if it starts with a number",
			"should replace whitespaces with underscores",
			"should remove all invalid character",
			"should not remove alphabetic characters, numbers, or underscores",
			"should fallback if no valid binding name is possible",
			"should fallback if output is only underscores",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
