// Generated from cloudflare/workers-sdk@c2bb4c815. Do not rename cases.
import { describe, it } from "vite-plus/test";

const groups = [
	{
		file: "api/startDevWorker/events.test.ts",
		ancestors: ["castErrorCause"],
		status: "skip",
		names: [
			"returns Error instances unchanged",
			"rehydrates a SerializedError, preserving message/name/stack",
			"rehydrates the serialized nested cause chain into Error instances",
			"wraps other non-Error causes, keeping them as `cause`",
			"preserves message-bearing objects with extra properties verbatim",
		],
	},
	{
		file: "build-output.test.ts",
		ancestors: ["wrangler build --experimental-cf-build-output"],
		status: "skip",
		names: [
			"emits the Build Output Specification tree for a Worker",
			"uses the .js extension for the manifest key even when the entrypoint is .ts",
			"includes modules matched by custom `rules` and types them in the manifest",
			"preserves filenames when `preserveFileNames: true`",
			"copies the assets directory",
			"emits an assets-only Worker (no bundle, no manifest)",
			"writes source maps when `uploadSourceMaps` is enabled",
			"errors when --experimental-cf-build-output is used without --experimental-new-config",
			"errors when a Worker has neither bundle nor assets",
		],
	},
	{
		file: "build-output.test.ts",
		ancestors: [
			"wrangler build --experimental-cf-build-output",
			"root config.json",
		],
		status: "skip",
		names: [
			"is emitted even when there are no account settings",
			"records the mode from --env",
			"records the mode from CLOUDFLARE_ENV",
			"omits the mode when neither --env nor CLOUDFLARE_ENV is set",
			"records the mode alongside account settings",
		],
	},
	{
		file: "cloudchamber/curl.test.ts",
		ancestors: ["cloudchamber curl"],
		status: "skip",
		names: [
			"should help",
			"can send data with -d/--data",
			"supports deprecated -D flag",
			"should set headers",
			"should preserve colons in header values",
			"should error for a header without a colon",
			"should error for a header without a name",
			"works",
			"should give a response with headers and request-id when verbose flag is set",
			"includes headers and request-id in JSON when used with --silent and --verbose",
			"should catch and report errors",
		],
	},
	{
		file: "config/loadDotEnv.test.ts",
		ancestors: ["loadDotEnv()"],
		status: "skip",
		names: [
			"should load environment variables from .env files",
			"should support silent processing",
			"should debug log if .env files are missing",
			"should have case sensitive env properties",
			"should have case insensitive env properties",
			"should include process.env variables if specified",
		],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — basic structure"],
		status: "skip",
		names: [
			"should set main_module for ESM workers",
			"should set body_part for commonjs workers",
			"should include the main module as a form part",
			"should include compatibility_date and compatibility_flags",
			"should include source maps as form parts",
			"should include additional ESM modules as form parts",
			"should throw when commonjs worker has additional modules",
		],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — keep_bindings"],
		status: "skip",
		names: [
			"should include plain_text and json in keep_bindings when keepVars is true",
			"should include secret_text and secret_key in keep_bindings when keepSecrets is true",
			"should combine keepVars, keepSecrets, and keepBindings",
			"should not include keep_bindings when none of keepVars/keepSecrets/keepBindings are set",
		],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — optional metadata fields"],
		status: "skip",
		names: [
			"should include 'logpush' when specified",
			"should include 'Durable Objects code update strategy' when specified",
			"should include 'placement' when specified",
			"should include 'tail_consumers' when specified",
			"should include 'limits' when specified",
			"should include 'observability' when specified",
			"should include 'cache' when specified",
			"should include 'cache with cross version cache' when specified",
			"should include 'exports' when specified",
			"should include 'mixed exports' when specified",
			"should include 'durable object exports with an attach…' when specified",
			"should include 'containers linked by class_name' when specified",
			"should include 'containers linked from the exports si…' when specified",
			"should include 'annotations' when specified",
			"should include containers when specified",
		],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — unsafe metadata"],
		status: "skip",
		names: [
			"should merge unsafe metadata into the metadata object",
			"should prefer an unsafe code update strategy override",
		],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — static assets only"],
		status: "skip",
		names: [
			"should short-circuit for assets-only uploads",
			"should include compatibility_date in assets-only metadata when provided",
		],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: ["deploy", "assets"],
		status: "skip",
		names: [
			"should use the directory specified in the CLI over wrangler.toml",
			"should use the directory specified in the CLI and allow the directory to be missing in the configuration",
			"should error if config.site and config.assets are used together",
			"should error if --assets and config.site are used together",
			"should error if directory specified by flag --assets does not exist in non-interactive mode",
			"should error if the directory path specified by the assets config is undefined",
			"should error if the directory path specified by the assets config is an empty string",
			"should error if directory specified by config assets does not exist",
			"should error if path specified by flag --assets is a file, not a directory",
			"should error if path specified by config assets.directory is a file, not a directory",
			"should resolve assets directory relative to wrangler.toml if using config",
			"should resolve assets directory relative to cwd if using cli",
			"should send bulk asset upload stats with deploy metrics",
		],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: ["deploy", "assets"],
		status: "todo",
		names: [
			"should error if an ASSET binding is provided without a user Worker",
			"should warn when using smart placement with Worker first",
			"should warn if run_worker_first=true but no binding is provided",
			"should error if run_worker_first is true and no user Worker is provided",
			"should attach an 'application/null' content-type header when uploading files with an unknown extension",
			"should be able to upload files with special characters in filepaths",
			"should ignore assets that match patterns in an .assetsignore file in the root of the assets directory",
			"should error if it is going to upload a _worker.js file as an asset",
			"should error if it is going to upload a _worker.js directory as an asset",
			"should not error if it is going to upload a _worker.js file as an asset and there is an .assetsignore file",
			"should not error if it is going to upload a _worker.js file that is not at the root of the asset directory",
			"should error on --dry-run if it is going to upload a _worker.js file as an asset",
			"should upload _redirects and _headers",
			"should upload an asset manifest of the files in the directory specified by --assets",
			"should upload an asset manifest of the files in the directory specified by [assets] config",
			"should upload assets in the requested buckets",
			"should upload each asset individually with raw bytes when wrangler_single_asset_uploads is true",
			"should be able to upload a user worker with ASSETS binding and config",
			"run_worker_first correctly overrides default if set to true",
			"uploads run_worker_first=true when provided in config",
			"uploads run_worker_first=[rules] when provided in config",
			"run_worker_first omitted when not provided in config",
			"should be able to upload an asset-only project",
			"should not provision bindings for an asset-only project",
			"should be able to upload to a WfP script",
			"should error when assets upload session response is null",
			"should retry asset uploads on failure for legacy upload",
			"should retry asset uploads on failure for edge KV upload",
		],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: [
			"deploy",
			"assets",
			"when 'wrangler_single_asset_uploads is miss…'",
		],
		status: "todo",
		names: ["should use legacy base64 bucket upload"],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: [
			"deploy",
			"assets",
			"when 'wrangler_single_asset_uploads is false'",
		],
		status: "todo",
		names: ["should use legacy base64 bucket upload"],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: [
			"deploy",
			"assets",
			"when 'the upload token cannot be decoded'",
		],
		status: "todo",
		names: ["should use legacy base64 bucket upload"],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: ["deploy", "assets", "'legacy' asset uploads"],
		status: "todo",
		names: ["should only recover concurrency after post-throttle successes"],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: ["deploy", "assets", "'single-file' asset uploads"],
		status: "todo",
		names: ["should only recover concurrency after post-throttle successes"],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: ["getEdgeKvUploadConcurrency"],
		status: "skip",
		names: [
			"returns value from JWT claim",
			"returns default when claim is missing",
			"returns default when JWT is undecodable",
		],
	},
	{
		file: "deploy/entry-points.test.ts",
		ancestors: ["deploy", "entry-points"],
		status: "skip",
		names: [
			"should be able to use `index` with no extension as the entry-point (esm)",
			"should be able to use `index` with no extension as the entry-point (sw)",
			"should be able to use the `main` config as the entry-point for ESM sources",
			"should use `main` relative to the wrangler.toml not cwd",
			"should be able to transpile TypeScript (esm)",
			"should be able to transpile TypeScript (sw)",
			"should add referenced text modules into the form upload",
			"should allow cloudflare module import",
			"should be able to transpile entry-points in sub-directories (esm)",
			"should not trigger autoconfig on `wrangler deploy <script>`",
			"should preserve exports on a module format worker",
			"should not preserve exports on a service-worker format worker",
			"should be able to transpile entry-points in sub-directories (sw)",
			'should error if a site definition doesn\'t have a "bucket" field',
			"should warn if there is a `site.entry-point` configuration",
			"should resolve site.entry-point relative to wrangler.toml",
			"should error if both main and site.entry-point are specified",
			"should error if there is no entry-point specified",
		],
	},
	{
		file: "deploy/entry-points.test.ts",
		ancestors: [
			"deploy",
			"entry-points",
			"should source map validation errors",
		],
		status: "skip",
		names: [
			"with TypeScript source file",
			"with additional modules",
			"with inline source map",
		],
	},
	{
		file: "deploy/entry-points.test.ts",
		ancestors: [
			"deploy",
			"entry-points",
			"should interactively handle misconfigured asset-only deployments",
		],
		status: "skip",
		names: [
			"should handle interactive `wrangler deploy <directory>` flows without triggering autoconfig",
			"should handle `wrangler deploy --assets` without name or compat date without triggering autoconfig",
			"should suggest 'my-project' if the default name from the cwd is invalid",
			"should error when --script points to a directory",
			"should error when --script points to a directory even when positional path is also provided",
			"should error when --script points to a directory even when positional path is a file",
			"does not write out a wrangler config file if the user says no",
			"includes script path in suggestion when deprecated --script option is used",
			"includes --assets in suggestion when positional path is a file and --assets is separate",
		],
	},
	{
		file: "deploy/entry-points.test.ts",
		ancestors: ["deploy", "positional path telemetry categorisation"],
		status: "skip",
		names: [
			"records null when no positional is passed",
			"categorises a file entry-point as 'file'",
			"categorises a directory as 'directory'",
			"categorises the current directory reference as 'current-dir'",
			"categorises a parent-relative reference as 'parent-relative'",
		],
	},
	{
		file: "deploy/secrets.test.ts",
		ancestors: ["deploy secrets", "--secrets-file"],
		status: "todo",
		names: [
			"should upload secrets from a JSON file alongside the worker",
			"should upload secrets from a .env file alongside the worker",
			"should set keepSecrets to inherit non-provided secrets when providing secrets file",
			"should fail when secrets file does not exist",
			"should fail when secrets file contains invalid JSON",
		],
	},
	{
		file: "deploy/secrets.test.ts",
		ancestors: ["deploy secrets", "secrets.required"],
		status: "todo",
		names: [
			"should add inherit bindings for required secrets",
			"should error when required secrets are missing from the deployed Worker",
			"should error before uploading when the Worker does not exist",
		],
	},
	{
		file: "deploy/secrets.test.ts",
		ancestors: ["deploy secrets", "--secrets-file with secrets.required"],
		status: "todo",
		names: [
			"should deploy when --secrets-file satisfies all required secrets even if the Worker does not exist",
			"should error listing only the secrets not provided by --secrets-file when the Worker does not exist",
			"should use inherit bindings only for required secrets not provided by --secrets-file",
		],
	},
	{
		file: "dev/start-dev.test.ts",
		ancestors: ["startDev"],
		status: "skip",
		names: [
			"unregisters the latest hotkey registration after auth re-registers hotkeys",
			"prints the Local Explorer API hint when the caller asks for it",
			"does not print the Local Explorer API hint when the caller has not opted in",
		],
	},
	{
		file: "index.test.ts",
		ancestors: ["wrangler", "no command"],
		status: "skip",
		names: ["should not require temporary terms acceptance before root help"],
	},
	{
		file: "index.test.ts",
		ancestors: ["wrangler", "--temporary"],
		status: "skip",
		names: ["is rejected on commands that don't opt in"],
	},
	{
		file: "index.test.ts",
		ancestors: ["wrangler", "command typo suggestions"],
		status: "todo",
		names: [
			"should suggest 'whoami' when user types 'whoamio'",
			"should suggest 'deploy' when user types 'delpoy'",
			"should not suggest anything for a completely unrelated command",
			"should suggest a command even with --help flag",
			"should suggest a subcommand for 'kv namespase'",
			"should suggest a nested subcommand for 'kv namespace craete'",
			"should preserve trailing args in suggestion for 'kv namespase create'",
			"should not suggest a subcommand for a completely unrelated subcommand",
			"should suggest 'whoami' when user types 'who-am-i'",
			"should suggest 'login' when user types 'log-in'",
			"should suggest 'logout' when user types 'log-out'",
		],
	},
	{
		file: "navigator-user-agent.test.ts",
		ancestors: ["isNavigatorDefined"],
		status: "skip",
		names: [
			"default",
			"modern date",
			"old date",
			"switch date",
			"before date",
			"old date, but with flag",
			"old date, with disable flag",
			"new date, but with disable flag",
			"new date, with enable flag",
			"errors with disable and enable flags specified",
		],
	},
	{
		file: "navigator-user-agent.test.ts",
		ancestors: ["defineNavigatorUserAgent is respected"],
		status: "skip",
		names: [
			"preserves `navigator` when `defineNavigatorUserAgent` is `false`",
			"tree shakes `navigator` when `defineNavigatorUserAgent` is `true`",
			"tree shakes `navigator` when `defineNavigatorUserAgent` is `true` and `process.env.NODE_ENV` is `undefined`",
		],
	},
	{
		file: "pages/pages-deployment-tail.test.ts",
		ancestors: ["pages deployment tail", "API interaction"],
		status: "todo",
		names: [
			"should throw an error if deployment isn't provided",
			"creates and then delete tails by deployment ID",
			"only uses deployments with status=success and name=deploy",
			"creates and then deletes tails by deployment URL",
			"errors when passing in a deployment without a project",
			"creates and then delete tails by project name",
			"errors when the websocket closes unexpectedly",
			"passes default environment to deployments list",
			"passes production environment to deployments list",
			"passes preview environment to deployments list",
		],
	},
	{
		file: "pages/pages-deployment-tail.test.ts",
		ancestors: ["pages deployment tail", "API interaction"],
		status: "skip",
		names: ["activates debug mode when the cli arg is passed in"],
	},
	{
		file: "pages/pages-deployment-tail.test.ts",
		ancestors: ["pages deployment tail", "filtering"],
		status: "todo",
		names: [
			"should throw for bad sampling rate filters ranges",
			"should send sampling rate filter",
			"sends single status filters",
			"sends multiple status filters",
			"sends single HTTP method filters",
			"sends multiple HTTP method filters",
			"sends header filters without a query",
			"sends header filters with a query",
			"sends single IP filters",
			"sends multiple IP filters",
			"sends search filters",
			"sends everything but the kitchen sink",
		],
	},
	{
		file: "pages/pages-deployment-tail.test.ts",
		ancestors: ["pages deployment tail", "printing"],
		status: "skip",
		names: [
			"logs request messages in JSON format",
			"logs scheduled messages in JSON format",
			"logs alarm messages in json format",
			"logs email messages in json format",
			"logs queue messages in json format",
			"logs request messages in pretty format",
			"logs scheduled messages in pretty format",
			"logs alarm messages in pretty format",
			"logs email messages in pretty format",
			"logs queue messages in pretty format",
			"defaults to logging in pretty format when the output is a TTY",
			"defaults to logging in json format when the output is not a TTY",
			"logs console messages and exceptions",
		],
	},
	{
		file: "pages/pages-deployment-tail.test.ts",
		ancestors: ["pages deployment tail", "printing"],
		status: "todo",
		names: ["should not crash when the tail message has a void event"],
	},
	{
		file: "paths.test.ts",
		ancestors: ["paths", "getBasePath()"],
		status: "skip",
		names: [
			"should return the path to the wrangler package",
			"should use the __RELATIVE_PACKAGE_PATH__ as defined on the global context to compute the base path",
		],
	},
	{
		file: "paths.test.ts",
		ancestors: ["readableRelative"],
		status: "skip",
		names: [
			"should leave paths to files in the current directory as-is",
			"should leave files in the parent directory as-is",
			"should add ./ to nested paths",
		],
	},
	{
		file: "r2/local-uploads.test.ts",
		ancestors: ["r2 bucket local-uploads", "enable"],
		status: "todo",
		names: ["should error if bucket name is not provided"],
	},
	{
		file: "r2/local-uploads.test.ts",
		ancestors: ["r2 bucket local-uploads", "disable"],
		status: "todo",
		names: ["should error if bucket name is not provided"],
	},
	{
		file: "unstable-get-miniflare-worker-options.test.ts",
		ancestors: ["unstable_getMiniflareWorkerOptions"],
		status: "skip",
		names: ["preserves UDP connect handlers"],
	},
	{
		file: "unstable-get-miniflare-worker-options.test.ts",
		ancestors: [
			"unstable_getMiniflareWorkerOptions",
			"zone derivation (used for the outbound CF-Worker header)",
		],
		status: "skip",
		names: [
			"derives the zone from a single `route` string",
			"uses the first entry in `routes`, preferring its `zone_name`",
			"falls back to the pattern hostname when `zone_name` is absent",
			"uses `zone_name` for unparseable patterns like `*/*`",
			"ignores `dev.host` (the `dev` config block is `wrangler dev`-only)",
			"derives the zone from `routes` even when `dev.host` is also set",
			"returns undefined when no routes are configured",
		],
	},
	{
		file: "unstable-get-miniflare-worker-options.test.ts",
		ancestors: [
			"unstable_getMiniflareWorkerOptions",
			"Cloudflare Access local dev simulation (`ctx.access`)",
		],
		status: "skip",
		names: [
			"passes `access.dev` through to the Miniflare worker options",
			"leaves `access` undefined when no `access` config is present",
		],
	},
	{
		file: "unstable-get-miniflare-worker-options.test.ts",
		ancestors: ["unstable_getMiniflareWorkerOptions", "cron triggers"],
		status: "skip",
		names: [
			"passes through exact cron strings from the selected environment",
			"passes through 'missing' cron triggers",
			"passes through 'empty' cron triggers",
		],
	},
	{
		file: "unstable-get-miniflare-worker-options.test.ts",
		ancestors: ["unstable_getMiniflareWorkerOptions", "workflow bindings"],
		status: "skip",
		names: [
			"drops deploy-only workflow fields that the local runtime has no concept of",
			"surfaces configured workflow exports as workflowExports for the local runtime",
		],
	},
	{
		file: "unstable-get-miniflare-worker-options.test.ts",
		ancestors: [
			"unstable_getMiniflareWorkerOptions",
			"typed services bindings with `dev.plugin`",
		],
		status: "skip",
		names: [
			"routes a typed service binding with `dev.plugin` to miniflare's unsafe-binding plugin pathway",
			"leaves a typed service binding without `dev` on the regular service-binding pathway",
		],
	},
	{
		file: "unstable-get-miniflare-worker-options.test.ts",
		ancestors: [
			"unstable_getMiniflareWorkerOptions",
			"Durable Object-managed Containers",
		],
		status: "skip",
		names: [
			"returns named-image runtime options for Miniflare",
			"attaches an empty Container configuration when no images are configured",
		],
	},
	{
		file: "utils/log-file.test.ts",
		ancestors: ["appendToDebugLogFile"],
		status: "skip",
		names: [
			"should strip ANSI escape codes from error messages",
			"should strip complex ANSI escape sequences",
			"should preserve plain messages without ANSI codes",
			"should handle multiline messages with ANSI codes",
			"should maintain timestamp and log level formatting",
			"should handle empty messages",
			"should handle messages with only ANSI codes",
		],
	},
	{
		file: "utils/log-file.test.ts",
		ancestors: ["cleanupOldLogFiles"],
		status: "skip",
		names: [
			"should delete log files older than 30 days by default",
			"should not delete non-wrangler log files",
			"should keep wrangler log files whose name has no parseable timestamp",
			"should silently succeed if the logs directory does not exist",
		],
	},
	{
		file: "utils/log-file.test.ts",
		ancestors: ["tryCleanupLogs"],
		status: "skip",
		names: [
			"should skip cleanup when WRANGLER_LOG_PATH points to an exact .log file",
			"should not throw when called",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
