// Generated from cloudflare/workers-sdk@c2bb4c815. Do not rename cases.
import { describe, it } from "vite-plus/test";

const groups = [
	{
		file: "agent-memory.test.ts",
		ancestors: ["agent-memory help"],
		status: "todo",
		names: [
			"should show help text when no arguments are passed",
			"should show help text for the namespace subcommand",
		],
	},
	{
		file: "agent-memory.test.ts",
		ancestors: ["agent-memory namespace commands"],
		status: "todo",
		names: [
			"should create a namespace",
			"should create a namespace and output JSON with --json",
			"should list namespaces as JSON with --json",
			"should get a namespace as JSON with --json",
			"should delete a namespace after confirmation",
			"should cancel deletion when confirmation is declined",
			"should delete a namespace without confirmation when --force is passed",
			"should throw a UserError when `get` hits a 404",
			"should throw a UserError when `delete` hits a 404",
			"should throw a UserError when `create` receives a 400 (invalid name)",
			"should throw a UserError when `create` receives a 409 (duplicate)",
		],
	},
	{
		file: "agent-memory.test.ts",
		ancestors: ["agent-memory namespace commands"],
		status: "skip",
		names: [
			"should list namespaces in a table",
			"should print a message when no namespaces exist",
			"should get a namespace in a table",
		],
	},
	{
		file: "api/startDevWorker/MultiworkerRuntimeController.test.ts",
		ancestors: ["MultiworkerRuntimeController"],
		status: "skip",
		names: [
			"tracks image-free Container preparation independently for each Worker",
			"tracks successful image preparation plans per Worker",
		],
	},
	{
		file: "api/startDevWorker/MultiworkerRuntimeController.test.ts",
		ancestors: ["MultiworkerRuntimeController", "stale bundle bail-out"],
		status: "skip",
		names: [
			"should not bail out when different workers submit bundles",
			"supports ratelimit bindings on secondary workers",
			"should skip stale bundles for the same worker during rapid updates",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseArgs", "happy paths"],
		status: "skip",
		names: [
			"parses all flags in --flag value form",
			"parses all flags in --flag=value form",
			"returns an empty object for no flags",
			"omits unset flags from the output",
			"accepts port 0 (OS-assigned)",
			"accepts port 65535 (max)",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseArgs", "port validation"],
		status: "skip",
		names: [
			"rejects negative ports (--port=-1 form)",
			"rejects ports above 65535",
			"rejects fractional ports",
			"rejects non-numeric ports",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: [
			"cf-wrangler parseArgs",
			"rejected flags (allowNegative disabled)",
		],
		status: "skip",
		names: [
			"rejects --no-local with an unknown-flag error",
			"rejects --remote (whole-worker remote dev is out of scope)",
			"rejects other wrangler dev flags we don't support",
			"rejects --env (must use --mode)",
			"rejects --config (config comes from wrangler's discovery)",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseArgs", "structural rejections"],
		status: "skip",
		names: ["rejects positional arguments", "rejects unknown flags"],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseArgs", "ArgParseError"],
		status: "skip",
		names: ["wraps node:util.parseArgs errors"],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseBuildArgs", "happy paths"],
		status: "skip",
		names: [
			"returns an empty object for no flags",
			"parses --mode",
			"parses --mode=value",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseBuildArgs", "rejections"],
		status: "skip",
		names: [
			"rejects --env (must use --mode)",
			"rejects --config (config comes from wrangler's discovery)",
			"rejects unknown flags",
			"rejects positional arguments",
		],
	},
	{
		file: "cloudchamber/images.test.ts",
		ancestors: ["cloudchamber image"],
		status: "todo",
		names: [
			"should help",
			"should create an image registry (no interactivity)",
			"should create an image registry (no interactivity)",
			"should remove an image registry (no interactivity)",
			"should list registries (no interactivity)",
		],
	},
	{
		file: "cloudchamber/images.test.ts",
		ancestors: ["cloudchamber image list"],
		status: "todo",
		names: [
			"should help",
			"should list images",
			"should list images with a filter",
			"should filter out repos with no non-sha tags",
			"should list repos as valid json with json flag set",
			"should filter out repos with no non-sha tags in valid json output",
		],
	},
	{
		file: "cloudchamber/images.test.ts",
		ancestors: ["cloudchamber image delete"],
		status: "todo",
		names: [
			"should help",
			"should delete images",
			"should error when provided a repo without a tag",
		],
	},
	{
		file: "containers/deploy.test.ts",
		ancestors: ["wrangler deploy with containers"],
		status: "todo",
		names: [
			"should upload an empty container list when explicitly configured",
			'keeps variables without generating Container image bindings: {"bindingName":"USER_IMAGES","containers":[]}',
			'keeps variables without generating Container image bindings: {"bindingName":"USER_IMAGES"}',
			"reports a deployed Worker and recovery instructions after application creation fails",
			"rejects unknown-storage legacy classes before deploy uploads",
			"rejects unknown-storage legacy classes before versions upload uploads",
			"deploys a managed registry image without scheduler lookups or rollouts",
			"deploys a managed dockerfile image without scheduler lookups or rollouts",
			"creates an application once and patches changed settings on repeat deployments",
			"should preserve Durable Object-managed container images when --containers-rollout=none",
			'should preserve deployed managed containers with local configuration {"configuration":"empty","keepVars":false} and rollout is disabled',
			'should preserve deployed managed containers with local configuration {"configuration":"omitted","keepVars":false} and rollout is disabled',
			'should preserve deployed managed containers with local configuration {"configuration":"empty","keepVars":true} and rollout is disabled',
			'should preserve deployed managed containers with local configuration {"configuration":"omitted","keepVars":true} and rollout is disabled',
			"preserves deployed containers undefined instead of adding local managed entries when rollout is disabled",
			"preserves deployed containers undefined instead of adding local managed entries when rollout is disabled",
			'rejects rollout skip before upload without deployed versions: {"missing":true,"emptyConfig":false}',
			'rejects rollout skip before upload without deployed versions: {"missing":true,"emptyConfig":true}',
			'rejects rollout skip before upload without deployed versions: {"missing":false,"emptyConfig":false}',
			'rejects rollout skip before upload without deployed versions: {"missing":false,"emptyConfig":true}',
			"allows rollout skip for a first deployment without inheriting an image binding",
			"preserves Container metadata without images or inherited image bindings",
			"should preserve mixed scheduler and Durable Object-managed metadata when --containers-rollout=none",
			"should reject legacy-storage Durable Object-managed containers before upload",
			"should deploy scheduler-backed and Durable Object-managed containers together",
			"cleans up built container images when Worker upload fails",
			"normalizes the diff when enabling ssh on an application without an inferable instance type",
		],
	},
	{
		file: "containers/deploy.test.ts",
		ancestors: [
			"wrangler deploy with containers",
			"observability config resolution",
		],
		status: "todo",
		names: [
			"uses top-level observability for a new application from container config",
			"uses top-level observability for a new application from root fallback",
			"keeps legacy configuration observability enabled for the root enabled shorthand",
			"keeps legacy configuration observability enabled for the root logs shorthand",
			"preserves legacy configuration observability when a rollout updates other fields",
			"migrates mixed observability before 'preserving enabled logs'",
			"migrates mixed observability before 'disabling logs'",
			"migrates mixed observability before 'adding application-level targeting'",
			"waits for an active rollout before migrating mixed observability",
			"waits for an active rollout before enabling top-level observability over legacy observability",
			"can replace an active legacy rollout target while disabling observability for migration",
			"keeps using legacy configuration observability for legacy-enabled apps",
			"keeps using top-level observability and skips rollout for top-level-only changes",
			"updates top-level observability when 'percentage targeting is removed'",
			"updates top-level observability when 'count targeting is removed'",
			"updates top-level observability when 'percentage targeting changes to count…'",
			"detects no changes when top-level observability already matches",
			"avoids no-op migration churn when legacy observability is already disabled",
			"throws a local error when application-level targeting is added before disabling legacy observability",
			"throws a local error when an active rollout still targets legacy observability",
			"still creates a rollout when top-level observability changes alongside deployment config",
		],
	},
	{
		file: "containers/deploy.test.ts",
		ancestors: ["wrangler deploy with containers", "ctx.exports"],
		status: "todo",
		names: [
			"should find a durable object namespace after the first page",
			"deploys a name-only managed Container export with populated images",
			"deploys a name-only managed Container export with empty images",
		],
	},
	{
		file: "containers/deploy.test.ts",
		ancestors: ["wrangler deploy with containers and dispatch namespace"],
		status: "todo",
		names: [
			"creates a managed Container in its own dispatch namespace",
			"rejects rollout skip before uploading an existing dispatch script with 'omitted' local containers",
			"rejects rollout skip before uploading an existing dispatch script with 'empty' local containers",
			"rejects rollout skip before uploading an existing dispatch script with 'renamed' local containers",
			"rejects rollout skip before uploading an existing dispatch script with 'scheduler-backed' local containers",
			"rejects rollout skip before uploading an existing dispatch script with 'mixed with an additional class' local containers",
			"should omit Durable Object-managed images for a new dispatch script when rollout is disabled",
		],
	},
	{
		file: "custom-build.test.ts",
		ancestors: ["Custom Builds"],
		status: "skip",
		names: [
			"runCustomBuild throws UserError when a command fails",
			"runCustomBuild throws UserError when a command is terminated by a signal",
			"runCommand aborts the custom build command",
			"runCommand aborts child processes spawned by shell commands",
		],
	},
	{
		file: "custom-build.test.ts",
		ancestors: ["Custom Builds", "WRANGLER_COMMAND environment variable"],
		status: "skip",
		names: [
			"should set WRANGLER_COMMAND=dev when wranglerCommand is dev",
			"should set WRANGLER_COMMAND=deploy when wranglerCommand is deploy",
			"should set WRANGLER_COMMAND for versions upload",
			"should set WRANGLER_COMMAND=types when wranglerCommand is types",
			"should not set WRANGLER_COMMAND when wranglerCommand is undefined",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings"],
		status: "todo",
		names: [
			"should allow bindings with different names",
			"should error when bindings of different types have the same name",
			"should error when bindings of the same type have the same name",
			"should error correctly when bindings of the same and different types use the same name",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[wasm_modules]"],
		status: "skip",
		names: [
			"should be able to define wasm modules for service-worker format workers",
			"should error when defining wasm modules for modules format workers",
			"should resolve wasm modules relative to the wrangler.toml file",
			"should be able to import .wasm modules from service-worker format workers",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[text_blobs]"],
		status: "skip",
		names: [
			"should be able to define text blobs for service-worker format workers",
			"should error when defining text blobs for modules format workers",
			"should resolve text blobs relative to the wrangler.toml file",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[data_blobs]"],
		status: "skip",
		names: [
			"should be able to define data blobs for service-worker format workers",
			"should error when defining data blobs for modules format workers",
			"should resolve data blobs relative to the wrangler.toml file",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[vars]"],
		status: "todo",
		names: ["should support json bindings"],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[vars]"],
		status: "skip",
		names: [
			"should render config vars literally and --var as hidden",
			"should read vars passed as cli arguments",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[r2_buckets]"],
		status: "todo",
		names: ["should support r2 bucket bindings"],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[logfwdr]"],
		status: "todo",
		names: [
			"should support logfwdr bindings",
			"should error when logfwdr schemas are specified",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[durable_objects]"],
		status: "todo",
		names: [
			"should support durable object bindings",
			"should support durable object bindings to SQLite classes",
			"should support service-workers binding to external durable objects",
			"should support module workers implementing durable objects",
			"should support durable objects and D1",
			"should support durable objects and D1",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[durable_objects]"],
		status: "skip",
		names: [
			"should error when detecting a service-worker worker implementing durable objects",
			"should error when deploying service-worker worker with migrations",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[services]"],
		status: "todo",
		names: [
			"should support service bindings",
			"should support service bindings with entrypoints",
			"should support service bindings with props",
			"should support the internal and non-public facing cross_account_grant service binding field",
			"should strip the local-dev `dev` field from a typed service binding at deploy time",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[analytics_engine_datasets]"],
		status: "todo",
		names: ["should support analytics engine bindings"],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[dispatch_namespaces]"],
		status: "todo",
		names: [
			"should support bindings to a dispatch namespace",
			"should support dispatch namespace bindings with an outbound worker",
			"should support dispatch namespace bindings with parameterized outbounds",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[agent_memory]"],
		status: "todo",
		names: ["should support agent_memory bindings"],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[unsafe]", "[unsafe.bindings]"],
		status: "todo",
		names: [
			"should stringify object in unsafe metadata",
			"should warn if using unsafe bindings",
			"should warn if using unsafe bindings already handled by wrangler",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[unsafe]", "[unsafe.capnp]"],
		status: "skip",
		names: [
			"should accept a pre-compiled capnp schema",
			"should error when both pre-compiled and uncompiled-capnp schemas are used",
			"should error when the capnp compiler is not present, but is required",
			"should accept an uncompiled capnp schema",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[unsafe]", "[unsafe.capnp]"],
		status: "todo",
		names: ["should error when no schemas are specified"],
	},
	{
		file: "deploy/exports-reconciliation.test.ts",
		ancestors: ["renderExportsReconciliationSuccess"],
		status: "todo",
		names: [
			"emits no output when nothing changed",
			"renders created / updated / deleted lists wrapped in blank lines",
			"renders renamed pairs with an arrow",
			"renders transferred and transfer_pending entries",
			"renders info entries dimly under an indented `Info:` heading and surfaces referencing_scripts",
			"renders warnings to stderr under an indented `Warnings:` heading",
			"renders the removable_entries one-liner indented under the block",
			"brackets the block with leading and trailing blank lines",
		],
	},
	{
		file: "deploy/exports-reconciliation.test.ts",
		ancestors: ["renderExportsReconciliationError"],
		status: "todo",
		names: [
			"formats per-class details with scenario, message, and optional fields",
		],
	},
	{
		file: "deploy/exports-reconciliation.test.ts",
		ancestors: ["isExportsReconciliationErrorDetails"],
		status: "todo",
		names: [
			"accepts a well-formed details array",
			"rejects non-array values",
			"rejects entries missing required fields",
		],
	},
	{
		file: "deploy/workflows.test.ts",
		ancestors: ["deploy", "workflows"],
		status: "todo",
		names: [
			"should deploy a workflow",
			"should deploy Artifacts event triggers after their target Workflows",
			"should clear event triggers with an empty array",
			"should reject event targets that are not defined by the Worker",
			"should prompt to create a workers.dev subdomain before deploying owned Workflows",
			"should deploy a workflow with limits",
			"should deploy a workflow with default_retention",
			"should deploy a workflow with concurrency",
			"should deploy a workflow with schedules",
			"should explain that cron-triggered workflows require a paid plan",
			"should update event triggers when an unrelated Workflow fails",
			"should deploy a workflow with schedules as an array of cron expressions",
			"should deploy a workflow with both limits and schedules",
			"should not call Workflow's API if the workflow binds to another script",
			"should error when deploying a workflow with limits that references an external script",
			"should error when deploying a workflow with concurrency that references an external script",
			"should error when deploying a workflow with schedules that references an external script",
			"should error when deploying a workflow with default_retention that references an external script",
		],
	},
	{
		file: "deploy/workflows.test.ts",
		ancestors: ["deploy", "workflows", "workflow exports"],
		status: "todo",
		names: [
			"should upload workflow exports and provision them",
			"should provision every setting declared on a workflow export",
			"should provision a workflow declared by both a binding and an export once",
			"should check a binding against an export using the name passed to --name",
			"should allow event triggers to target workflow exports",
		],
	},
	{
		file: "deploy/workflows.test.ts",
		ancestors: [
			"deploy",
			"workflows",
			"workflow script_name validation with environments",
		],
		status: "todo",
		names: [
			"should error when script_name matches top-level name but not env-suffixed name and limits are set",
			"should allow limits when script_name matches the env-suffixed name",
			"should deploy external script_name under env without limits",
			"should error when script_name matches top-level name but not env-suffixed name and schedules is set",
			"should allow schedules when script_name matches the env-suffixed name",
			"should deploy external script_name under env without schedules",
		],
	},
	{
		file: "deploy/workflows.test.ts",
		ancestors: ["deploy", "workflows", "workflow conflict detection"],
		status: "todo",
		names: [
			"should warn when deploying a workflow that belongs to a different worker",
			"should warn when deploying a workflow export that belongs to a different worker",
			"should abort deploy when user declines the workflow conflict confirmation",
			"should not warn when workflow belongs to the same worker",
			"should not warn when workflow does not exist yet",
			"should warn about multiple conflicting workflows",
			"should skip workflow conflict check in non-interactive mode without --strict",
			"should abort deploy in non-interactive strict mode when workflow belongs to different worker",
		],
	},
	{
		file: "experimental-commands-api.test.ts",
		ancestors: ["experimental_getWranglerCommands"],
		status: "skip",
		names: [
			"returns global flags",
			"returns command tree structure",
			"includes expected commands with metadata",
			"includes nested commands",
			"includes command arguments and metadata",
			"includes namespace commands",
			"preserves command metadata properties",
			"commands opting in to `--temporary` match the expected set",
		],
	},
	{
		file: "is-local.test.ts",
		ancestors: [],
		status: "skip",
		names: [
			'isLocal({"remote":true}, true) -> false',
			'isLocal({"remote":true}, false) -> false',
			'isLocal({"remote":false}, true) -> true',
			'isLocal({"remote":false}, false) -> true',
			'isLocal({"local":true}, true) -> true',
			'isLocal({"local":true}, false) -> true',
			'isLocal({"local":false}, true) -> false',
			'isLocal({"local":false}, false) -> false',
			"isLocal({}, true) -> true",
			"isLocal({}, false) -> false",
		],
	},
	{
		file: "package-manager.test.ts",
		ancestors: ["getPackageManager()", "no supported package manager"],
		status: "todo",
		names: ["should throw an error"],
	},
	{
		file: "package-manager.test.ts",
		ancestors: ["getPackageManager()", "using npm"],
		status: "todo",
		names: ["should return the npm package manager"],
	},
	{
		file: "package-manager.test.ts",
		ancestors: ["getPackageManager()", "using yarn"],
		status: "todo",
		names: ["should return the yarn package manager"],
	},
	{
		file: "package-manager.test.ts",
		ancestors: ["getPackageManager()", "using pnpm"],
		status: "todo",
		names: ["should return the pnpm package manager"],
	},
	{
		file: "package-manager.test.ts",
		ancestors: ["getPackageManager()", "using npm; yarn"],
		status: "todo",
		names: ["should return the npm package manager"],
	},
	{
		file: "package-manager.test.ts",
		ancestors: ["getPackageManager()", "using npm; yarn; pnpm"],
		status: "todo",
		names: ["should return the npm package manager"],
	},
	{
		file: "package-manager.test.ts",
		ancestors: ["getPackageManager()", "using npm; yarn; pnpm; bun"],
		status: "todo",
		names: ["should return the npm package manager"],
	},
	{
		file: "package-manager.test.ts",
		ancestors: ["getPackageManager()", "using bun"],
		status: "todo",
		names: ["should return the bun package manager"],
	},
	{
		file: "pages/pages.test.ts",
		ancestors: ["pages"],
		status: "skip",
		names: [
			"should display a list of available subcommands, for pages with no subcommand",
			"should display a list of available subcommands, for 'pages dev help'",
			"should display a list of available subcommands for 'pages project help`",
			"should display a list of available subcommands for 'pages deployment'",
			"should display a list of available subcommands for 'pages deploy'",
			"should display a list of available subcommands for 'pages secret'",
			"should display a list of available subcommands for 'pages download'",
		],
	},
	{
		file: "pages/pages.test.ts",
		ancestors: ["pages", "deprecation message for deprecated options"],
		status: "skip",
		names: [
			"should display for 'pages dev -- <command>'",
			"should display for 'pages dev --script-path'",
		],
	},
	{
		file: "pages/pages.test.ts",
		ancestors: ["pages", "beta message for subcommands"],
		status: "skip",
		names: [
			"should display for pages:dev",
			"should display for pages:functions:build",
			"should display for pages:functions:optimize-routes",
		],
	},
	{
		file: "preview-config.test.ts",
		ancestors: ["Preview configuration conversion"],
		status: "skip",
		names: [
			"converts a broad supported configuration without production values",
			"copies supported Preview Base configuration and blocks Durable Objects",
			"copies an Issues-only Preview Base observability configuration",
			"returns one no-op outcome for ignored and incomplete bindings",
			"does not read ignored binding payloads",
			"reports unsupported binding messages",
			"reports top-level setting messages",
			"omits tail consumer environments and reports their limitation",
			"inherits production observability",
			"aggregates config, deduplicates messages, and preserves blocking",
			"returns an empty nonblocking aggregate",
			"uses conversion to select production bindings expected in Preview",
			"preserves empty Preview Base values",
			"omits null Preview Base settings without removing JSON null",
			"rejects duplicate singleton bindings",
			"production conversion never serializes unsupported values",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "put"],
		status: "skip",
		names: ["should error helpfully if pages_build_output_dir is set"],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "put", "interactive"],
		status: "todo",
		names: [
			"should trim stdin secret value",
			"should create a secret",
			"should error without a script name",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "put", "non-interactive", "with accountId"],
		status: "todo",
		names: [
			"should error if request for available accounts fails",
			"should error if request for available memberships fails",
			"should error if a user has no account",
			"should error if a user has multiple accounts, and has not specified an account in wrangler.toml",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: [
			"wrangler secret",
			"put",
			"non-interactive",
			"multi-env warning",
		],
		status: "skip",
		names: [
			"should warn if the wrangler config contains environments but none was specified in the command",
			"should not warn if the wrangler config contains environments and one was specified in the command",
			"should not warn if the wrangler config doesn't contain environments and none was specified in the command",
			"should not warn if the wrangler config contains environments and CLOUDFLARE_ENV is set",
			'should not warn if --env="" is passed to explicitly target the top-level environment',
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "delete"],
		status: "skip",
		names: ["should error helpfully if pages_build_output_dir is set"],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "delete"],
		status: "todo",
		names: [
			"should delete a secret",
			"should delete a secret",
			"should error without a script name",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "delete", "multi-env warning"],
		status: "skip",
		names: [
			"should warn if the wrangler config contains environments but none was specified in the command",
			"should not warn if the wrangler config contains environments and one was specified in the command",
			"should not warn if the wrangler config doesn't contain environments and none was specified in the command",
			"should not warn if the wrangler config contains environments and CLOUDFLARE_ENV is set",
			'should not warn if --env="" is passed to explicitly target the top-level environment',
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "list"],
		status: "skip",
		names: ["should error helpfully if pages_build_output_dir is set"],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "list"],
		status: "todo",
		names: [
			"should error without a script name",
			"should error if worker is not found (error code 10007)",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "bulk"],
		status: "skip",
		names: ["should error helpfully if pages_build_output_dir is set"],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "bulk", "multi-env warning"],
		status: "skip",
		names: [
			"should warn if the wrangler config contains environments but none was specified in the command",
			"should not warn if the wrangler config contains environments and one was specified in the command",
			"should not warn if the wrangler config doesn't contain environments and none was specified in the command",
			"should not warn if the wrangler config contains environments and CLOUDFLARE_ENV is set",
			'should not warn if --env="" is passed to explicitly target the top-level environment',
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "login"],
		status: "skip",
		names: [
			"should clear the cached temporary preview account when logging in",
			"should send the `login user` metric when `--scopes` is provided",
			"--use-keyring stores credentials in an encrypted file with a key in the OS keyring",
			"--no-use-keyring scrubs encrypted credentials without writing them to plaintext, then the fresh login uses the file store",
			"--no-use-keyring still scrubs the encrypted credentials and keyring entry when CLOUDFLARE_AUTH_USE_KEYRING=false is set (the env var must not defeat the opt-out scrub)",
			"--use-keyring rolls the keyring_enabled preference back when eager credential-store validation throws",
			"--use-keyring rolls the keyring_enabled preference back when the resolver soft-falls-back to the file store",
			"--use-keyring persists the preference and skips the misleading rollback when CLOUDFLARE_AUTH_USE_KEYRING=false overrides for this command",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "login", "OAuth callback error handling"],
		status: "todo",
		names: [
			"rejects with the bare OAuth error code when no description is provided",
			"rejects with both the OAuth error code and error_description",
			"rejects with the existing consent-denied message for access_denied",
			"rejects with the provider error when /oauth2/token fails after a valid auth code",
			"rejects with the provider error when /oauth2/token returns 2xx with an error body",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "login"],
		status: "todo",
		names: [
			"should error if --scopes contains an invalid scope",
			"should error if --scopes contains multiple invalid scopes",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "auth keyring"],
		status: "skip",
		names: [
			"`auth keyring enable` persists the preference without requiring a login",
			"`auth keyring enable` rolls the preference back when the keyring backend is unavailable",
			"`auth keyring disable` scrubs the default profile's encrypted credentials",
			"`auth keyring disable` scrubs encrypted credentials created via the env var even when the preference was never persisted",
			"`auth keyring` with no action reports the current setting without changing it",
			"`auth keyring` rejects the --profile flag",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User"],
		status: "todo",
		names: [
			"reports an unreachable auth server instead of an expired login, without starting a login (TTY: false)",
			"reports an unreachable auth server instead of an expired login, without starting a login (TTY: true)",
			"refreshes the profile passed to loginOrRefreshIfRequired",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "login (device flow)"],
		status: "skip",
		names: [
			"should complete login on the first successful poll",
			"should display the effective timeout when the server's `expires_in` is shorter than the 5-minute cap",
			"should fall back to constructing a verification URL when the server omits `verification_uri_complete`",
			"should not open the browser when `--browser=false`",
			"should keep polling while the server returns `authorization_pending`, then succeed",
			"should keep polling when a poll fails transiently (non-JSON body), then succeed",
			"should time out with a message reflecting the server's `expires_in` when shorter than the cap",
			"should error with a clear message when the user denies consent",
			"should error with a clear message when the device code expires",
			"should error when `--callback-host` is passed alongside `--device`",
			"should error when `--callback-port` is passed alongside `--device`",
			"should reject the incompatible flag combination before `--no-use-keyring` mutates any credential-storage state",
		],
	},
	{
		file: "user.test.ts",
		ancestors: [
			"User",
			"CLOUDFLARE_API_TOKEN priority over stored OAuth state",
		],
		status: "todo",
		names: [
			"getAPIToken returns the env token even when a stored OAuth token also exists",
			"loginOrRefreshIfRequired does not attempt to refresh an expired OAuth token when env auth is set",
			"wrangler whoami succeeds via env token when a stale OAuth token also exists on disk",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "auth token"],
		status: "todo",
		names: [
			"should re-read refresh_token from disk before refreshing in case a sibling process rotated it",
			"should preserve the stored refresh_token when the OAuth server omits one on refresh",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "getActiveAccountId"],
		status: "todo",
		names: [
			"should return config.account_id when set",
			"should return CLOUDFLARE_ACCOUNT_ID env var when config has no account_id",
			"should prefer env var over cache",
			"should return cached account when config and env var are not set",
			"should return undefined when no source is available",
			"should reject a config.account_id that cannot be used in an API URL",
			"should reject a CLOUDFLARE_ACCOUNT_ID that cannot be used in an API URL",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "getActiveAccountId"],
		status: "skip",
		names: ["should prefer config.account_id over env var and cache"],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "fetchAllAccounts"],
		status: "todo",
		names: [
			"should return the intersection of /accounts and /memberships",
			"should drop accounts present in /accounts but not /memberships",
			"should drop accounts present in /memberships but not /accounts",
			"should throw when no accounts are found",
			"should throw when /accounts and /memberships have no overlap",
			"should fall back to /accounts when /memberships returns 9106 (Account API Token path)",
			"should throw a helpful error on 9106 when /accounts is also unusable",
			"should fall back to /accounts when /memberships returns 10000 (Authentication error)",
			"should throw a helpful error on 10000 when /accounts is also unusable",
			"should include env-var hint when /memberships returns 9106 and /accounts is empty",
			"should propagate /memberships errors that are not 9106 or 10000",
			"should return an empty array instead of throwing when throwOnEmpty is false",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "getOrSelectAccountId with env var"],
		status: "todo",
		names: [
			"should return env var without making API calls",
			"should prefer env var over cached account",
			"should not write to cache when using env var",
			"should not write to cache when using config account_id",
			"should write to cache when account is resolved via API",
			"should reject an invalid env var without making API calls",
		],
	},
	{
		file: "utils/shell-quote.test.ts",
		ancestors: ["quote"],
		status: "skip",
		names: [
			"returns unquoted string for safe arguments",
			"wraps strings with spaces in quotes",
			"escapes special characters",
			"handles single quotes by wrapping in double quotes",
			"handles empty array",
			"handles multiple arguments",
		],
	},
	{
		file: "utils/shell-quote.test.ts",
		ancestors: ["parse"],
		status: "skip",
		names: [
			"parses simple arguments",
			"parses single-quoted strings",
			"parses double-quoted strings",
			"handles escaped characters",
			"handles environment variables when env is provided",
			"returns empty string for unresolved env variable",
			"handles glob patterns",
			"handles comments",
			"throws for control operators",
			"handles empty input",
			"handles Windows-style backslash paths",
			"handles nested quotes",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
