// Generated from cloudflare/workers-sdk@c2bb4c815. Do not rename cases.
import { describe, it } from "vite-plus/test";

const groups = [
	{
		file: "api/startDevWorker/DevEnv.test.ts",
		ancestors: ["DevEnv", "handleErrorEvent"],
		status: "skip",
		names: [
			"should format esbuild BuildFailure errors nicely for BundlerController",
			"should format esbuild BuildFailure from cause for BundlerController",
			"should log non-esbuild BundlerController errors with just the message",
			"should log ProxyWorker request errors without tearing down the dev session",
		],
	},
	{
		file: "banner.test.ts",
		ancestors: ["wrangler banner"],
		status: "skip",
		names: [
			"should display the version banner by default",
			"should hide the version banner when WRANGLER_HIDE_BANNER is present",
			"should not hide the version banner when WRANGLER_HIDE_BANNER=false",
		],
	},
	{
		file: "cloudchamber/create.test.ts",
		ancestors: ["cloudchamber create"],
		status: "todo",
		names: [
			"should help",
			"should fail with a nice message when parameters are missing",
			"should fail with a nice message when image is invalid",
			"should fail with a nice message when parameters are mistyped",
			"should fail with a nice message when instance type is invalid",
			"should fail with a nice message when instance type is set with vcpu",
			"should create deployment (detects no interactivity)",
			"should create deployment with instance type (detects no interactivity)",
			"should create deployment indicating ssh keys (detects no interactivity)",
			"can't create deployment due to lack of fields (json)",
		],
	},
	{
		file: "cloudchamber/create.test.ts",
		ancestors: ["cloudchamber create"],
		status: "skip",
		names: [
			"properly reads wrangler config",
			"properly reads wrangler config for instance type",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["readConfig() upgrade hint"],
		status: "skip",
		names: [
			"should not show an upgrade hint when unexpected fields are found but no update is available",
			"should show an upgrade hint when unexpected fields are found and an update is available",
			"should not show an upgrade hint when warnings are unrelated to unexpected fields",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["readConfig()"],
		status: "skip",
		names: [
			"should not error if a python entrypoint is used with the right compatibility_flag",
			"should error if a python entrypoint is used without the right compatibility_flag",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["experimental_readRawConfig()", "with json config files"],
		status: "skip",
		names: [
			"should find a json config file given a specific path",
			"should find a config file given a specific script",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["experimental_readRawConfig()", "with jsonc config files"],
		status: "skip",
		names: [
			"should find a jsonc config file given a specific path",
			"should find a config file given a specific script",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["experimental_readRawConfig()", "with toml config files"],
		status: "skip",
		names: [
			"should find a toml config file given a specific path",
			"should find a config file given a specific script",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["BOM (Byte Order Marker) handling"],
		status: "skip",
		names: [
			"should remove UTF-8 BOM from TOML config files",
			"should remove UTF-8 BOM from JSON config files",
			"should error on UTF-16 BE BOM",
			"should error on UTF-16 LE BOM",
			"should error on UTF-32 BE BOM",
			"should error on UTF-32 LE BOM",
			"should handle files without BOM normally",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["readConfig() custom_domain inheritance warning"],
		status: "skip",
		names: [
			"should warn when a named env inherits custom_domain routes from the top-level config",
			"should not warn when the env explicitly overrides routes",
			"should not warn for the top-level env itself",
		],
	},
	{
		file: "create-worker-upload-form/commonjs.test.ts",
		ancestors: ["createWorkerUploadForm — commonjs service-worker format"],
		status: "skip",
		names: [
			"should convert 'wasm → wasm_module' bindings in commonjs format",
			"should convert 'text → text_blob' bindings in commonjs format",
			"should convert 'buffer → data_blob' bindings in commonjs format",
			"should handle __STATIC_CONTENT_MANIFEST in commonjs format",
		],
	},
	{
		file: "create-worker-upload-form/commonjs.test.ts",
		ancestors: [
			"createWorkerUploadForm — __STATIC_CONTENT_MANIFEST ESM subdirectories",
		],
		status: "skip",
		names: [
			"should add re-export stubs in subdirectories for the manifest module",
		],
	},
	{
		file: "delete.test.ts",
		ancestors: ["delete"],
		status: "todo",
		names: [
			"should skip Workers Sites namespace cleanup when listing KV namespaces is not permitted",
			"should skip Workers Sites namespace cleanup when deleting a KV namespace is not permitted",
		],
	},
	{
		file: "delete.test.ts",
		ancestors: ["delete", "force deletes"],
		status: "todo",
		names: [
			"should skip dependency checks when listing Worker references is not permitted",
			"should skip dependency checks when listing tail consumers is not permitted",
		],
	},
	{
		file: "deploy/email-routing.test.ts",
		ancestors: ["deploy --dry-run (Email Routing addresses)"],
		status: "todo",
		names: [
			"accepts valid addresses on dry-run and exits without uploading",
			"fails validation for malformed addresses before uploading",
		],
	},
	{
		file: "deploy/routes.test.ts",
		ancestors: ["deploy", "routes"],
		status: "todo",
		names: [
			"should deploy the worker to a route",
			"should deploy with an empty string route",
			"should deploy to a route with a pattern/{zone_id|zone_name} combo",
			"should deploy to a route with a SaaS domain",
			"should deploy to a route with a SaaS subdomain",
			"should fallback to the Wrangler v1 zone-based API if the bulk-routes API fails",
			"should list every conflicting route when routes are assigned to another worker",
			"should list every previously deployed route in the fallback warning",
			"should error if it's a workers.dev route",
		],
	},
	{
		file: "deploy/routes.test.ts",
		ancestors: ["deploy", "routes", "--zone and --zone-id flags"],
		status: "todo",
		names: [
			"should attach a single --zone to all --route patterns",
			"should pair --zone values with --route patterns in argument order",
			"should pair --zone-id values with --route patterns in argument order",
			"should error when --zone is used without --experimental-route-zones",
			"should error when --zone and --zone-id are used together",
			"should error when the number of --zone values does not match the number of --route values",
			"should error when more --zone-id values than --route values are passed",
			"should error when --zone is passed without --route",
		],
	},
	{
		file: "deploy/routes.test.ts",
		ancestors: ["deploy", "routes"],
		status: "skip",
		names: ["should deploy to legacy environment specific routes"],
	},
	{
		file: "deploy/routes.test.ts",
		ancestors: ["deploy", "routes", "custom domains"],
		status: "todo",
		names: [
			"should deploy routes marked with 'custom_domain' as separate custom domains",
			"should not check for zone route conflicts when only custom domains are configured",
			"should pass enabled and previews_enabled to the custom domains API",
			"should not print the Preview provisioning note for an unchanged Preview domain",
			"should not print the Preview provisioning note when previews_enabled is false or omitted",
			"should not print the Preview provisioning note when custom-domain publishing fails",
			"should confirm override if custom domain deploy would override an existing domain",
			"should override a custom domain without confirmation if it already belongs to this Worker environment",
			"should confirm override if custom domain deploy contains a conflicting DNS record",
			"should confirm for conflicting custom domains and then again for conflicting dns",
			"should throw if an invalid custom domain is requested",
			"should not continue with publishing an override if user does not confirm",
		],
	},
	{
		file: "deploy/routes.test.ts",
		ancestors: ["deploy", "routes", "custom domains"],
		status: "skip",
		names: [
			"should deploy domains passed via --domain flag as custom domains",
			"should deploy multiple domains passed via --domain flags",
			"should deploy --domain flags alongside routes (from config when no CLI routes)",
			"should validate domain flags and reject invalid domains with wildcards",
			"should validate domain flags and reject invalid domains with paths",
			"should handle both --route and --domain flags together",
		],
	},
	{
		file: "deploy/routes.test.ts",
		ancestors: ["deploy", "routes", "deploy asset routes"],
		status: "todo",
		names: [
			"shouldn't error on routes with paths if there are no assets",
			"should warn on mounted paths",
			"does not mention 404s hit a Worker if it's assets only",
			"does mention hitting the Worker on 404 if there is one",
			"should not warn on mounted paths if run_worker_first = false",
		],
	},
	{
		file: "deploy/routes.test.ts",
		ancestors: ["deploy", "triggers"],
		status: "todo",
		names: [
			"should deploy the worker with a scheduled trigger",
			"should deploy the worker with an empty array of scheduled triggers",
			"should deploy the worker without updating the scheduled triggers",
			"should deploy the worker without updating the scheduled triggers",
			"should deploy the worker without updating the scheduled triggers",
			"should aggregate errors from multiple failing triggers and still log successful targets",
		],
	},
	{
		file: "dev/remote.test.ts",
		ancestors: ["RemoteSessionAuthenticationError"],
		status: "skip",
		names: [
			"preserves the original error as its cause",
			"sets a static telemetryMessage",
		],
	},
	{
		file: "dev/remote.test.ts",
		ancestors: [
			"RemoteSessionAuthenticationError",
			"when authenticating via CLOUDFLARE_API_TOKEN",
		],
		status: "skip",
		names: ["mentions the API token environment variable in the message"],
	},
	{
		file: "dev/remote.test.ts",
		ancestors: [
			"RemoteSessionAuthenticationError",
			"when authenticating via CLOUDFLARE_API_KEY + CLOUDFLARE_EMAIL",
		],
		status: "skip",
		names: ["mentions the Global API Key environment variable in the message"],
	},
	{
		file: "dev/remote.test.ts",
		ancestors: [
			"RemoteSessionAuthenticationError",
			"when authenticating via OAuth (no env credentials)",
		],
		status: "skip",
		names: ["suggests re-authenticating with wrangler login"],
	},
	{
		file: "hyperdrive.test.ts",
		ancestors: ["hyperdrive planetscale"],
		status: "todo",
		names: [
			"should show the planetscale namespace help",
			"should show the signature command help",
			"should POST to the planetScale integration endpoint",
			"should print only the signature JSON, so it can be piped",
			"should send only the fields the PlanetScale CLI accepts",
		],
	},
	{
		file: "hyperdrive.test.ts",
		ancestors: ["hyperdrive commands"],
		status: "todo",
		names: [
			"should create a hyperdrive config given individual params instead of a connection string",
			"should throw an exception when creating a hyperdrive config without network origin options",
		],
	},
	{
		file: "middleware.test.ts",
		ancestors: [
			"middleware",
			"workers change behaviour with middleware with wrangler dev",
			"module workers",
		],
		status: "skip",
		names: [
			"should register a middleware and intercept",
			"should be able to access scheduled workers from middleware",
			"should trigger an error in a scheduled work from middleware",
		],
	},
	{
		file: "middleware.test.ts",
		ancestors: [
			"middleware",
			"workers change behaviour with middleware with wrangler dev",
			"service workers",
		],
		status: "skip",
		names: [
			"should register a middleware and intercept using addMiddleware",
			"should register a middleware and intercept using addMiddlewareInternal",
			"should be able to access scheduled workers from middleware",
			"should trigger an error in a scheduled work from middleware",
		],
	},
	{
		file: "middleware.test.ts",
		ancestors: [
			"middleware",
			"unchanged functionality when wrapping with middleware",
			"module workers",
		],
		status: "skip",
		names: [
			"should return Hello World with no middleware export",
			"should return hello world with empty middleware array",
			"should return hello world passing through middleware",
			"should return hello world with multiple middleware in array",
			"should leave response headers unchanged with middleware",
			"waitUntil should not block responses",
		],
	},
	{
		file: "middleware.test.ts",
		ancestors: [
			"middleware",
			"unchanged functionality when wrapping with middleware",
			"service workers",
		],
		status: "skip",
		names: [
			"should return Hello World with no middleware export",
			"should return hello world with empty middleware array",
			"should return hello world passing through middleware",
			"should return hello world with addMiddleware function called multiple times",
			"should return hello world with addMiddleware function called with array of middleware",
			"should return hello world with addMiddlewareInternal function called multiple times",
			"should return hello world with addMiddlewareInternal function called with array of middleware",
			"should return hello world with both addMiddleware and addMiddlewareInternal called",
			"should leave response headers unchanged with middleware",
			"should allow multiple addEventListeners for fetch",
			"waitUntil should not block responses",
		],
	},
	{
		file: "middleware.test.ts",
		ancestors: ["middleware", "multiple middleware"],
		status: "skip",
		names: [
			"should build multiple middleware as expected",
			"should respond correctly with D1 databases, scheduled testing, and formatted dev errors",
		],
	},
	{
		file: "pages/pages-build-env.test.ts",
		ancestors: ["pages build env"],
		status: "skip",
		names: [
			"should render empty object",
			"should fail with no project dir",
			"should fail with no outfile",
			"should exit with specific exit code if no config file is found",
			"should exit with specific code if a non-pages config file is found",
			"should exit correctly with an unparseable non-pages config file",
			"should exit correctly with a non-pages config file w/ invalid environment",
			"should throw an error if an invalid pages config file is found",
			"should exit if an unparseable pages config file is found",
			"should return top-level by default",
			"should return top-level by default (json)",
			"should return production",
			"should return preview",
			"should render output directory path relative to project directory, even if wrangler config is redirected",
		],
	},
	{
		file: "pages/utf8-truncation.test.ts",
		ancestors: ["truncateUtf8Bytes"],
		status: "skip",
		names: [
			"should not truncate strings under the limit",
			"should not truncate strings exactly at the limit",
			"should truncate ASCII strings over the limit",
			"should handle Cyrillic characters (2 bytes each)",
			"should handle long Cyrillic text",
			"should handle Japanese characters (3 bytes each)",
			"should handle emoji (4 bytes each)",
			"should not split multi-byte UTF-8 sequences",
			"should handle continuation bytes at boundary",
			"should handle mixed ASCII and multi-byte characters",
			"should handle empty string",
			"should handle single multi-byte character at boundary",
			"should preserve valid UTF-8 structure",
			"should handle exactly 384 bytes with multi-byte chars",
			"should handle 385 bytes with multi-byte chars",
		],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "list"],
		status: "todo",
		names: ["should list queues' jurisdictions, if present"],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "create", "wrangler.json"],
		status: "todo",
		names: [
			"should create a queue",
			"should send queue settings with delivery delay",
		],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "create", "wrangler.toml"],
		status: "todo",
		names: [
			"should create a queue",
			"should send queue settings with delivery delay",
		],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "consumer list"],
		status: "skip",
		names: [
			"should show the correct help text",
			"should show empty message when queue has no consumers",
		],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "consumer list"],
		status: "todo",
		names: [
			"should list both worker and http consumers",
			"should list only worker consumers when queue has no http consumers",
			"should list only http consumers when queue has no worker consumers",
			"should show error when queue does not exist",
			'should output consumers as JSON with "--json" flag',
			'should output empty array as JSON with "--json" flag when no consumers',
		],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "consumer worker list"],
		status: "skip",
		names: [
			"should show the correct help text",
			"should show empty message when queue has no worker consumers",
		],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "consumer worker list"],
		status: "todo",
		names: [
			"should list worker consumers",
			"should show error when queue does not exist",
			'should output worker consumers as JSON with "--json" flag',
			'should output empty array as JSON with "--json" flag when no worker consumers',
		],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "consumer http list"],
		status: "skip",
		names: [
			"should show the correct help text",
			"should show empty message when queue has no http consumers",
		],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "consumer http list"],
		status: "todo",
		names: [
			"should list http consumers",
			"should show error when queue does not exist",
			'should output http consumers as JSON with "--json" flag',
			'should output empty array as JSON with "--json" flag when no http consumers',
		],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "queues", "info"],
		status: "todo",
		names: ["should return queue info with jurisdiction, if present"],
	},
	{
		file: "queues/queues.test.ts",
		ancestors: ["wrangler", "purge"],
		status: "todo",
		names: ["allows purge with the --force flag in non-interactive mode"],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["isValidIdentifier"],
		status: "skip",
		names: [
			"should return true for valid identifiers",
			"should return false for invalid identifiers",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["escapeTypeScriptString"],
		status: "skip",
		names: ["should escape special characters"],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["constructTypeKey"],
		status: "skip",
		names: [
			"should return a valid type key",
			"should escape special characters in quoted keys",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["constructTSModuleGlob() should return a valid TS glob "],
		status: "skip",
		names: [
			"'*.wasm' -> undefined",
			"'*.txt' -> undefined",
			"'*/foo' -> undefined",
			"'*foo' -> undefined",
			"'file.foo' -> undefined",
			"'folder/file.foo' -> undefined",
			"'folder/*' -> undefined",
			"'folder/*' -> undefined",
			"'folder/*' -> undefined",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generateImportSpecifier"],
		status: "skip",
		names: ["should generate a relative import specifier"],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["getEnvHeader"],
		status: "skip",
		names: [
			"should generate a header with the provided hash and command",
			"should include complex commands with flags",
			"should handle empty hash",
			"should use process.argv when command is not provided",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["toPascalCase"],
		status: "skip",
		names: [
			"should convert simple strings to PascalCase",
			"should convert kebab-case to PascalCase",
			"should convert snake_case to PascalCase",
			"should handle mixed separators",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["toEnvInterfaceName"],
		status: "skip",
		names: [
			"should add Env suffix to environment names",
			"should deduplicate Env suffix",
			"should handle kebab-case environment names",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["validateEnvInterfaceNames"],
		status: "skip",
		names: [
			"should not throw for valid, unique environment names",
			"should throw for reserved name Env",
			"should throw when two environment names convert to the same interface name",
			"should throw when names with different separators collide",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["throwMissingBindingError"],
		status: "skip",
		names: [
			"should throw a `UserError` for top-level bindings with array index",
			"should throw a `UserError` for environment bindings with array index",
			"should handle non-array bindings (index omitted)",
			"should handle undefined config path",
			"should handle different field names",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI"],
		status: "skip",
		names: [
			"keeps the runtime header stable after trailing whitespace is removed",
			"should error when no config file is detected",
			"should error when a specified custom config file is missing",
			"should respect the top level -c|--config flag",
			"should log the interface type generated and declare modules",
			"should include stringified process.env types for vars, secrets, and json",
			"should handle multiple worker configs",
			"should resolve secondary worker types when env overrides the worker name",
			"should create a DTS file at the location that the command is executed from",
			"should create a DTS file at the location that the command is executed from",
			"should log the declare global type generated and declare modules",
			"should accept a toml file without an entrypoint and fallback to the standard modules declarations",
			"should not error if expected entrypoint is not found and assume module worker",
			"should include secret keys from .dev.vars",
			"should use explicit --env-file instead of .dev.vars when both exist",
			"should not report stale types when --env-file is used and .dev.vars exists (--check)",
			"should report types as up to date for multi-worker setup without re-passing -c flags (--check)",
			"should include secret keys from .env, if there is no .dev.vars",
			"should allow opting out of strict-vars",
			"should use native Container image types without a generated environment binding",
			"should override vars with secrets",
			"should generate types from config `secrets.required`",
			"should ignore .dev.vars when config `secrets` is defined",
			"should ignore .env when config `secrets` is defined",
			"should generate types for per-env config `secrets`",
			"should not fall back to .dev.vars for envs without `secrets` when another env declares `secrets`",
			"should exclude .dev.vars keys when `secrets` is declared without `required`",
			"various different types of vars",
			"should generate types for VPC services bindings",
			"should generate types for VPC networks bindings",
			"should generate types for VPC networks bindings with network_id",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "when nothing was found"],
		status: "skip",
		names: [
			"should not create DTS file for service syntax workers if env only",
			"should create DTS file for service syntax workers with runtime types only",
			"should create a DTS file with an empty env interface for module syntax workers",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: [
			"generate types - CLI",
			"vars present in multiple environments",
		],
		status: "skip",
		names: [
			"should produce string and union types for variables (default)",
			"should produce non-strict types for variables (with --strict-vars=false)",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: [
			"generate types - CLI",
			"bindings present in multiple environments",
		],
		status: "skip",
		names: [
			"should collect bindings from all environments when no --env is specified",
			"should only collect bindings from the specified environment when --env is used",
			"should deduplicate bindings with the same name across environments",
			"should produce union types when binding name has different types across environments",
			"should error when a binding is missing its binding name in an environment",
			"should error when a binding is missing its binding name at top-level",
			"should collect vars only from specified environment with --env",
			"should mark bindings as optional if not present in all environments",
			"should not include top-level bindings in per-environment interfaces",
			"should include secrets in per-environment interfaces since they are inherited",
			"should mark inheritable bindings as required when defined at top-level",
			"should allow inheritable bindings to be overridden in named environments",
			"should mark inheritable bindings as optional when only defined in some environments",
			"should not inherit top-level inheritable bindings when env defines the property without a binding",
			"should produce union types for vars with different values across environments",
			"should generate simple Env when no environments are defined",
			"should error when environment names would collide after conversion",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "customization", "env"],
		status: "skip",
		names: [
			"should allow the user to customize the interface name",
			"should error if --env-interface is specified with no argument",
			"should error if an invalid interface identifier is provided to --env-interface",
			"should error if --env-interface is used with a service-syntax worker",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "customization", "output file"],
		status: "skip",
		names: [
			"should allow the user to specify where to write the result",
			"should error if the user points to a non-d.ts file",
			"should error if both --include-env and --include-runtime are false",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "customization"],
		status: "skip",
		names: ["should allow multiple customizations to be applied together"],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "runtime types output"],
		status: "skip",
		names: [
			"errors helpfully if you use --experimental-include-runtime",
			"prints something helpful if you have @cloudflare/workers-types",
			"prints something helpful if you have a runtime file at the old default location",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "declarative Durable Object `exports`"],
		status: "skip",
		names: [
			"populates `durableNamespaces` from live `exports` entries (including unbound + `expecting-transfer`) and excludes tombstones",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - API"],
		status: "skip",
		names: [
			"returns combined and split `env` output",
			"returns `runtime` output when `env` types are excluded",
			"supports `strictVars=false` and custom env interface/path",
			"builds `env` header command from API options, not process args",
			"supports multi-config service resolution",
			"validates API options",
			"matches CLI output for `env` only generation",
			"matches CLI output for `runtime` + `env` generation",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["pipeline schema type generation"],
		status: "skip",
		names: [
			"should generate typed pipeline bindings when API returns schema",
			"should fall back to generic type when API returns unstructured stream",
			"should fall back to generic type when API call fails",
			"should handle multiple pipelines with different schemas",
			"should handle nested struct types in schema",
			"should generate pipeline types without Cloudflare namespace prefix for service-worker format",
		],
	},
	{
		file: "utils/levenshtein.test.ts",
		ancestors: ["levenshteinDistance"],
		status: "skip",
		names: [
			"should return 0 for identical strings",
			"should return the length of the other string when one is empty",
			"should return 0 for two empty strings",
			"should handle single character insertions",
			"should handle single character deletions",
			"should handle single character substitutions",
			"should handle transpositions as two edits",
			"should handle completely different strings",
			"should be symmetric",
			"should handle single character strings",
			"should compute correct distance for longer strings",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
