// Generated from cloudflare/workers-sdk@c2bb4c815. Do not rename cases.
import { describe, it } from "vite-plus/test";

const groups = [
	{
		file: "api/startDevWorker/BundlerController.assets-watcher.test.ts",
		ancestors: ["BundlerController — assets watcher"],
		status: "skip",
		names: [
			"a pending assets refresh is discarded on teardown",
			"a pending assets refresh is discarded when the config is replaced",
			"logs a warning and disables the watcher when chokidar emits EMFILE",
			"logs a warning and closes the watcher for non-EMFILE watcher errors",
			"no watchers are created by a config reload that outlives teardown",
		],
	},
	{
		file: "auth-credentials.test.ts",
		ancestors: ["writeAuthCredentials"],
		status: "skip",
		names: [
			"round-trips a UserAuthConfig through the TOML file",
			"writes a new auth config file with mode 0o600",
			"tightens permissions on a pre-existing auth config file with looser mode",
		],
	},
	{
		file: "auth-credentials.test.ts",
		ancestors: ["createTomlFileStorage read() contract"],
		status: "skip",
		names: [
			"returns undefined when the file does not exist",
			"returns undefined for an unparseable file rather than throwing",
			"propagates genuine I/O errors (e.g. when the path is a directory)",
		],
	},
	{
		file: "cloudchamber/apply.test.ts",
		ancestors: ["cloudchamber apply"],
		status: "skip",
		names: [
			"should show deprecation warning when running cloudchamber apply",
			"can apply a simple application",
			"can apply a simple existing application",
			"can apply a simple existing application and create other (max_instances)",
			"can skip a simple existing application and create other",
			"can apply a simple existing application and create other",
			"can apply a simple existing application (labels)",
			"can apply an application, and there is no changes (retrocompatibility with regional scheduling policy)",
			"can apply an application, and there is no changes (two applications)",
			"can apply an application, and there is no changes",
			"can enable observability logs (top-level field)",
			"can enable observability logs (logs field)",
			"can disable observability logs (top-level field)",
			"can disable observability logs (logs field)",
			"can disable observability logs (absent field)",
			"keeps observability logs enabled",
			"keeps observability logs disabled (undefined in the app)",
			"keeps observability logs disabled (false in the app)",
			"can apply a simple application (instance type)",
			"can apply a simple application (custom instance type)",
			"can apply a simple existing application (instance type)",
			"can apply a simple existing application (custom instance type)",
			"falls back on dev instance type when instance type is absent",
			"expands image names from managed registry when creating an application",
			"expands image names from managed registry when modifying an application",
			"updates affinities",
		],
	},
	{
		file: "config-cache.test.ts",
		ancestors: ["config cache", "basic operations"],
		status: "skip",
		names: [
			"should return an empty config if no file exists",
			"should read and write values without overriding old ones",
		],
	},
	{
		file: "config-cache.test.ts",
		ancestors: ["config cache", "cache directory resolution"],
		status: "skip",
		names: [
			"should use .wrangler/cache when no node_modules exists",
			"should respect WRANGLER_CACHE_DIR environment variable",
			"should prioritize WRANGLER_CACHE_DIR over any other detection",
			"should always return a string (never null)",
		],
	},
	{
		file: "core/main-handleerror-fallback.test.ts",
		ancestors: ["main() handleError fallback"],
		status: "todo",
		names: ["writes original error to stderr when handleError throws"],
	},
	{
		file: "d1/splitter.test.ts",
		ancestors: ["normalizeSqlLineEndings()"],
		status: "skip",
		names: ["should preserve CRLF inside quoted SQL values and identifiers"],
	},
	{
		file: "d1/splitter.test.ts",
		ancestors: ["mayContainMultipleStatements()"],
		status: "skip",
		names: [
			"should return false if there is only a semi-colon at the end",
			"should return true if there is a semi-colon before the end of the string",
			"should return true if there is more than one statement",
		],
	},
	{
		file: "d1/splitter.test.ts",
		ancestors: ["splitSqlQuery()"],
		status: "skip",
		names: [
			"should trim a regular old sqlite dump",
			"should return original SQL if there are no real statements",
			"should not split single statements",
			"should handle strings",
			"should handle inline comments",
			"should handle block comments",
			"should split multiple statements",
			"should ignore comment at the end",
			"should handle whitespace between statements",
			"uses SQLite rather than PostgreSQL dollar quote syntax",
			"matches SQLite statement boundaries",
			"splits trigger fixtures from SQLite",
			"drops only statement fragments containing no useful SQL token",
			"does not classify keyword-looking or quoted identifiers as keywords",
			"preserves an unterminated bracket identifier after a complete statement",
			"preserves an unterminated quoted value after a complete statement",
			"should handle compound statements for BEGINs",
			"should handle a lowercase end closing a compound statement",
			"should handle compound statements for CASEs",
		],
	},
	{
		file: "d1/splitter.test.ts",
		ancestors: [
			"splitSqlQuery()",
			"regression tests from splitter PRs #15234 #15226 #15163",
		],
		status: "skip",
		names: [
			"keeps a CASE value expression followed by a comma inside a trigger",
			"keeps a parenthesized CASE expression inside a trigger",
			"does not treat an identifier ending in CASE as a keyword",
			"does not treat an accented identifier beginning with END as a keyword",
			"does not treat qualified keyword identifiers as trigger boundaries",
			"recognizes CASE immediately followed by a parenthesized expression",
			"recognizes a compact END after a parenthesized expression",
			"handles bracket-quoted identifiers containing semicolons",
			"handles END directly after a statement semicolon",
			"handles BEGIN directly after a parenthesis",
			"handles CASE expressions followed by parentheses and commas",
			"does not treat an identifier ending in END as a keyword",
			"does not treat accented identifiers ending in END as keywords",
			"does not treat named parameters as trigger boundaries",
			"does not treat bracket-quoted identifiers as trigger boundaries",
			"keeps CASE expressions inside trigger bodies",
			"does not treat keyword-shaped identifiers as trigger boundaries",
			"handles trigger boundaries separated by comments",
			"handles temporary triggers",
		],
	},
	{
		file: "d1/splitter.test.ts",
		ancestors: ["splitSqlQuery()", "performance tests"],
		status: "skip",
		names: [
			"should split a file with a lot of commands",
			"should split a file with a large quoted value quickly",
			"should split a file with very long comments quickly",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy"],
		status: "skip",
		names: [
			"should output log file with deployment details",
			"should successfully deploy with CI tag match",
			"should successfully override name with WRANGLER_CI_OVERRIDE_NAME",
			"should successfully override name with WRANGLER_CI_OVERRIDE_NAME and outputs the correct output file",
			"should resolve wrangler.toml relative to the entrypoint",
			"should support wrangler.json",
			"should include serialised FormData in debug logs",
			"should support wrangler.jsonc",
			"should error helpfully if pages_build_output_dir is set in wrangler.toml when --no-autoconfig",
			"should error helpfully if pages_build_output_dir is set in wrangler.toml",
			"should attempt to run the autoconfig flow when pages_build_output_dir",
			"in non-interactive mode, attempts to deploy a Pages project using autoconfig",
			"should not run autoconfig when --config is explicitly provided",
			"should resolve wrangler.toml relative to the entrypoint",
			"should output a deploy and an autoconfig output entry to WRANGLER_OUTPUT_FILE_PATH if autoconfig run",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy"],
		status: "todo",
		names: [
			"should not deploy if there's any other kind of error when checking deployment source",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "output additional script information"],
		status: "skip",
		names: [
			"for first party workers, it should print worker information at log level",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication"],
		status: "todo",
		names: ["drops a user into the login flow if they're unauthenticated"],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication"],
		status: "skip",
		names: [
			"creates a temporary preview account in interactive mode when --temporary is passed",
			"requires --temporary when --event-code is passed",
			"rejects a blank event code",
			"does not accept --event-code on versions upload",
			"rejects repeated event codes without exposing their values",
			"provisions an event account before deploying",
			"aborts in interactive mode when the terms are not accepted",
			"warns a user when they're authenticated with an API token in wrangler config file",
			"throws when the user is already authenticated and requests a temporary account",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication", "with an alternative auth domain"],
		status: "todo",
		names: ["drops a user into the login flow if they're unauthenticated"],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication", "with temporary preview accounts"],
		status: "skip",
		names: [
			"creates a temporary preview account in non-interactive mode after printing terms notice",
			"throws when an OAuth token is on disk, even if it is expired and cannot refresh",
			"provisions the preview account against the staging API and caches it per-environment",
			"reuses a cached temporary preview account for later temporary deploys",
			"treats a malformed temporary preview account cache as a miss and refetches",
			"should fail clearly if the temporary preview account request fails",
			"fails the deploy when the proof-of-work challenge can't be obtained",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication", "with temporary preview accounts"],
		status: "todo",
		names: [
			"should not throw an error in non-TTY if 'CLOUDFLARE_API_TOKEN' & 'account_id' are in scope",
			"should not throw an error if 'CLOUDFLARE_ACCOUNT_ID' & 'CLOUDFLARE_API_TOKEN' are in scope",
			"should throw an error in non-TTY & there is more than one account associated with API token",
			"should redact account names in CI even when non-interactive",
			"should throw error in non-TTY if 'CLOUDFLARE_API_TOKEN' is missing",
			"should throw error with no account ID provided and no members retrieved",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "warnings"],
		status: "todo",
		names: ["should warn user when worker was last deployed from api"],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "warnings"],
		status: "skip",
		names: [
			"should warn user when additional properties are passed to a services config",
			"should log esbuild warnings",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "environments"],
		status: "skip",
		names: ["should use legacy environments by default"],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "environments", "legacy"],
		status: "skip",
		names: [
			"uses the script name when no environment is specified",
			"appends the environment name when provided, and there is associated config",
			"appends the environment name when provided (with a warning), if there are no configured environments",
			"should throw an error when an environment name when provided, which doesn't match those in the config",
			"should allow --env and --name to be used together",
		],
	},
	{
		file: "deploy/name-collision-guard.test.ts",
		ancestors: ["deploy name-collision guard (non-interactive)"],
		status: "skip",
		names: [
			"aborts when an agent-generated name matches an existing Worker",
			"aborts when the delegated name was auto-generated (no --name)",
			"aborts even when the delegated name was carried across as --name",
			"does not guard a plain non-interactive deploy (no delegation)",
		],
	},
	{
		file: "dev/get-local-persistence-path.test.ts",
		ancestors: ["getLocalPersistencePath", "when persistence is disabled"],
		status: "skip",
		names: ["should return `false` when `persistTo` is `false`"],
	},
	{
		file: "dev/get-local-persistence-path.test.ts",
		ancestors: [
			"getLocalPersistencePath",
			"when persistence is enabled with default path",
		],
		status: "skip",
		names: [
			"should return `.wrangler/state` relative to cwd when no config path",
			"should return `.wrangler/state` relative to config file directory",
		],
	},
	{
		file: "dev/get-local-persistence-path.test.ts",
		ancestors: [
			"getLocalPersistencePath",
			"when persistence path is explicitly specified",
		],
		status: "skip",
		names: [
			"should resolve relative path from cwd",
			"should resolve absolute path from cwd",
			"should resolve relative path from cwd even when config path is set",
		],
	},
	{
		file: "friendly-validator-errors.test.ts",
		ancestors: ["helpIfErrorIsSizeOrScriptStartup"],
		status: "skip",
		names: [
			"cleanly reports a startup error even if bundle analysis fails",
			"reports size errors even if bundle analysis would fail",
			"writes a profile for a nested project root when bundle analysis succeeds",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: ["metrics", "getMetricsDispatcher()", "sendAdhocEvent()"],
		status: "skip",
		names: [
			"should send a request to the default URL",
			"should include parsed wrangler version components in events",
			"should write a debug log if the dispatcher is disabled",
			"should write a debug log if the request fails",
			"should write a warning log if no source key has been provided",
			"should include agent ID when detected",
			"should set agent to null if detection returns null id",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: [
			"metrics",
			"getMetricsDispatcher()",
			"agent skills install status fetch",
		],
		status: "skip",
		names: [
			"should not query the GitHub skills API if the dispatcher is disabled",
			"should query the GitHub skills API once if the dispatcher is enabled",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: ["metrics", "getMetricsDispatcher()", "sendCommandEvent()"],
		status: "skip",
		names: [
			"should send a started and completed event",
			"should send a started and errored event",
			"should mark isCI as true if running in CI",
			"should mark isPagesCI as true if running in Pages CI",
			"should mark isWorkersCI as true if running in Workers CI",
			"should capture Workers + Assets projects",
			"should not send arguments with wrangler login",
			"should include args provided by the user",
			"should mark as non-interactive if running in non-interactive environment",
			"should include an error message if the specific error has been allow-listed with {telemetryMessage:true}",
			"should include an error message if the specific error has been allow-listed with a custom telemetry message",
			"should include agent ID in command events when detected",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: [
			"metrics",
			"getMetricsDispatcher()",
			"sendCommandEvent()",
			"banner",
		],
		status: "skip",
		names: [
			"should print the banner if current version is different to the stored version",
			"should not print the banner if current version is the same as the stored version",
			"should print the banner if nothing is stored under bannerLastShown and then store the current version",
			"should not print the banner if telemetry permission is disabled",
			"should *not* print the banner if command is not dev/deploy/docs",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: ["metrics", "getMetricsConfig()", "enabled"],
		status: "skip",
		names: [
			"should return the WRANGLER_SEND_METRICS environment variable for enabled if it is defined",
			"should return enabled false if the DO_NOT_TRACK environment variable is set",
			"should let DO_NOT_TRACK override the WRANGLER_SEND_METRICS environment variable",
			"should ignore DO_NOT_TRACK if it is not set to an opt-out value",
			"should return the sendMetrics argument for enabled if it is defined",
			"should return enabled true if the user on this device previously agreed to send metrics",
			"should return enabled false if the user on this device previously refused to send metrics",
			"should print a message if the permission date is older than the current metrics date",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: ["metrics", "getMetricsConfig()", "deviceId"],
		status: "skip",
		names: [
			"should return a deviceId found in the config file",
			"should create and store a new deviceId if none is found in the config file",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: ["metrics", "metrics commands", "metrics status"],
		status: "skip",
		names: [
			"prints the current telemetry status based on the cached metrics config",
			"shows the wrangler config as the source when send_metrics is present",
			"shows WRANGLER_SEND_METRICS as the source if used",
			"defaults to enabled if metrics config is not set",
			"prioritises environment variable over send_metrics",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: ["metrics", "metrics commands"],
		status: "skip",
		names: [
			'disables telemetry when "wrangler metrics disable" is run',
			'doesn\'t send telemetry when running "wrangler metrics disable"',
			'does send telemetry when running "wrangler metrics enable"',
			'enables telemetry when "wrangler metrics enable" is run',
			'persists enabled but reports disabled when "wrangler metrics enable" is run with DO_NOT_TRACK',
			"doesn't overwrite c3 telemetry config",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: ["metrics", "telemetry commands", "telemetry status"],
		status: "skip",
		names: [
			"prints the current telemetry status based on the cached metrics config",
			"shows the wrangler config as the source when send_metrics is present",
			"shows WRANGLER_SEND_METRICS as the source if used",
			"defaults to enabled if metrics config is not set",
			"prioritises environment variable over send_metrics",
		],
	},
	{
		file: "metrics.test.ts",
		ancestors: ["metrics", "telemetry commands"],
		status: "skip",
		names: [
			'disables telemetry when "wrangler telemetry disable" is run',
			'doesn\'t send telemetry when running "wrangler telemetry disable"',
			'does send telemetry when running "wrangler telemetry enable"',
			'enables telemetry when "wrangler telemetry enable" is run',
			'persists enabled but reports disabled when "wrangler telemetry enable" is run with DO_NOT_TRACK',
			"doesn't overwrite c3 telemetry config",
		],
	},
	{
		file: "pages/deployment-list.test.ts",
		ancestors: ["pages deployment list"],
		status: "todo",
		names: [
			"should make request to list deployments",
			"should pass no environment",
			"should pass production environment with flag",
			"should pass preview environment with flag",
		],
	},
	{
		file: "pages/deployment-list.test.ts",
		ancestors: ["pages deployment list"],
		status: "skip",
		names: [
			"should make request to list deployments and return result as json",
			"should prefer CLOUDFLARE_ACCOUNT_ID over cached account id",
		],
	},
	{
		file: "pages/routes-validation.test.ts",
		ancestors: ["routes-validation adapter"],
		status: "skip",
		names: [
			"converts invalid JSON specs to FatalError",
			"converts missing include rules to FatalError",
			"converts too many rules to FatalError",
			"converts rules that are too long to FatalError",
			"converts invalid rules to FatalError",
			"converts overlapping rules to FatalError",
			"preserves unexpected validation errors",
		],
	},
	{
		file: "process-env-populated.test.ts",
		ancestors: ["isProcessEnvPopulated"],
		status: "skip",
		names: [
			"default",
			"future date",
			"old date",
			"switch date",
			"old date, but with flag",
			"old date, with disable flag",
			"future date, but with disable flag",
			"future date, with enable flag",
			"future date without nodejs_compat",
			"date where nodejs_compat is on by default, without the flag",
			"date where nodejs_compat is on by default, opted out with no_nodejs_compat",
			"date where nodejs_compat is on by default, with disable flag",
			"future date, with enable flag but without nodejs_compat",
			"errors with disable and enable flags specified",
		],
	},
	{
		file: "tunnel/tunnel-resolve.test.ts",
		ancestors: ["resolveTunnelId"],
		status: "todo",
		names: ["shows API token guidance for named tunnel permission errors"],
	},
	{
		file: "utils/did-you-mean.test.ts",
		ancestors: ["getSuggestion"],
		status: "skip",
		names: [
			"should suggest the closest match for a typo",
			"should suggest 'deploy' for 'delpoy'",
			"should suggest 'dev' for 'dve'",
			"should return undefined for a completely unrelated input",
			"should be case-insensitive",
			"should return undefined when candidates list is empty",
			"should return exact match when input matches a candidate",
			"should respect custom maxDistance",
			"should work with Set input",
			"should not suggest short commands for unrelated short inputs",
			"should still suggest longer commands for short inputs when close enough",
		],
	},
	{
		file: "utils/did-you-mean.test.ts",
		ancestors: ["logDidYouMean"],
		status: "skip",
		names: [
			"should log a suggestion in a box when a close match exists",
			"should not log anything when no close match exists",
			"should include the full command prefix for subcommands",
			"should preserve trailing args after the typo",
		],
	},
	{
		file: "zones.test.ts",
		ancestors: ["Zones", "getZoneForRoute", "getZoneFromRoute"],
		status: "skip",
		names: [
			"returns the URL host for a SimpleRoute (string)",
			"returns `zone_name` for a ZoneNameRoute (subdomain pattern)",
			"returns `zone_name` for a ZoneNameRoute (apex pattern)",
			"returns `zone_name` for a ZoneNameRoute with the unparseable `*/*` pattern",
			"returns `undefined` when the pattern is unparseable and no `zone_name` is available",
			"falls back to the pattern hostname for a ZoneIdRoute",
			"falls back to the pattern hostname for a CustomDomainRoute",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
