// Generated from cloudflare/workers-sdk@c2bb4c815. Do not rename cases.
import { describe, it } from "vite-plus/test";

const groups = [
	{
		file: "api/startDevWorker/BundleController.test.ts",
		ancestors: ["BundleController", "happy path bundle + watch"],
		status: "skip",
		names: [
			"single ts source file ('bundled')",
			"single ts source file ('unbundled with entrypoint processing')",
			"a watch-mode rebuild failure emits an error event and recovers",
			"multiple ts source files",
			"custom build",
			"does not run the custom build command again for a config it has already been run for",
			"a burst of watched file changes does not run custom builds concurrently",
			"teardown aborts an in-flight watched custom build",
			"a config update after teardown is ignored (watched custom build)",
			"a config update after teardown is ignored (unwatched custom build)",
			"a config update after teardown is ignored (esbuild bundler)",
		],
	},
	{
		file: "api/startDevWorker/BundleController.test.ts",
		ancestors: ["BundleController"],
		status: "skip",
		names: ["module aliasing"],
	},
	{
		file: "api/startDevWorker/BundleController.test.ts",
		ancestors: ["BundleController", "switching"],
		status: "skip",
		names: ["esbuild -> custom builds", "custom builds -> esbuild"],
	},
	{
		file: "api/startDevWorker/BundleController.test.ts",
		ancestors: ["BundleController", "bundling error messages"],
		status: "skip",
		names: [
			"should recommend alias when a non-Node module cannot be resolved",
			"should NOT recommend alias for Node built-in modules",
		],
	},
	{
		file: "assets.test.ts",
		ancestors: [
			"getAssetsOptions",
			"validateDirectoryExistence: true (default — deploy path)",
		],
		status: "skip",
		names: [
			"throws NonExistentAssetsDirError when the --assets directory does not exist",
			"throws with a message referencing the CLI flag when --assets is used",
			"throws with a message referencing the config file when assets.directory is used",
			"throws NonDirectoryAssetsDirError when the path points to a file, not a directory",
		],
	},
	{
		file: "assets.test.ts",
		ancestors: [
			"getAssetsOptions",
			"validateDirectoryExistence: false (getPlatformProxy / unstable_getMiniflareWorkerOptions path)",
		],
		status: "skip",
		names: [
			"does NOT throw when the assets directory does not exist",
			"returns a valid AssetsOptions object even when the directory is absent",
			"still throws NonDirectoryAssetsDirError when the path points to a file",
			"returns correct options when the directory exists and has files",
			"works with assets from config rather than the CLI flag",
			"returns undefined when no assets are configured",
		],
	},
	{
		file: "cli-hotkeys.test.ts",
		ancestors: ["Hot Keys", "callbacks"],
		status: "skip",
		names: [
			"calls handlers when a key is pressed",
			"handles CAPSLOCK",
			"does not fire plain key handler when ctrl or meta is also held with shift",
			"handles meta keys",
			"ignores missing key names",
			"ignores unbound keys",
			"calls handler if any additional key bindings are pressed",
			"surfaces errors in handlers",
		],
	},
	{
		file: "cli-hotkeys.test.ts",
		ancestors: ["Hot Keys", "instructions"],
		status: "skip",
		names: [
			"provides formatted instructions to Wrangler's & Miniflare's logger implementations",
			"provides stacked formatted instructions in narrow views",
			"hides options with disabled property enabled",
		],
	},
	{
		file: "config-cache-wrangler-fallback.test.ts",
		ancestors: ["config cache with .wrangler/cache fallback"],
		status: "skip",
		names: [
			"should use .wrangler/cache when no node_modules exists",
			"should return an empty config if no file exists",
			"should save and retrieve config values using .wrangler/cache fallback",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "DNS errors"],
		status: "todo",
		names: [
			"should return 'DNSError' for ENOTFOUND to api.cloudflare.com",
			"should return 'DNSError' for ENOTFOUND to dash.cloudflare.com",
			"should return 'DNSError' for DNS errors in error cause",
			"should NOT return 'DNSError' for non-Cloudflare hostnames",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "Connection timeout errors"],
		status: "todo",
		names: [
			"should return 'ConnectionTimeout' for api.cloudflare.com timeouts",
			"should return 'ConnectionTimeout' for dash.cloudflare.com timeouts",
			"should return 'ConnectionTimeout' for timeout errors in error cause",
			"should return 'ConnectionTimeout' when Cloudflare URL is in parent message",
			"should NOT return 'ConnectionTimeout' for non-Cloudflare URLs",
			"should NOT return 'ConnectionTimeout' for user's dev server timeouts",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "Permission errors"],
		status: "todo",
		names: [
			"should return 'PermissionError' for EPERM errors",
			"should return 'PermissionError' for EACCES errors",
			"should return 'PermissionError' for EPERM errors without path",
			"should return 'PermissionError' for EPERM errors in error cause",
			"should NOT return 'PermissionError' for non-EPERM/EACCES errors",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "File not found errors"],
		status: "todo",
		names: [
			"should return 'FileNotFoundError' for ENOENT errors with path",
			"should return 'FileNotFoundError' for ENOENT errors without path",
			"should return 'FileNotFoundError' for ENOENT errors in error cause",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "Authentication errors"],
		status: "todo",
		names: [
			"should return 'AuthenticationError' for code 10000 (expired/revoked token)",
			"should return 'AuthenticationError' for code 9106 (invalid token)",
			"should NOT return 'AuthenticationError' for other API errors",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "Fallback behavior"],
		status: "todo",
		names: [
			"should return constructor name for unknown Error types",
			"should return undefined for non-Error values",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["isAuthenticationError"],
		status: "todo",
		names: [
			"should return true for APIError with code 10000",
			"should return true for APIError with code 9106",
			"should return true for ParseError with code 10000",
			"should return false for APIError with a non-auth code",
			"should return false for APIError with no code",
			"should return false for a plain Error",
			"should return false for non-Error values",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "SSL/TLS certificate errors"],
		status: "todo",
		names: [
			"should log a warning for self-signed certificate errors",
			"should log a warning for unable to verify first certificate errors",
			"should log a warning for unable to get local issuer certificate errors",
			"should log a warning when certificate error is in error cause",
			"should log a warning when certificate error is part of a longer message",
			"should not log a warning for unrelated errors",
			"should still log the original error after the warning",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "Cloudflare API connection timeout errors"],
		status: "todo",
		names: [
			"should show user-friendly message for api.cloudflare.com timeouts",
			"should show user-friendly message for dash.cloudflare.com timeouts",
			"should handle timeout errors in error cause",
			"should handle timeout when Cloudflare URL is in parent message",
			"should NOT show timeout message for non-Cloudflare URLs",
			"should NOT show timeout message for user's dev server timeouts",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "Permission errors (EPERM, EACCES)"],
		status: "todo",
		names: [
			"should show user-friendly message for EPERM errors with path",
			"should show user-friendly message for EACCES errors with path",
			"should show error message when path is not available",
			"should handle EPERM errors in error cause",
			"should NOT treat non-EPERM errors as permission errors",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "DNS resolution errors (ENOTFOUND)"],
		status: "todo",
		names: [
			"should show user-friendly message for ENOTFOUND to api.cloudflare.com",
			"should show user-friendly message for ENOTFOUND to dash.cloudflare.com",
			"should handle DNS errors in error cause",
			"should NOT show DNS error for non-Cloudflare hostnames",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "File not found errors (ENOENT)"],
		status: "todo",
		names: [
			"should show user-friendly message for ENOENT errors with path",
			"should show error message when path is not available",
			"should handle ENOENT errors in error cause",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "Cloudflare SDK errors"],
		status: "todo",
		names: [
			"should surface the Retry-After header from a 429 SDK error",
			"should not add a Retry-After note when the header is absent",
		],
	},
	{
		file: "d1/info.test.ts",
		ancestors: ["info"],
		status: "skip",
		names: ["should not display version as valid json when not alpha"],
	},
	{
		file: "deploy/config-remote.test.ts",
		ancestors: ["deploy", "config remote differences"],
		status: "skip",
		names: [
			"should present a diff warning to the user when there are differences between the local config (json/jsonc) and the dash config",
			"should not present a diff warning to the user when there are differences between the local config (json/jsonc) and the dash config in dry-run mode",
			"should present a diff warning to the user when there are differences between the local config (toml) and the dash config",
			"in non-intractive (and non-strict) mode, should present a diff when there are differences between the local config and the dash config, and proceed with the deployment",
		],
	},
	{
		file: "deploy/config-remote.test.ts",
		ancestors: [
			"deploy",
			"config remote differences",
			"with strict mode enabled",
		],
		status: "skip",
		names: [
			"should error if there are remote config difference in non-interactive mode",
			"should error when worker was last deployed from api",
		],
	},
	{
		file: "deploy/config-remote.test.ts",
		ancestors: ["deploy", "config remote differences"],
		status: "todo",
		names: [
			"should warn the user when the deployment would (likely unintentionally) override remote secrets",
			"should handle the remote secrets fetching check for new workers",
			"should not fetch remote secrets in dry-run mode",
			"should abort the deployment when it would (likely unintentionally) override remote secrets in non-interactive strict mode",
		],
	},
	{
		file: "deploy/legacy-assets.test.ts",
		ancestors: ["deploy", "(legacy) asset upload"],
		status: "skip",
		names: [
			"should upload all the files in the directory specified by `config.site.bucket`",
			"should not contain backslash for assets with nested directories",
			"when using a service-worker type, it should add an asset manifest as a text_blob, and bind to a namespace",
			"when using a module worker type, it should add an asset manifest module, and bind to a namespace",
			"should make environment specific kv namespace for assets, even for wrangler environments",
			"should only upload files that are not already in the KV namespace",
			"should only upload files that match the `site-include` arg",
			"should not upload files that match the `site-exclude` arg",
			"should only upload files that match the `site.include` config",
			"should not upload files that match the `site.exclude` config",
			"should use `site-include` arg over `site.include` config",
			"should use `site-exclude` arg over `site.exclude` config",
			"should walk directories except node_modules",
			"should skip hidden files and directories except `.well-known`",
			"should error if the asset is over 25Mb",
			"should batch assets in groups <100 mb",
			"should error if the asset key is over 512 characters",
			"should delete uploaded assets that aren't included anymore",
			"should generate an asset manifest with keys relative to site.bucket",
			"should use the relative path from current working directory to Worker directory when using `--site`",
			"should abort other bucket uploads if one bucket upload fails",
		],
	},
	{
		file: "deploy/legacy-assets.test.ts",
		ancestors: [
			"deploy",
			"(legacy) asset upload",
			"should truncate diff with over 100 assets unless debug log level set",
		],
		status: "skip",
		names: ["default log level", "debug log level"],
	},
	{
		file: "dev/dev-vars.test.ts",
		ancestors: ["getVarsForDev"],
		status: "skip",
		names: [
			"merges config vars with .dev.vars without secrets defined",
			"merges config vars with .dev.vars with secrets defined",
			"warns about missing required secrets",
			"falls back to .env files when CLOUDFLARE_LOAD_DEV_VARS_FROM_DOT_ENV is not false",
			"overrides json-typed config vars",
			"handles undefined loadedSecrets gracefully (no dev var files)",
		],
	},
	{
		file: "flagship.test.ts",
		ancestors: ["flagship", "flags pull"],
		status: "todo",
		names: [
			"writes remote flags and the account tag into the local store",
			"leaves local-only flags untouched and reports them",
			"rejects local access while the project's dev session is running",
			"writes where a dev session reads, under a different binding name",
			"follows pagination and emits JSON on --json",
		],
	},
	{
		file: "flagship.test.ts",
		ancestors: ["flagship", "--local"],
		status: "todo",
		names: [
			"creates, lists, gets and deletes without touching the network",
			"round-trips a rollout through update and evaluate",
			"reports local failures as user errors without falling back",
			"rejects --cursor, which the local store cannot honour",
			"rejects --persist-to without --local",
		],
	},
	{
		file: "match-tag.test.ts",
		ancestors: ["match-tag", "happy path"],
		status: "skip",
		names: ["throws no errors", "ignores errors if no tag match provided"],
	},
	{
		file: "match-tag.test.ts",
		ancestors: ["match-tag", "error cases"],
		status: "skip",
		names: [
			"catches worker not found from API and throws validation error",
			"catches all other API errors and throws proper error",
			"catches all other errors and throws generic error",
			"throws validation error if tag mismatches",
			"throws validation error if account_id mismatches",
		],
	},
	{
		file: "match-tag.test.ts",
		ancestors: ["match-tag", "error cases", "deploy"],
		status: "skip",
		names: [
			"catches worker not found from API and throws validation error",
			"catches all other API errors and throws generic validation error",
			"throws validation error if tag mismatches",
			"throws validation error if account_id mismatches",
			"throws validation error if account_id mismatches w/ custom wrangler.toml path",
		],
	},
	{
		file: "pages/deployment-delete.test.ts",
		ancestors: ["pages deployment delete"],
		status: "todo",
		names: [
			"should delete a deployment with the given ID",
			"should error if no deployment ID is specified",
			"should not delete if confirmation refused",
			"should delete without asking if --force is provided",
			"should support -f alias for --force",
		],
	},
	{
		file: "pages/deployment-delete.test.ts",
		ancestors: ["pages deployment delete"],
		status: "skip",
		names: ["should prefer CLOUDFLARE_ACCOUNT_ID over cached account id"],
	},
	{
		file: "pages/project-validate.test.ts",
		ancestors: ["pages project validate"],
		status: "todo",
		names: [
			"should exit cleanly for a good directory",
			"should error for a large file",
			"should error for a large directory",
			"should succeed with custom fileCountLimit even when exceeding default limit",
			"should error with custom fileCountLimit when exceeding custom limit",
			"should use fileCountLimit from CF_PAGES_UPLOAD_JWT when set",
			"should error when file count exceeds limit from CF_PAGES_UPLOAD_JWT",
		],
	},
	{
		file: "print-bindings.test.ts",
		ancestors: ["printBindings — variable display"],
		status: "skip",
		names: [
			"shows config vars literally",
			"shows --var/--vars as (hidden)",
			"shows .dev.vars / secret file vars as (hidden)",
			"shows json vars literally",
			"handles all three sources together in one table",
			"truncates long config var values",
		],
	},
	{
		file: "print-bindings.test.ts",
		ancestors: ["printBindings — AI Search bindings"],
		status: "skip",
		names: [
			"shows AI Search namespace bindings",
			"shows AI Search instance bindings",
			"renders inherited AI Search namespace bindings as `(inherited)`",
			"shows Agent Memory bindings",
			"renders inherited Agent Memory bindings as `(inherited)`",
		],
	},
	{
		file: "print-bindings.test.ts",
		ancestors: ["printBindings -- Flagship bindings"],
		status: "skip",
		names: [
			"shows Flagship bindings as local by default",
			"shows Flagship bindings as remote when `remote: true` is set",
		],
	},
	{
		file: "print-bindings.test.ts",
		ancestors: ["printBindings -- Artifacts bindings"],
		status: "skip",
		names: ["shows Artifacts bindings"],
	},
	{
		file: "triggers.test.ts",
		ancestors: ["triggers deploy"],
		status: "skip",
		names: ["uses a redirected deploy configuration"],
	},
	{
		file: "triggers.test.ts",
		ancestors: ["triggers deploy", "--zone and --zone-id flags"],
		status: "skip",
		names: [
			"accepts a --zone for the --route patterns",
			"errors when --zone is used without --experimental-route-zones",
			"errors when --zone and --zone-id are used together",
			"errors when --zone-id is passed without --route",
		],
	},
	{
		file: "utils/detect-agent.test.ts",
		ancestors: ["detect-agent", "detectAgent()"],
		status: "skip",
		names: [
			"reports an agent (with id) when detection type is 'agent'",
			"is not an agent when type is 'hybrid', but still reports the id",
			"is not an agent when type is 'interactive'",
			"resolves to a non-agent result when detection throws",
			"detects in a single pass",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "list"],
		status: "todo",
		names: [
			"should output the raw workflows as JSON with --json",
			"should match the table ordering with --json",
			"should output an empty array with --json when there are no workflows",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "describe"],
		status: "todo",
		names: [
			"should output the raw workflow as JSON with --json",
			"should report a null latest_version when there are no versions",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances list", "date filtering"],
		status: "todo",
		names: [
			"sends date_start and date_end as UTC ISO 8601",
			"normalises a date-only value to a UTC timestamp",
			"expands a date-only end bound to cover the whole UTC day",
			"treats the same date for both bounds as that whole day",
			"treats an offset-less time as UTC regardless of host timezone",
			"honours an explicit UTC offset regardless of host timezone",
			"leaves an end bound with an explicit time exact",
			"omits date params when the flags are not provided",
			"combines a date filter with a status filter",
			"errors on an unparseable date",
			"errors on a non-ISO date that Date.parse would accept",
			"errors rather than silently shifting the window for 2026-02-30 (a day beyond the end of the month)",
			"errors rather than silently shifting the window for 2026-02-29 (Feb 29 in a non-leap year)",
			"errors rather than silently shifting the window for 2026-04-31 (April 31)",
			"accepts a real leap day",
			"converts a timestamp with a UTC offset",
			"errors when date-start is after date-end",
			"warns that no instances matched the filters",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances list"],
		status: "todo",
		names: [
			"should output the raw instances as JSON with --json",
			"should still honour --reverse with --json",
			"should output an empty array with --json when there are no instances",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances describe"],
		status: "todo",
		names: [
			"should output the raw instance as JSON with --json",
			"should ignore --truncate-output-limit with --json",
			"should describe a waiting step with dynamic retry delay without crashing",
			"should describe a waiting step with a missing attempt end without crashing",
			"should describe a running instance and steps with duration calculated up to now",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances send-event"],
		status: "todo",
		names: ["should output the API response as JSON with --json"],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances pause"],
		status: "todo",
		names: [
			"should get and pause the bar instance given a name",
			"should output JSON with --json",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances resume"],
		status: "todo",
		names: [
			"should get and resume the bar instance given a name",
			"should output the API response as JSON with --json",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances terminate"],
		status: "todo",
		names: [
			"should get and terminate the bar instance given a name",
			"should pass rollback when requested",
			"should output the API response as JSON with --json",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances delete"],
		status: "todo",
		names: [
			"should delete multiple instances, including cron-generated IDs",
			"should report per-instance errors after logging deletions",
			"should output the raw batch result as JSON with --json",
			"should emit JSON and still fail on a partial delete with --json",
			"should read instance IDs from a JSON file",
			"should require at least one instance ID",
			"should reject an invalid IDs file",
			"should reject more than 100 combined instances",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances restart"],
		status: "todo",
		names: [
			"should get and restart the bar instance given a name",
			"should output the API response as JSON with --json",
			"should restart an instance from a specific step",
			"should require a step name when restart step options are provided",
			"should reject invalid restart step counts",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances terminate-all"],
		status: "todo",
		names: ["should output the raw job status as JSON with --json"],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "trigger"],
		status: "todo",
		names: ["should output the raw created instance as JSON with --json"],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "delete"],
		status: "todo",
		names: ["should output JSON with --json"],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "workflow binding validation"],
		status: "skip",
		names: [
			"should reject workflow binding with name with invalid characters",
			"should reject workflow binding with name with invalid characters",
			"should reject workflow binding with name with invalid characters",
			"should reject workflow binding with name with invalid characters",
			"should accept workflow binding with valid concurrency",
			"should accept workflow binding with empty concurrency object",
			"should accept workflow binding with concurrency.limit at boundary value 1",
			"should reject workflow binding with concurrency.limit of 0",
			"should reject workflow binding with non-integer concurrency.limit",
			"should reject workflow binding with negative concurrency.limit",
			"should reject workflow binding with non-object concurrency",
			"should reject workflow binding with array concurrency",
			"should warn on unexpected fields in workflow binding concurrency",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "local", "workflows list --local"],
		status: "todo",
		names: ["should output a deployed-compatible subset as JSON with --json"],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "local", "workflows describe --local"],
		status: "todo",
		names: ["should output a deployed-compatible subset as JSON with --json"],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "local", "workflows delete --local"],
		status: "todo",
		names: ["should output the local API response as JSON"],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"workflows instances list --local",
		],
		status: "todo",
		names: [
			"should output a deployed-compatible subset as JSON with --json",
			"sends the same normalised date bounds as the remote path",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"workflows instances terminate --local",
		],
		status: "todo",
		names: ["should pass rollback in local dev session"],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"workflows instances delete --local",
		],
		status: "todo",
		names: ["should resolve latest once before local deletion"],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"workflows instances restart --local",
		],
		status: "todo",
		names: [
			"should restart an instance from a specific step in local dev session",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"workflows instances send-event --local",
		],
		status: "todo",
		names: ["should output the local API response as JSON"],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"latest instance resolution --local",
		],
		status: "todo",
		names: ["should output the local API response without a latest notice"],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
