// Generated from cloudflare/workers-sdk@c2bb4c815. Do not rename cases.
import { describe, it } from "vite-plus/test";

const groups = [
	{
		file: "api/startDevWorker/LocalRuntimeController.test.ts",
		ancestors: ["LocalRuntimeController", "getUserWorkerInnerUrlOverrides"],
		status: "skip",
		names: [
			"parses host and port when origin hostname includes a port",
			"clears the local dev port when origin hostname does not include one",
		],
	},
	{
		file: "api/startDevWorker/LocalRuntimeController.test.ts",
		ancestors: ["LocalRuntimeController", "Core"],
		status: "skip",
		names: [
			"dispatches a typed runtimeError for an uncaught Worker exception",
			"should start Miniflare with module worker",
			"should start Miniflare with service worker",
			"should update the running Miniflare instance",
			"should skip stale bundles and only reload once for rapid updates",
			"should start Miniflare with configured compatibility settings",
			"should start inspector on random port and allow debugging",
		],
	},
	{
		file: "api/startDevWorker/LocalRuntimeController.test.ts",
		ancestors: ["LocalRuntimeController", "Bindings"],
		status: "skip",
		names: [
			"should expose basic bindings",
			"should expose WebAssembly module bindings in service workers",
			"should persist cached data",
			"should not persist data when persist is false",
			"should expose KV namespace bindings",
			"should support Secrets Store bindings",
			"should support Hello World bindings",
			"should support Workers Sites bindings",
			"should expose R2 bucket bindings",
			"should expose D1 database bindings",
			"should expose queue producer bindings and consume queue messages",
			"should expose hyperdrive bindings - default",
			"should expose hyperdrive bindings - sslmode 'prefer'",
			"should expose hyperdrive bindings - sslmode 'require' fails",
			"should support Pipeline bindings",
			"should support Images bindings",
			"should support Media bindings",
			"supports Workflow bindings",
			"exposes send email bindings",
			"exposes browser bindings",
			"exposes Workers AI bindings",
			"exposes Analytics Engine bindings",
			"exposes dispatch namespace bindings",
			"exposes mTLS bindings",
		],
	},
	{
		file: "api/startDevWorker/LocalRuntimeController.test.ts",
		ancestors: ["MultiworkerRuntimeController"],
		status: "skip",
		names: ["dispatches a typed runtimeError for an uncaught Worker exception"],
	},
	{
		file: "case-insensitive-env.test.ts",
		ancestors: ["caseInsensitiveEnv"],
		status: "skip",
		names: [
			"resolves get/has/delete case-insensitively",
			"does not leak a stale differently-cased key when a value is overridden",
			"removes the tracked property when deleted under a different casing",
		],
	},
	{
		file: "cloudchamber/delete.test.ts",
		ancestors: ["cloudchamber delete"],
		status: "todo",
		names: [
			"should help",
			"should delete deployment (detects no interactivity)",
			"can't modify delete due to lack of fields",
		],
	},
	{
		file: "containers/config.test.ts",
		ancestors: ["getNormalizedContainerOptions"],
		status: "todo",
		names: [
			"should throw early when a Durable Object-managed container class is missing",
			"should throw early when a Durable Object-managed container uses an external class",
			"should throw early when a Durable Object-managed container uses legacy storage",
			"should let container observability override root observability",
			"should normalize container observability targeting fields",
			"should let root observability override enabled for logs fallback",
		],
	},
	{
		file: "create-worker-upload-form/mime-types.test.ts",
		ancestors: ["moduleTypeMimeType"],
		status: "skip",
		names: [
			"should map esm to application/javascript+module",
			"should map commonjs to application/javascript",
			"should map compiled-wasm to application/wasm",
			"should map buffer to application/octet-stream",
			"should map text to text/plain",
			"should map python to text/x-python",
			"should map python-requirement to text/x-python-requirement",
		],
	},
	{
		file: "create-worker-upload-form/mime-types.test.ts",
		ancestors: ["fromMimeType"],
		status: "skip",
		names: [
			"should reverse-map application/javascript+module to esm",
			"should reverse-map application/javascript to commonjs",
			"should reverse-map application/wasm to compiled-wasm",
			"should reverse-map application/octet-stream to buffer",
			"should throw for unsupported mime types",
		],
	},
	{
		file: "deploy/binding-depends-on-export.test.ts",
		ancestors: ["renderBindingDependsOnExportError"],
		status: "todo",
		names: [
			"surfaces the EWC server message verbatim",
			"trims surrounding whitespace from the server message",
			"falls back to a generic actionable message when the server message is empty",
		],
	},
	{
		file: "deploy/environments.test.ts",
		ancestors: ["deploy", "--dry-run"],
		status: "todo",
		names: ["should not deploy the worker if --dry-run is specified"],
	},
	{
		file: "deploy/environments.test.ts",
		ancestors: ["deploy", "--keep-vars"],
		status: "todo",
		names: [
			"should send keepVars when keep-vars is passed in",
			"should not send keepVars by default",
			"should send keepVars when `keep_vars = true`",
		],
	},
	{
		file: "deploy/environments.test.ts",
		ancestors: ["deploy", "--dispatch-namespace"],
		status: "todo",
		names: ["should upload to dispatch namespace"],
	},
	{
		file: "deploy/environments.test.ts",
		ancestors: ["deploy", "[observability]"],
		status: "todo",
		names: [
			"should allow uploading workers with observability",
			"should allow uploading workers with nested observability logs setting",
			"should allow uploading workers with nested observability traces setting",
			"should disable observability if not explicitly defined",
		],
	},
	{
		file: "deploy/environments.test.ts",
		ancestors: ["deploy", "compliance region support"],
		status: "todo",
		names: [
			"should upload to the public region by default",
			"should upload to the FedRAMP High region if set in config",
			"should upload to the FedRAMP High region if set in an env var",
			"should error if the region is set in both env var and configured, and they conflict",
			"should not error if the region is set in both env var and configured, and they are the same",
		],
	},
	{
		file: "deploy/environments.test.ts",
		ancestors: ["deploy", "Service and environment tagging"],
		status: "skip",
		names: [
			"has environments, no existing tags, top-level env",
			"has environments, no existing tags, named env",
			"has environments, missing tags, top-level env",
			"has environments, missing tags, named env",
			"has environments, missing environment tag, named env",
			"has environments, stale service tag, top-level env",
			"has environments, stale service tag, named env",
			"has environments, stale environment tag, top-level env",
			"has environments, stale environment tag, named env",
			"has environments, has expected tags, top-level env",
			"has environments, has expected tags, named env",
			"no environments",
			"no top-level name",
			"displays warning when error updating tags",
			"environments with redirected config",
		],
	},
	{
		file: "deploy/environments.test.ts",
		ancestors: ["deploy", "multi-env warning"],
		status: "skip",
		names: [
			"should warn if the wrangler config contains environments but none was specified in the command",
			"should not warn if the wrangler config contains environments and one was specified in the command",
			"should not warn if the wrangler config doesn't contain environments and none was specified in the command",
			'should not warn if --env="" is passed to explicitly target the top-level environment',
			"should not warn if the wrangler config contains environments and CLOUDFLARE_ENV is set",
			"should not warn if using a redirected wrangler config with a baked-in target environment",
			"should not warn if using a redirected wrangler config targeting the top-level environment (no targetEnvironment set)",
		],
	},
	{
		file: "deploy/environments.test.ts",
		ancestors: ["deploy", "--tag and --message"],
		status: "todo",
		names: [
			"should send tag and message annotations via the new versions API",
			"should send tag and message annotations via the legacy PUT API",
			"should send only --tag without --message",
			"should send only --message without --tag",
			"should not set annotations when neither --tag nor --message is provided",
		],
	},
	{
		file: "deploy/workers-dev.test.ts",
		ancestors: ["deploy", "workers_dev defaults"],
		status: "todo",
		names: [
			"'workers_dev=undefined, routes empty'",
			"'workers_dev=undefined, routes populat…'",
			"'workers_dev override, routes empty'",
			"'workers_dev override, routes populated'",
			"'preview_urls=undefined, workers_dev=d…'",
			"'preview_urls=undefined, workers_dev=d…'",
			"'preview_urls=undefined, workers_dev=e…'",
			"'preview_urls override'",
		],
	},
	{
		file: "deploy/workers-dev.test.ts",
		ancestors: ["deploy", "workers_dev setting"],
		status: "todo",
		names: [
			"should include Cloudflare-Workers-Script-Api-Date header",
			"should deploy to a workers.dev domain if workers_dev is undefined",
			"should deploy successfully if the /subdomain POST request is flaky",
			"should deploy to the workers.dev domain if workers_dev is `true`",
			"should not try to enable the workers.dev domain if it has been enabled before and previews are in sync",
			"should sync the workers.dev domain if it has been enabled before but previews should be enabled",
			"should sync the workers.dev domain if it has been enabled before but previews should be enabled",
			"should disable the workers.dev domain if workers_dev is `false`",
			"should not try to disable the workers.dev domain if it is not already available and previews are in sync",
			"should sync the workers.dev domain if it is not available but previews should be enabled",
			"should sync the workers.dev domain if it is not available but previews should be disabled",
			"should use the command line --compatibility-date and --compatibility-flags if they are specified",
			"should enable the workers.dev domain if workers_dev is undefined and subdomain is not already available",
			"should enable the workers.dev domain if workers_dev is true and subdomain is not already available",
			"should get the workers.dev URL from the Worker resource",
			"should fail to deploy to the workers.dev domain if email is unverified",
			"should offer to create a new workers.dev subdomain when publishing to workers_dev without one",
			"should not deploy to workers.dev if there are any routes defined",
			"can deploy to both workers.dev and routes if both defined",
		],
	},
	{
		file: "deploy/workers-dev.test.ts",
		ancestors: ["deploy", "workers_dev setting"],
		status: "skip",
		names: [
			"should disable the workers.dev domain if workers_dev is undefined but overwritten to `false` in environment",
			"should disable the workers.dev domain if workers_dev is `true` but overwritten to `false` in environment",
			"should deploy to a workers.dev domain if workers_dev is undefined but overwritten to `true` in environment",
			"should deploy to a workers.dev domain if workers_dev is `false` but overwritten to `true` in environment",
			"should use the global compatibility_date and compatibility_flags if they are not overwritten by the environment",
			"should use the environment specific compatibility_date and compatibility_flags",
			"should error if a compatibility_date is not available in wrangler.toml or cli args",
			"should error if a compatibility_date is missing and suggest the correct date",
			"should not deploy to workers.dev if there are any routes defined (environments)",
			"should not deploy to workers.dev if there are any routes defined (only in environments)",
			"can deploy to both workers.dev and routes if both defined (environments: 1)",
			"can deploy to both workers.dev and routes if both defined (environments: 2)",
			"will deploy only to routes when workers_dev is false (environments 1) ",
			"will deploy only to routes when workers_dev is false (environments 2) ",
			"should warn the user if workers_dev default is different from remote",
			"should warn the user if preview_urls default is different from remote",
		],
	},
	{
		file: "deploy/workers-dev.test.ts",
		ancestors: [
			"deploy",
			"workers_dev setting",
			"brand-new account / first deploy (no workers.dev subdomain yet)",
		],
		status: "todo",
		names: [
			"registers a workers.dev subdomain before uploading a new Worker",
			"fails when workers.dev subdomain registration is unauthorized",
			"fails before uploading when the user declines to register a subdomain",
			"uploads a new Worker without prompting when the account already has a subdomain",
			"uploads a new Worker when granular auth prevents the account subdomain lookup",
			"does not check for a workers.dev subdomain when a new Worker only targets routes",
			"does not check for a workers.dev subdomain when a new Worker sets workers_dev = false",
		],
	},
	{
		file: "deploy/workers-dev.test.ts",
		ancestors: [
			"deploy",
			"workers_dev setting",
			"brand-new account / first deploy (no workers.dev subdomain yet)",
		],
		status: "skip",
		names: ["uses the project name without prompting when run by an agent"],
	},
	{
		file: "deploy/workers-dev.test.ts",
		ancestors: ["deploy", "workers_dev mixed state warnings"],
		status: "skip",
		names: ["should not warn when config is the same as remote"],
	},
	{
		file: "deploy/workers-dev.test.ts",
		ancestors: ["deploy", "workers_dev mixed state warnings"],
		status: "todo",
		names: [
			"should not warn when workers_dev=false,preview_urls=false",
			"should not warn when workers_dev=true,preview_urls=true",
			"should warn when workers_dev=false,preview_urls=true",
			"should use the Worker preview URL suffix in mixed-state warnings",
			"should warn when workers_dev=true,preview_urls=false",
		],
	},
	{
		file: "errors.test.ts",
		ancestors: ["errors", "UserError"],
		status: "skip",
		names: [
			"takes a custom telemetry message",
			"can set telemetryMessage to equal the main message",
		],
	},
	{
		file: "errors.test.ts",
		ancestors: ["errors", "DeprecationError"],
		status: "skip",
		names: [
			"takes a custom telemetry message",
			"can set telemetryMessage to equal the main message",
		],
	},
	{
		file: "errors.test.ts",
		ancestors: ["errors", "FatalError"],
		status: "skip",
		names: [
			"takes a custom telemetry message",
			"can set telemetryMessage to equal the main message",
		],
	},
	{
		file: "errors.test.ts",
		ancestors: ["errors", "CommandLineArgsError"],
		status: "skip",
		names: [
			"takes a custom telemetry message",
			"can set telemetryMessage to equal the main message",
		],
	},
	{
		file: "errors.test.ts",
		ancestors: ["errors", "JsonFriendlyFatalError"],
		status: "skip",
		names: [
			"takes a custom telemetry message",
			"can set telemetryMessage to equal the main message",
		],
	},
	{
		file: "errors.test.ts",
		ancestors: ["errors", "MissingConfigError"],
		status: "skip",
		names: ["just sets the telemetry message as the main message"],
	},
	{
		file: "errors.test.ts",
		ancestors: ["errors", "ParseError"],
		status: "skip",
		names: [
			"takes a custom telemetry message",
			"can set telemetryMessage to equal the main message",
		],
	},
	{
		file: "errors.test.ts",
		ancestors: ["errors", "APIError"],
		status: "skip",
		names: [
			"takes a custom telemetry message",
			"can set telemetryMessage to equal the main message",
		],
	},
	{
		file: "init.test.ts",
		ancestors: ["init", "`wrangler init` now delegates to c3 by default"],
		status: "skip",
		names: [
			"shows that it delegates to C3",
			"if `-y` is used, delegate to c3 with --wrangler-defaults",
			"if telemetry is disabled in wrangler, then disable for c3 too",
		],
	},
	{
		file: "init.test.ts",
		ancestors: [
			"init",
			"`wrangler init` now delegates to c3 by default",
			"with yarn package manager",
		],
		status: "skip",
		names: [
			"uses C3 command without version specifier for yarn",
			"uses C3 command without version specifier when using --from-dash with yarn",
		],
	},
	{
		file: "init.test.ts",
		ancestors: [
			"init",
			"`wrangler init` now delegates to c3 by default",
			"with custom C3 command",
		],
		status: "skip",
		names: [
			"shows that it delegates to C3",
			"if `-y` is used, delegate to c3 with --wrangler-defaults",
		],
	},
	{
		file: "init.test.ts",
		ancestors: [
			"init",
			"`wrangler init` now delegates to c3 by default",
			"when C3 fails",
		],
		status: "skip",
		names: [
			"reports a stable message that names the command and carries the output on the cause",
			"reports a process terminated by a signal as a failure",
		],
	},
	{
		file: "init.test.ts",
		ancestors: ["init", "--from-dash --no-delegate-c3"],
		status: "skip",
		names: [
			"delegates to C3 --type pre-existing",
			"should download routes + custom domains + workers dev",
			"should fail on init --from-dash on non-existent worker name",
			"should download source script from dashboard w/ out positional <name>",
			"should download source script from dashboard as plain JavaScript",
			"should include user limits",
			"should ignore usage_model = bundled",
			"should ignore usage_model = unbound",
			"should ignore usage_model = standard",
			"should use fallback compatibility date if none is upstream",
			"should throw an error to retry if a request fails",
			"should not include migrations in config file when none are necessary",
			"should not continue if no worker name is provided",
			"should download multi-module source scripts from dashboard",
		],
	},
	{
		file: "output.test.ts",
		ancestors: ["writeOutput()"],
		status: "skip",
		names: [
			"should do nothing with no env vars set",
			"should write to the file given by WRANGLER_OUTPUT_FILE_PATH",
			"should write to the file given by WRANGLER_OUTPUT_FILE_PATH, ignoring WRANGLER_OUTPUT_FILE_DIRECTORY",
			"should write multiple entries to the file given by WRANGLER_OUTPUT_FILE_PATH",
			"should write to a random file in WRANGLER_OUTPUT_FILE_DIRECTORY",
			"should write multiple entries to the same random file in WRANGLER_OUTPUT_FILE_DIRECTORY",
			"should write an alias and environment for pages-deploy-detailed outputs",
			"should write preview outputs with separate preview and deployment URLs",
			"should write an error log when a handler throws an error",
			"should redact event codes from session output with a separate argument",
			"should redact event codes from session output with equals syntax",
			"should redact event codes from session output with a camel-case separate argument",
			"should redact event codes from session output with camel-case equals syntax",
			"should include retry_after_ms in the error log when the failure carries a Retry-After duration",
		],
	},
	{
		file: "pages/pages-download-config.test.ts",
		ancestors: ["pages download config"],
		status: "skip",
		names: [
			"should download full config correctly",
			"should generate preview override if preview has limits and production does not",
			"should not duplicate inheritable properties if they're equal",
			"should prefer CLOUDFLARE_ACCOUNT_ID over cached account id",
			"should fail if not given a project name",
			"should fail if project does not exist",
		],
	},
	{
		file: "pages/pages-download-config.test.ts",
		ancestors: ["pages download config", "overwrite existing file"],
		status: "skip",
		names: [
			"should overwrite existing file w/ --force",
			"should not overwrite existing file w/o --force (non-interactive)",
			"should overwrite existing file w/ prompt",
			"should not overwrite existing file w/ prompt",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines list"],
		status: "todo",
		names: ["should surface failed pipelines in the list"],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines get"],
		status: "todo",
		names: [
			"highlights failure reason for a failed pipeline",
			"resolves pipeline by name",
			"resolves pipeline by name across multiple pages",
			"resolves pipeline by name when identifier looks like a 32-char hex string",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines delete"],
		status: "todo",
		names: ["deletes pipeline by name"],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines streams get"],
		status: "todo",
		names: [
			"resolves stream by name",
			"resolves stream by name when API returns error code 1016",
			"resolves stream by name across multiple pages",
			"resolves stream by name when identifier looks like a 32-char hex string",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines streams delete"],
		status: "todo",
		names: ["deletes stream by name"],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines sinks create"],
		status: "todo",
		names: [
			"should create R2 JSON sink with gzip compression",
			"should create uncompressed JSON sink when compression is omitted",
			"should create JSON sink with explicit uncompressed output",
			"should reject unsupported JSON compression",
			"should reject row group size for JSON sinks",
			"should error when r2-data-catalog has interval below minimum",
			"should allow r2 sinks with interval below 60 seconds",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines sinks get"],
		status: "todo",
		names: [
			"resolves sink by name",
			"resolves sink by name when API returns error code 1015",
			"resolves sink by name across multiple pages",
			"resolves sink by name when identifier looks like a 32-char hex string",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines sinks delete"],
		status: "todo",
		names: ["deletes sink by name"],
	},
	{
		file: "register-yargs-command-skills.test.ts",
		ancestors: ["register-yargs-command skills integration"],
		status: "skip",
		names: [
			"does not check skills for commands without suggestSkillsAfterHandler",
			"calls runSkillsInstallFlow with force: true and command when --install-skills is passed",
			"calls runSkillsUpdateFlow after commands with suggestSkillsAfterHandler: true",
			"calls runSkillsUpdateFlow after `wrangler whoami` (non-JSON)",
			"command in skills install event contains only the command name, not positional args or flags",
			"does not check skills after `wrangler whoami --json`",
			"does not fail the command when runSkillsUpdateFlow throws",
			"does not call runSkillsUpdateFlow when WRANGLER_NO_SKILLS_UPDATE_PROMPTS env var is set",
		],
	},
	{
		file: "update-config-file.test.ts",
		ancestors: ["createdResourceConfig()"],
		status: "skip",
		names: [
			"non interactive: no prompts and no file update",
			"interactive: no file update after answering no",
			"interactive: file update after answering yes",
			"interactive: replaces an existing binding with the same name",
			"non interactive: replaces an existing binding with the same name",
			"interactive: file update in env after answering yes",
			"interactive: file update after answering yes-but",
			"interactive: no prompts & no file update for toml",
			"interactive: no prompts & no file update for no config file",
			"logs correct binding type",
		],
	},
	{
		file: "update-config-file.test.ts",
		ancestors: ["createdResourceConfig()", "defaults"],
		status: "skip",
		names: ["no prompts if all defaults provided"],
	},
	{
		file: "utils/retry.test.ts",
		ancestors: ["retryOnAPIFailure"],
		status: "skip",
		names: [
			"should retry 5xx errors and succeed if the 3rd try succeeds",
			"should throw 5xx error after all retries fail",
			"should retry 429 errors and succeed if the 3rd try succeeds",
			"should wait for the duration in retryAfterMs instead of the computed backoff",
			"should honour Retry-After on 5xx errors too, instead of the computed backoff",
			"should fail fast without retrying when Retry-After exceeds the cap",
			"should fail fast on a 5xx whose Retry-After exceeds the cap, rather than exhausting retries",
			"should log a message when waiting on a Retry-After header",
			"should not retry non-5xx errors",
			"should retry TypeError",
			"should not retry other errors",
			"should cancel retry backoff when abort signal fires",
			"should propagate abort error from action without retrying",
			"should retry TimeoutError from AbortSignal.timeout()",
			"should retry custom APIError implementation with non-5xx error",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
