// Generated from cloudflare/workers-sdk@c2bb4c815. Do not rename cases.
import { describe, it } from "vite-plus/test";

const groups = [
	{
		file: "ai.test.ts",
		ancestors: ["ai help"],
		status: "todo",
		names: [
			"should show models help",
			"should show schema help without model list flags",
		],
	},
	{
		file: "ai.test.ts",
		ancestors: ["ai commands"],
		status: "todo",
		names: [
			"should handle legacy model list",
			"should query model list with filters",
			"should handle model schema",
		],
	},
	{
		file: "api/startDevWorker/utils.test.ts",
		ancestors: ["isSameUserWorkerOrigin"],
		status: "skip",
		names: [
			"matches same-origin requests regardless of path or query",
			"does not match when the port differs",
			"does not match when the hostname differs",
			"does not match when the protocol differs",
			"does not match when there is no proxyData (UserWorker torn down)",
		],
	},
	{
		file: "api/startDevWorker/utils.test.ts",
		ancestors: ["convertConfigBindingsToStartWorkerBindings"],
		status: "skip",
		names: [
			"converts config bindings into startWorker bindings",
			"prioritizes preview values compared to their standard counterparts",
			"converts programmatic dev stream bindings",
		],
	},
	{
		file: "api/startDevWorker/utils.test.ts",
		ancestors: ["rewriteUrlInHeaderValue"],
		status: "skip",
		names: [
			"rewrites a URL whose host is exactly the proxied host",
			"does not corrupt a subdomain of the proxied host",
			"does not corrupt a host that merely contains the proxied host as a substring",
			"leaves an unrelated host untouched",
			"does not append a trailing slash to a bare origin (e.g. an Origin header)",
			"preserves host-like substrings inside the query string",
			"maps the local dev address back to the proxied host (request path)",
		],
	},
	{
		file: "cfetch-utils.test.ts",
		ancestors: ["throwFetchError"],
		status: "todo",
		names: [
			"should include api errors, messages and documentation_url in error",
			"nested",
			"should include api errors without messages",
		],
	},
	{
		file: "cloudchamber/list.test.ts",
		ancestors: ["cloudchamber list"],
		status: "todo",
		names: ["should help", "should list deployments (json)"],
	},
	{
		file: "containers/registries.test.ts",
		ancestors: ["containers registries configure", "FedRAMP compliance region"],
		status: "todo",
		names: ["should configure AWS ECR registry with interactive prompts"],
	},
	{
		file: "containers/registries.test.ts",
		ancestors: [
			"containers registries configure",
			"FedRAMP compliance region",
			"non-interactive",
		],
		status: "todo",
		names: ["should accept the secret from piped input"],
	},
	{
		file: "containers/registries.test.ts",
		ancestors: [
			"containers registries configure",
			"AWS ECR registry configuration",
		],
		status: "todo",
		names: ["should configure AWS ECR registry with interactive prompts"],
	},
	{
		file: "containers/registries.test.ts",
		ancestors: [
			"containers registries configure",
			"AWS ECR registry configuration",
			"non-interactive",
		],
		status: "todo",
		names: [
			"should accept the secret from piped input",
			"should reuse existing secret without requiring a value (no stdin)",
		],
	},
	{
		file: "containers/registries.test.ts",
		ancestors: [
			"containers registries configure",
			"DockerHub registry configuration",
			"non-interactive",
		],
		status: "todo",
		names: [
			"should accept the secret from piped input",
			"should reuse existing secret without requiring a value (no stdin)",
		],
	},
	{
		file: "containers/registries.test.ts",
		ancestors: ["containers registries list"],
		status: "todo",
		names: ["should output valid JSON when --json flag is used"],
	},
	{
		file: "containers/registries.test.ts",
		ancestors: ["containers registries credentials"],
		status: "todo",
		names: ["should output valid JSON when --json flag is used"],
	},
	{
		file: "d1/d1.test.ts",
		ancestors: ["d1"],
		status: "todo",
		names: [
			"should show help when no argument is passed",
			"should show help when an invalid argument is passed",
			"should show help when the time travel command is passed",
		],
	},
	{
		file: "deploy/check-workflow-conflicts.test.ts",
		ancestors: ["checkWorkflowConflicts"],
		status: "todo",
		names: [
			"should return { hasConflicts: false } when there are no workflows in config",
			"should return { hasConflicts: false } when workflows is undefined",
			"should return { hasConflicts: false } when workflow does not exist yet",
			"should return { hasConflicts: false } when workflow belongs to same worker",
			"should detect conflict when workflow belongs to different worker",
			"should detect multiple conflicts",
			"should skip workflows that bind to another script",
			"should only flag workflows being deployed by this script",
			"should generate correct message for single conflict",
		],
	},
	{
		file: "deploy/get-remote-config-diff.test.ts",
		ancestors: ["getRemoteConfigsDiff"],
		status: "skip",
		names: [
			"should handle a very simple diffing scenario (no diffs, random order)",
			"should handle a very simple diffing scenario where there is only an addition to an array (specifically in `kv_namespaces`)",
			"should handle a very simple diffing scenario (some diffs, random order)",
			"should handle a diffing scenario with only additions",
			"should handle a diffing scenario with only deletions",
			"should handle a diffing scenario with modifications and removals",
			"should ignore local-only configs such as `dev` and `build`",
			"should ignore the `remote` field of bindings during the diffing process (since remote bindings are a local-only concept)",
			"should ignore all fields from an assets binding besides the binding name (since remotely only that information is stored)",
			"should not show spurious diffs when binding arrays have same elements in different order",
		],
	},
	{
		file: "deploy/get-remote-config-diff.test.ts",
		ancestors: ["getRemoteConfigsDiff", "observability"],
		status: "skip",
		names: [
			"shouldn't present any diff when the local config is just { enabled: true } and the remote observability is enabled with its default values",
			"should treat a remote undefined equal to a remote { enabled: false }",
			"should treat a remote undefined equal to a remote { enabled: false, logs: { enabled: false } }",
			"should correctly show the diff of boolean when the remote is undefined and the local is { enabled: true }",
			"should correctly show the diff of boolean when the remote is undefined and the local is { logs: { enabled: false } }",
			"should correctly not show head_sampling_rate being added remotely",
			"should correctly not show logs.invocation_logs being added remotely",
		],
	},
	{
		file: "dev.test.ts",
		ancestors: ["wrangler dev", "Local Explorer agent hint"],
		status: "skip",
		names: [
			"asks startDev to print the hint for headless agent sessions",
			"does not ask startDev to print the hint for interactive agent sessions",
			"does not ask startDev to print the hint for non-agent sessions",
		],
	},
	{
		file: "dev.test.ts",
		ancestors: ["wrangler dev", "durable_objects", "declarative `exports`"],
		status: "skip",
		names: [
			"starts dev when `exports` is set",
			"resolves a container referenced from a durable object export",
		],
	},
	{
		file: "dev.test.ts",
		ancestors: ["wrangler dev", "containers"],
		status: "skip",
		names: ["should warn in remote mode with named-image containers"],
	},
	{
		file: "dev.test.ts",
		ancestors: ["wrangler dev", "tunnel"],
		status: "skip",
		names: [
			"should pass --tunnel flag through to dev config",
			"should pass --tunnel-name with --tunnel through to dev config",
			"should allow --tunnel-name without enabling tunnel",
			"should default tunnel to undefined when not specified",
			"should error when --tunnel and --remote are both specified",
		],
	},
	{
		file: "fetch-graphql-result.test.ts",
		ancestors: ["fetchGraphqlResult"],
		status: "skip",
		names: [
			"should make a request against the graphql endpoint by default",
			"should accept a request with no init, but return no data",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger"],
		status: "skip",
		names: ["should add colored markers to error and warning messages"],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger", "loggerLevel=debug"],
		status: "skip",
		names: [
			"should render messages that are at or above the log level set in the logger",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger", "loggerLevel=log"],
		status: "skip",
		names: [
			"should render messages that are at or above the log level set in the logger",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger", "loggerLevel=warn"],
		status: "skip",
		names: [
			"should render messages that are at or above the log level set in the logger",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger", "loggerLevel=error"],
		status: "skip",
		names: [
			"should render messages that are at or above the log level set in the logger",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger", "loggerLevelFromEnvVar=error"],
		status: "skip",
		names: [
			"should render messages that are at or above the log level set in the env var",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger", "loggerLevelFromEnvVar case-insensitive"],
		status: "skip",
		names: [
			"should render messages that are at or above the log level set in the env var",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: [
			"logger",
			"loggerLevelFromEnvVar falls back to log on invalid level",
		],
		status: "skip",
		names: [
			"should render messages that are at or above the log level set in the env var",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger", "once"],
		status: "skip",
		names: [
			"should only log the same message once",
			"should log once per log level",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger", "@cloudflare/cli-shared-helpers logRaw"],
		status: "skip",
		names: [
			"should output at log level",
			"should not output when log level is set to warn",
			"should not output when log level is set to error",
			"should not output when log level is set to none",
			"should output when log level is set to debug",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["logger", "@cloudflare/cli-shared-helpers error"],
		status: "skip",
		names: [
			"should output at error level",
			"should not output when log level is set to none",
			"should output when log level is set to warn",
			"should output when log level is set to log",
			"should output when log level is set to debug",
		],
	},
	{
		file: "logger.test.ts",
		ancestors: ["shouldLogToDisk"],
		status: "skip",
		names: [
			"should return false in test environments by default",
			"should return true outside test environments when WRANGLER_WRITE_LOGS is not set",
			"should return false when WRANGLER_WRITE_LOGS=false",
			"should be case-insensitive (WRANGLER_WRITE_LOGS=FALSE)",
			"should return false when WRANGLER_WRITE_LOGS=0",
			"should return true for any other value",
		],
	},
	{
		file: "pages/delegation-commands.test.ts",
		ancestors: ["Pages-to-Workers command delegation"],
		status: "skip",
		names: [
			"delegates a new Pages deploy when the account already has another Pages project",
			"delegates a new Pages project create when the account already has another Pages project",
		],
	},
	{
		file: "pages/project-list.test.ts",
		ancestors: ["pages project list"],
		status: "todo",
		names: [
			"should make request to list projects",
			"should make multiple requests for paginated results",
			"should error before making a request when CLOUDFLARE_ACCOUNT_ID contains characters that are invalid in a URL",
		],
	},
	{
		file: "pages/project-list.test.ts",
		ancestors: ["pages project list"],
		status: "skip",
		names: [
			"should override cached accountId with CLOUDFLARE_ACCOUNT_ID environmental variable if provided",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "resolveWorkerName"],
		status: "todo",
		names: [
			"should prefer WRANGLER_CI_OVERRIDE_NAME over arguments and config",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "formatNoActivePreviewUrlsMessage"],
		status: "todo",
		names: [
			"shows exact configuration for 'a new Preview-only custom domain'",
			"shows exact configuration for 'an existing implicitly enabled produc…'",
			"shows exact configuration for 'an existing explicitly enabled produc…'",
			"shows exact configuration for 'an existing multi-route config with a…'",
			"shows exact configuration for 'an existing singular non-custom-domai…'",
			"preserves a singular non-custom-domain route in TOML guidance",
			"scopes URL guidance to the selected environment in '/test/wrangler.json'",
			"scopes URL guidance to the selected environment in '/test/wrangler.toml'",
			"scopes URL guidance to the selected environment in '/test/generated/wrangler.json'",
			"does not ask the user to commit a change when both settings are already present",
			"tells the user to update, not add, an explicit preview_urls: false",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "getBranchName"],
		status: "skip",
		names: [
			"should prefer the Workers CI branch env var",
			"should use the GitHub Actions branch env vars",
			"should use the GitLab branch env var",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "previewContainerAppName"],
		status: "skip",
		names: [
			"should join worker name, preview slug, and class name with underscores",
			"should normalise 'a worker name that starts with a digit' and mark it with a digest",
			"should normalise 'consecutive dashes in a worker name' and mark it with a digest",
			"should normalise 'a character that no application name …' and mark it with a digest",
			"should keep apart worker names that normalise onto one another",
			"should cap the name at the length the API allows",
			"should keep apart worker names that differ only past that length",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "getRepositoryUrl"],
		status: "skip",
		names: [
			"should use GitHub Actions repository env vars",
			"should use GitHub Enterprise server URL",
			"should use GitLab project URL",
			"should use and normalize git remote origin URL when in CI",
			"should not shell out to the local git remote outside CI",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "getPullRequestMetadata"],
		status: "skip",
		names: [
			"should use direct pull request URL env vars",
			"should use GitHub event pull request metadata",
			"should not fail when the GitHub event pull request has no title",
			"should not recover a title from the GITHUB_REF fallback",
			"should use GitLab merge request metadata",
			"should treat a blank title the same as a missing one",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "getCommitSha"],
		status: "skip",
		names: [
			"should use the GitHub Actions commit SHA",
			"should use the GitLab CI commit SHA",
			"should use the CircleCI commit SHA",
			"should use the generic COMMIT_SHA fallback",
			"should prefer GitHub Actions over other providers",
			"should return undefined when no commit SHA env var is set",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "extractConfigBindings"],
		status: "skip",
		names: [
			"should extract vars as plain_text bindings",
			"should extract non-string vars as json bindings so the runtime preserves the native shape",
			"should extract kv_namespaces",
			"should extract d1_databases",
			"should extract r2_buckets",
			"should extract services",
			"should extract durable_objects bindings",
			"should return empty object when no previews block",
			"should extract multiple binding types",
			"should extract ai_search and ai_search_namespaces",
			"should extract additional supported preview binding types",
			"should pass cross_account_grant on service bindings",
			"should fold unsafe.bindings into the previews env",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"configuration onboarding",
		],
		status: "todo",
		names: [
			"warns about named environments in 'wrangler.json' when --env is omitted",
			"warns about named environments in 'wrangler.toml' when --env is omitted",
			"preserves environment diagnostics when --env is supplied",
			"does not emit human named-environment guidance in JSON mode",
			"onboards a rich Preview Base into 'wrangler.toml' and deploys it",
			"onboards a rich Preview Base into 'wrangler.json' and deploys it",
			"onboards a rich Preview Base into 'wrangler.jsonc' and deploys it",
			"shows and writes an environment-scoped Preview Base proposal",
			"onboards sparse Preview Base settings into 'wrangler.json'",
			"onboards sparse Preview Base settings into 'wrangler.jsonc'",
			"onboards Preview Base 'empty limits'",
			"onboards Preview Base 'empty tail consumers'",
			"falls back to guidance for commented TOML",
			"suggests an empty previews block for an empty Worker",
			"keeps an explicit empty previews block without prompting",
			"rejects generated placeholders before onboarding or deployment",
			"rejects generated placeholder keys before deployment",
			"allows Preview values that only contain the placeholder text",
			"does not prompt, log, or mutate config for JSON onboarding",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "preview command"],
		status: "todo",
		names: [
			"should create a new preview with defaults applied",
			"requires Preview-safe replacements for production bindings",
			"returns the suggested Preview configuration as JSON",
			"uses blocking lead-in with generated Preview configuration for 'Durable Objects'",
			"emits one combined unsupported-settings warning",
			"should upload secrets from a JSON --secrets-file as secret_text bindings",
			"should fail on a bad --secrets-file before creating the preview or uploading assets",
			"should upload --var values as plain_text bindings, overriding config vars but not secrets",
			"should redact secret values from --json output even if the API echoes them back",
			"should upload secrets from a .env format --secrets-file as secret_text bindings",
			"should output preview and deployment JSON for wrangler-action when the Preview API omits the Worker name",
			"should show existing preview status for existing preview",
			"handles URL guidance when 'both URL arrays are empty'",
			"handles URL guidance when 'the Preview URL array is active'",
			"handles URL guidance when 'the deployment URL array is active'",
			"handles custom-domain Preview URL guidance when 'workers.dev URLs are active but custo…'",
			"handles custom-domain Preview URL guidance when 'the Preview URL array has a custom-do…'",
			"handles custom-domain Preview URL guidance when 'the deployment URL array has a custom…'",
			"handles custom-domain Preview URL guidance when 'a configured IDN custom domain matche…'",
			"should use the URL-encoded preview name as the Preview identifier in path params",
			"should work without previews_base_config",
			"should show compact success output when observability is configured",
			"should include previews tail_consumers in the preview resource request",
			"should include version settings in the deployment request",
			"should pass ignore_base_config query param when creating a Preview with --ignore-base-config",
			"should include assets payload for deployment when assets are configured",
			"should include the assets binding in env using the configured binding name",
			"should include source maps in deployment modules when upload_source_maps is enabled",
			"should use previews durable_objects for export validation",
			"should use previews workflows for export validation",
			"should include migrations in the deployment request",
			"should handle first preview deployment when latest deployment is missing",
			"should include deployment annotations from metadata and args",
			"should disable placement when previews placement is off",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
		],
		status: "todo",
		names: [
			"creates the parent Worker with Preview URLs enabled, then creates the Preview",
			"aborts without creating the parent Worker when the user declines",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
			"'defaults Preview URLs to workers.dev'",
		],
		status: "skip",
		names: ["resolves subdomain settings without applying production triggers"],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
			"'defaults Preview URLs to explicit wor…'",
		],
		status: "skip",
		names: ["resolves subdomain settings without applying production triggers"],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
			"'respects enabled Preview URLs'",
		],
		status: "skip",
		names: ["resolves subdomain settings without applying production triggers"],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
			"'respects disabled Preview URLs'",
		],
		status: "skip",
		names: ["resolves subdomain settings without applying production triggers"],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
		],
		status: "skip",
		names: ["keeps JSON output parseable when creating the parent Worker"],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "preview command"],
		status: "skip",
		names: [
			"uses blocking lead-in with generated Preview configuration for 'Containers'",
			"should not warn about top-level bindings when they are present in local previews config",
			"should use flagship bindings from local previews config",
			"should use ai_search bindings from local previews config",
			"should not warn about top-level bindings that were supplied via --var or --secrets-file",
			"should not warn about inheritable top-level bindings missing from previews",
			"should build correctly when using a redirected config",
			"should include dist/server chunks when using a vite no-bundle redirected config",
			"should include containers in deployment metadata and create a preview-scoped container application",
			"should name applications from the resolved worker name",
			"should take container observability from 'the top-level config when the preview…'",
			"should take container observability from 'the preview config, which wins over t…'",
			"should deploy containers for a Durable Object declared by 'migrations' with no preview binding",
			"should deploy containers for a Durable Object declared by 'exports' with no preview binding",
			"should keep --json output parseable while deploying containers",
			"should resolve a container whose class is also bound cross-script earlier in the config",
			"should not propagate top-level containers into the preview deployment",
			"should omit containers from deployment when none are configured",
			"should exclude containers whose DO binding has script_name set",
			"should fail before creating the preview deployment when a container's class_name matches no Durable Object class",
			"should fail before creating the preview deployment when a container omits class_name",
			"should throw a UserError when no Durable Object namespace can be found for a container's class",
			"should fail before creating the preview deployment when a container's image belongs to a different account",
			"should fail before creating the preview deployment when Docker cannot be launched for a container built from a Dockerfile",
			"should fail before creating the preview deployment when the API token lacks the containers scope",
			"should warn that the preview is live when its containers fail to deploy, and still surface the error",
			"should use previews.define for worker bundling",
			"should fall back to HEAD commit metadata for annotations in CI",
			"should use env-specific previews config instead of top-level previews config",
			"should include previews.cache in deployment request, falling back to top-level cache",
			"should prefer previews.cache over top-level cache in deployment request",
			"should respect env-specific worker name for preview and deployment requests",
			"should fail before making API calls when env-specific previews config is invalid",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "preview delete"],
		status: "todo",
		names: [
			"should delete a preview with --skip-confirmation",
			"should proceed with deletion in non-interactive mode (CI fallback)",
			"should use --worker-name to target the correct worker",
			"should URL-encode the preview name when deleting",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "preview delete"],
		status: "skip",
		names: ["should respect env-specific worker name when deleting"],
	},
	{
		file: "tail.test.ts",
		ancestors: ["tail", "disconnects"],
		status: "todo",
		names: [
			"retries then gives up after the connection drops (pretty format)",
			"retries then gives up after the connection drops (json format)",
			"auto-reconnects after a transient drop and continues streaming",
			"treats a missed keep-alive pong as a disconnect and reconnects",
		],
	},
	{
		file: "tail.test.ts",
		ancestors: ["tail", "shutdown"],
		status: "todo",
		names: [
			"logs `Stopping tail...`, deletes the tail, and exits cleanly on Ctrl-C",
			"shuts down cleanly when Ctrl-C is hit before the WebSocket finishes connecting",
		],
	},
	{
		file: "tail.test.ts",
		ancestors: ["tail"],
		status: "skip",
		names: [
			"should error helpfully if pages_build_output_dir is set in wrangler.toml",
		],
	},
	{
		file: "utils/create-batches.test.ts",
		ancestors: ["createBatches"],
		status: "skip",
		names: [
			"a,b,c,d,e in batches of 2",
			"a,b,c,d,e,f,g,h in batches of 3",
			"a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z in batches of 6",
		],
	},
	{
		file: "vpc.test.ts",
		ancestors: ["vpc service commands"],
		status: "todo",
		names: ["should handle listing TCP services with port in table"],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
