// Generated from cloudflare/workers-sdk@c2bb4c815. Do not rename cases.
import { describe, it } from "vite-plus/test";

const groups = [
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"runSkillsInstallFlow with force-install prompt",
			"skip conditions",
		],
		status: "skip",
		names: [
			"skips silently when metadata file exists and sends no metrics",
			"skips silently when metadata file has accepted='unanswered' (user interrupted prompt)",
			"skips silently when metadata file uses the legacy format (no version field) and migrates it on disk",
			"force=true ignores existing metadata file",
			"skips and sends skills_install_skipped when no agents are detected",
			"skips and sends skills_install_skipped when rosie.agents() returns empty",
			"warns and sends skills_install_skipped when rosie.install() throws",
			"sends skills_install_skipped with errorMessage when rosie.agents() throws",
			"skips in CI and sends skills_install_skipped when ci.isCI is true",
			"force=true bypasses CI check and installs skills",
			"sends skills_install_skipped without logging anything in the terminal when TTY is false",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"runSkillsInstallFlow with force-install prompt",
			"user prompt interaction",
		],
		status: "skip",
		names: [
			"writes metadata, sends skills_install_skipped, and does not install when user declines",
			"calls rosie.install, logs success, and sends skills_install_completed when user accepts",
			"writes metadata with accepted='unanswered' before showing the confirm prompt",
			"force=true installs skills without prompting",
			"force=true does not write 'unanswered' metadata before installing",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"runSkillsInstallFlow with force-install prompt",
			"telemetry command property",
		],
		status: "skip",
		names: [
			"includes command in skills_install_completed when provided",
			"includes command in skills_install_skipped when provided",
			"omits command from metrics when not provided",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"runSkillsInstallFlow with force-install prompt",
			"multiple agents",
		],
		status: "skip",
		names: ["detects and installs skills for multiple agents"],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"runSkillsInstallFlow with force-install prompt",
			"install failure",
		],
		status: "skip",
		names: [
			"writes metadata with installFailed when rosie.install() throws",
			"success message excludes agents that failed",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"runSkillsInstallFlow with force-install prompt",
			"metadata file",
		],
		status: "skip",
		names: [
			"writes metadata file with correct content when user accepts",
			"writes metadata file when user declines",
			"does not include installFailed in metadata when user declines",
			"sets installFailed to true when rosie.install() throws",
			"sets installFailed to agent names on partial failure",
			"sets installFailed to false when all agents succeed",
			"records union of previous and current skill names on partial install failure",
			"preserves previous skill names when GitHub API fetch fails during install",
			"falls back to cached tree SHA when post-install fetchSkillsTreeSha fails",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"runSkillsInstallFlow with custom prompt message",
			"skip conditions",
		],
		status: "skip",
		names: [
			"skips silently when metadata file exists",
			"skips silently when metadata file records a decline",
			"skips silently when metadata file has accepted='unanswered'",
			"skips in CI",
			"skips in non-interactive terminal",
			"skips when no agents are detected",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"runSkillsInstallFlow with custom prompt message",
			"prompt message",
		],
		status: "skip",
		names: ["uses the caller-provided prompt message"],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"runSkillsInstallFlow with custom prompt message",
			"user prompt interaction",
		],
		status: "skip",
		names: [
			"installs skills when user accepts",
			"writes metadata with accepted=false when user declines",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: ["telemetryCurrentAgentSkillsInstalled"],
		status: "skip",
		names: [
			"resolves to null when no agent is detected",
			"resolves to null when detectAgent returns null id",
			"resolves to null when agent is detected but not in telemetryAgentMappings",
			"resolves to false when GitHub API fetch fails and no cache exists",
			"resolves to false when no skills are present in agent's globalSkillsPath",
			"resolves to 'manual' when some skills exist but no metadata file",
			"resolves to 'automatic' when skills exist and metadata confirms successful install",
			"resolves to 'manual' when metadata says install failed entirely (installFailed: true)",
			"resolves to 'manual' when metadata says install failed for this agent (installFailed: string[])",
			"resolves to 'manual' when agent is not in detectedAgents",
			"resolves to 'manual' when metadata has accepted='unanswered' (user interrupted prompt)",
			"uses cached GitHub API response within TTL",
			"falls back to stale cache when GitHub API returns an error",
			"works with cursor-agent amIVibingId mapping",
			"resolves to 'manual' when skills exist at an alternativeGlobalPath but no metadata",
			"resolves to 'automatic' when skills at alternativeGlobalPath were installed for another agent",
			"resolves to 'manual' when skills at alternativeGlobalPath were installed for another agent but failed",
			"resolves to false when skills are not at primary or any alternativeGlobalPath",
			"memoises the result across multiple calls",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: [
			"telemetryCurrentAgentSkillsInstalled",
			"legacy metadata migration",
		],
		status: "skip",
		names: [
			"resolves to 'automatic' when metadata uses the legacy flat AgentInfo schema",
			"migrates legacy metadata to version 1 on disk when read",
			"resolves to 'manual' when legacy metadata says install failed",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: ["runSkillsUpdateFlow"],
		status: "skip",
		names: [
			"skips when no metadata file exists",
			"skips when metadata says user declined install",
			"skips when metadata says install failed entirely",
			"skips when installedTreeSha matches remote SHA",
			"skips when user already declined this remote SHA",
			"prompts and updates when upstream SHA is different",
			"records a freshly-fetched tree SHA instead of the cached one after a successful update",
			"writes declinedTreeSha before showing the confirm prompt so an interrupted prompt does not reappear",
			"records declinedTreeSha when user declines and does not opt out of future prompts",
			"persists skipUpdatePrompts when user declines and opts out of future prompts",
			"skips update check when skipUpdatePrompts is set in metadata",
			"prompts again after upstream changes past a previously declined SHA",
			"handles update failure gracefully",
			"retries previously-failed agents on next update run",
			"skips when no managed agent skills exist on disk",
			"skips when skills were installed less than 30 days ago",
			"checks for updates when skills are older than 30 days",
			"prompts when installedTreeSha is missing",
			"back-fills missing skillsTreeSha from a fresh cache and proceeds with update check",
			"removes stale skill directories that no longer exist upstream after a successful update",
			"preserves non-Cloudflare skill directories during update",
			"restores backed-up skill directories when rosieInstall throws during update",
			"restores backed-up skill directories for agents that partially failed during update",
			"preserves backup directory and warns when restore fails after a thrown install",
			"persists installedSkillNames in metadata after successful update",
		],
	},
	{
		file: "agents-skills-install.test.ts",
		ancestors: ["runSkillsInstallFlow cleanup"],
		status: "skip",
		names: [
			"persists installedSkillNames in metadata after successful install",
			"restores backed-up skill directories when rosieInstall throws during install",
		],
	},
	{
		file: "api/startDevWorker/ProxyController.test.ts",
		ancestors: ["ProxyController"],
		status: "skip",
		names: [
			"ProxyWorker error reports preserve message/name/stack across the JSON channel",
			"Runtime.exceptionThrown dispatches a typed runtimeError event",
		],
	},
	{
		file: "cf-wrangler/build.test.ts",
		ancestors: ["cf-wrangler build"],
		status: "skip",
		names: [
			"emits Preview Build Output",
			"emits an assets-only project whose assets directory is the project root",
		],
	},
	{
		file: "cloudchamber/instance-type.test.ts",
		ancestors: ["inferInstanceType"],
		status: "skip",
		names: [
			"returns 'lite' for lite specs (0.0625 vcpu, 256 MiB, 2 GB disk)",
			"normalizes legacy 'standard' alias to 'standard-1' (prevents phantom EDIT diffs)",
			"returns 'basic' for basic specs",
			"returns 'standard-2' for standard-2 specs",
			"returns undefined when config does not match any known instance type",
			"returns undefined when disk is absent",
		],
	},
	{
		file: "containers/images.test.ts",
		ancestors: ["containers images delete"],
		status: "todo",
		names: [
			"reports deletion success with a warning when the GC request fails",
		],
	},
	{
		file: "d1/convert-timestamp-to-iso.test.ts",
		ancestors: ["convertTimestampToISO"],
		status: "skip",
		names: [
			"should reject invalid date strings",
			"should convert a JS timestamp to an ISO string",
			"should automagically convert a unix timestamp to an ISO string",
			"should reject unix timestamps older than 30 days",
			"should reject JS timestamps from the future",
			"should return an ISO string when provided an ISO string",
			"should reject ISO strings older than 30 days",
			"should reject ISO strings from the future",
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "[define]"],
		status: "skip",
		names: [
			"should be able to define values that will be substituted into top-level identifiers",
			"can be overriden in environments",
			"can be overridden with cli args",
			"can be overridden with cli args containing colons",
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "custom builds"],
		status: "skip",
		names: [
			"should run a custom build before publishing",
			"should run a custom build of multiple steps combined by && before publishing",
			"should throw an error if the entry doesn't exist after the build finishes",
			"should throw an error if the entry is a directory after the build finishes",
			"should minify the script when `--minify` is true (sw)",
			"should minify the script when `minify` in config is true (esm)",
			"should apply esbuild's keep-names functionality by default",
			"should apply esbuild's keep-names functionality unless keep_names is set to false",
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "--node-compat"],
		status: "skip",
		names: [
			"should error when using node compatibility mode",
			"should recommend node compatibility flag when using node builtins and no node compat is enabled",
			"should recommend node compatibility flag when using node builtins and node compat is set only to nodejs_als",
			"should recommend updating the compatibility date when using node builtins and the `nodejs_compat` flag",
			"should recommend updating the compatibility date flag when using no_nodejs_compat and non-prefixed node builtins",
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "unresolved module error messages"],
		status: "skip",
		names: [
			"should recommend alias when a non-Node module cannot be resolved",
			"should NOT recommend alias for Node built-in modules",
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "`nodejs_compat` compatibility flag"],
		status: "skip",
		names: [
			'when absent, should warn on any "external" `node:*` imports',
			'when present, should support "external" `node:*` imports',
			'when present, and compat date is on or after 2024-09-23, should support "external" non-prefixed node imports',
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "bundle reporter"],
		status: "skip",
		names: [
			"should print the bundle size",
			"should print the bundle size, with API errors",
			"should check biggest dependencies when upload fails with script size error",
			"should offer some helpful advice when upload fails with script startup error",
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "bundle reporter", "unit tests"],
		status: "skip",
		names: [
			"should calculate the bundle size",
			"should print the bundle size",
			"should print the top biggest dependencies in the bundle when upload fails",
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "--no-bundle"],
		status: "skip",
		names: [
			"(cli) should not transform the source code before publishing it",
			"(config) should not transform the source code before publishing it",
			"should preserve source phase imports without error",
			"should collect additional modules when find_additional_modules is not set",
			"should not collect additional modules when find_additional_modules is false",
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "--no-bundle --minify"],
		status: "skip",
		names: [
			"should warn that no-bundle and minify can't be used together",
			"should warn that no-bundle and minify can't be used together",
		],
	},
	{
		file: "deploy/build.test.ts",
		ancestors: ["deploy", "source maps"],
		status: "skip",
		names: [
			"should include source map with bundle when upload_source_maps = true",
			"should not include source map with bundle when upload_source_maps = false",
			"should include source maps emitted by custom build when upload_source_maps = true",
			"should include source maps when a //# debugId= comment follows the //# sourceMappingURL= comment",
			"should not include source maps emitted by custom build when upload_source_maps = false",
			"should correctly read sourcemaps with custom wrangler.toml location",
		],
	},
	{
		file: "deploy/formats.test.ts",
		ancestors: ["deploy", "upload rules"],
		status: "skip",
		names: [
			"should be able to define rules for uploading non-js modules (sw)",
			"should be able to define rules for uploading non-js modules (esm)",
			"should be able to use fallthrough:true for multiple rules",
			"should be able to use fallthrough:false for multiple rules",
			"should warn when multiple rules for the same type do not have fallback defined",
			"should be able to preserve file names when defining rules for uploading non-js modules (sw)",
			"should be able to preserve file names when defining rules for uploading non-js modules (esm)",
			"should rebase absolute non-js imports to a relative preserved name (esm)",
			"should keep absolute imports with matching basenames distinct (esm)",
			"should strip query string suffixes from module names (esm)",
			"should strip query string suffixes from module names with preserve_file_names (esm)",
		],
	},
	{
		file: "deploy/formats.test.ts",
		ancestors: ["deploy", "upload rules", "inject process.env.NODE_ENV"],
		status: "skip",
		names: ["should replace `process.env.NODE_ENV` in scripts"],
	},
	{
		file: "deploy/formats.test.ts",
		ancestors: ["deploy", "service worker format"],
		status: "skip",
		names: [
			"should error if trying to import a cloudflare prefixed external when in service worker format",
			"should error if importing a node.js library when in service worker format",
			"should error if nodejs_compat (v2) is turned on when in service worker format",
		],
	},
	{
		file: "deploy/formats.test.ts",
		ancestors: ["deploy", "legacy module specifiers"],
		status: "skip",
		names: [
			"should work with legacy module specifiers, with a deprecation warning (1)",
			"should work with legacy module specifiers, with a deprecation warning (2)",
			"should work with legacy module specifiers, with a deprecation warning (3)",
			"should not match regular module specifiers when there aren't any possible legacy module matches",
		],
	},
	{
		file: "deploy/formats.test.ts",
		ancestors: ["deploy", "tsconfig"],
		status: "skip",
		names: [
			"should use compilerOptions.paths to resolve modules",
			"should use compilerOptions.paths to resolve non-js modules with module rules",
			"should output to target es2022 even if tsconfig says otherwise",
		],
	},
	{
		file: "deploy/formats.test.ts",
		ancestors: ["deploy", "--outdir"],
		status: "skip",
		names: [
			"should generate built assets at --outdir if specified",
			"should copy any module imports related assets to --outdir if specified",
			"should copy source phase wasm imports to --outdir if specified",
		],
	},
	{
		file: "deploy/formats.test.ts",
		ancestors: ["deploy", "--outfile"],
		status: "skip",
		names: [
			"should generate worker bundle at --outfile if specified",
			"should include any module imports related assets in the worker bundle",
			"should include source phase wasm imports in the worker bundle",
			"should include bindings in the worker bundle",
		],
	},
	{
		file: "deploy/formats.test.ts",
		ancestors: ["deploy", "--metafile"],
		status: "skip",
		names: [
			"should output a metafile when --metafile is set",
			"should output a metafile when --metafile=./meta.json is set",
		],
	},
	{
		file: "deployment-bundle/build-container-images.test.ts",
		ancestors: ["buildDurableObjectContainerImages"],
		status: "skip",
		names: [
			"builds Dockerfile-backed Durable Object-managed container images without pushing",
			'resolves name-only exports and per-image build options during dry run: {"configPath":"project/wrangler.jsonc","expected":"project/docker"}',
			'resolves name-only exports and per-image build options during dry run: {"context":"../source","configPath":"project/wrangler.jsonc","expected":"source"}',
			'resolves name-only exports and per-image build options during dry run: {"context":"/Users/pbacondarwin/dev/cloudflare/workers-sdk/packages/wrangler/absolute context","configPath":"project/wrangler.jsonc","expected":"absolute context"}',
			'resolves name-only exports and per-image build options during dry run: {"context":"./source","expected":"source"}',
			'builds the same Dockerfile separately when its options differ: {"build_context":"../other"}',
			'builds the same Dockerfile separately when its options differ: {"build_vars":{"MODE":"second"}}',
			'reuses equivalent builds regardless of normalized paths, defaults or variable order: {"first":{"FIRST":"1","SECOND":"2"},"second":{"SECOND":"2","FIRST":"1"}}',
			'reuses equivalent builds regardless of normalized paths, defaults or variable order: {"second":{}}',
			"skips deploy builds when container rollout is disabled",
			"builds Durable Object-managed images before versions upload",
			"cleans up earlier images when a later build fails",
		],
	},
	{
		file: "experimental-config/convert.test.ts",
		ancestors: ["convertToolingConfig", "empty input"],
		status: "skip",
		names: [
			"returns an empty object for an empty config",
			"omits keys for undefined input fields rather than emitting `undefined` values",
		],
	},
	{
		file: "experimental-config/convert.test.ts",
		ancestors: [
			"convertToolingConfig",
			"camelCase → snake_case top-level mappings",
		],
		status: "skip",
		names: [
			"maps noBundle to no_bundle",
			"passes minify through unchanged",
			"maps keepNames to keep_names",
			"passes alias through unchanged",
			"passes define through unchanged",
			"maps findAdditionalModules to find_additional_modules",
			"maps preserveFileNames to preserve_file_names",
			"maps baseDir to base_dir",
			"passes rules through unchanged",
			"maps wasmModules to wasm_modules",
			"maps textBlobs to text_blobs",
			"maps dataBlobs to data_blobs",
			"passes tsconfig through unchanged",
			"maps jsxFactory to jsx_factory",
			"maps jsxFragment to jsx_fragment",
			"maps uploadSourceMaps to upload_source_maps",
			"maps sendMetrics to send_metrics",
		],
	},
	{
		file: "experimental-config/convert.test.ts",
		ancestors: ["convertToolingConfig", "pythonModules"],
		status: "skip",
		names: [
			"maps to python_modules with exclude preserved",
			"passes an empty pythonModules object through as python_modules: {}",
			"preserves an explicit empty exclude array",
		],
	},
	{
		file: "experimental-config/convert.test.ts",
		ancestors: ["convertToolingConfig", "build"],
		status: "skip",
		names: [
			"maps watchDir to watch_dir (string form)",
			"maps watchDir to watch_dir (array form)",
			"emits build with undefined sub-fields when only watchDir is provided",
		],
	},
	{
		file: "experimental-config/convert.test.ts",
		ancestors: ["convertToolingConfig", "dev"],
		status: "skip",
		names: [
			"maps every renamed sub-field",
			"does NOT map types into the output (consumed separately)",
			"emits dev with undefined sub-fields for absent options",
		],
	},
	{
		file: "experimental-config/convert.test.ts",
		ancestors: ["convertToolingConfig", "assetsDirectory"],
		status: "skip",
		names: [
			"maps to assets.directory",
			"does not emit `assets` when assetsDirectory is absent",
		],
	},
	{
		file: "experimental-config/convert.test.ts",
		ancestors: ["convertToolingConfig", "composite"],
		status: "skip",
		names: ["maps a fully populated config in a single pass"],
	},
	{
		file: "kv/key.test.ts",
		ancestors: ["kv", "key", "list", "cursor - undefined"],
		status: "todo",
		names: ["should make multiple requests for paginated results"],
	},
	{
		file: "kv/key.test.ts",
		ancestors: ["kv", "key", "list", "cursor - null"],
		status: "todo",
		names: ["should make multiple requests for paginated results"],
	},
	{
		file: "kv/key.test.ts",
		ancestors: ["kv", "key", "list", "cursor - "],
		status: "todo",
		names: ["should make multiple requests for paginated results"],
	},
	{
		file: "pages/build-functions-errors.test.ts",
		ancestors: ["Pages Functions build error adapter"],
		status: "skip",
		names: [
			"preserves unexpected route discovery errors",
			"preserves unexpected routes module errors",
		],
	},
	{
		file: "pages/project-create.test.ts",
		ancestors: ["pages project create"],
		status: "todo",
		names: [
			"should create a project with a production branch",
			"does not delegate an agent create when the project name already exists",
			"should create a project with compatibility flags",
			"should create a project with a compatibility date",
		],
	},
	{
		file: "pages/project-create.test.ts",
		ancestors: ["pages project create"],
		status: "skip",
		names: [
			"should override cached accountId with CLOUDFLARE_ACCOUNT_ID environmental variable if provided",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret"],
		status: "todo",
		names: [
			"rejects Preview deployment flag '--name my-preview' for 'put API_KEY'",
			"rejects Preview deployment flag '--message \"add secret\"' for 'put API_KEY'",
			"rejects Preview deployment flag '--tag v1' for 'put API_KEY'",
			"rejects Preview deployment flag '--ignore-base-config' for 'put API_KEY'",
			"rejects Preview deployment flag '--name my-preview' for 'delete REMOVE_ME'",
			"rejects Preview deployment flag '--message \"delete secret\"' for 'delete REMOVE_ME'",
			"rejects Preview deployment flag '--tag v1' for 'delete REMOVE_ME'",
			"rejects Preview deployment flag '--ignore-base-config' for 'delete REMOVE_ME'",
			"rejects Preview deployment flag '--name my-preview' for 'list'",
			"rejects Preview deployment flag '--message \"list secrets\"' for 'list'",
			"rejects Preview deployment flag '--tag v1' for 'list'",
			"rejects Preview deployment flag '--ignore-base-config' for 'list'",
			"rejects Preview deployment flag '--name my-preview' for 'bulk'",
			"rejects Preview deployment flag '--message \"bulk secrets\"' for 'bulk'",
			"rejects Preview deployment flag '--tag v1' for 'bulk'",
			"rejects Preview deployment flag '--ignore-base-config' for 'bulk'",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret"],
		status: "skip",
		names: ["does not inherit the preview script positional"],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "put"],
		status: "todo",
		names: [
			"patches the base config with the secret",
			"supports --worker-name",
			"fails before making API calls when Worker name is missing",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: [
			"wrangler preview",
			"preview base-config secret",
			"put",
			"(interactive)",
		],
		status: "todo",
		names: ["reads the secret from a masked prompt"],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "put"],
		status: "skip",
		names: ["respects env-specific worker name when using --env"],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "delete"],
		status: "todo",
		names: [
			"patches the base config removing the secret",
			"confirms before deleting a secret interactively",
			"makes no API call when the user declines confirmation",
			"supports --worker-name when deleting a secret",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "delete"],
		status: "skip",
		names: ["respects env-specific worker name when deleting a secret"],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "list"],
		status: "todo",
		names: [
			"reads the base config",
			"supports --worker-name when listing secrets",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "list"],
		status: "skip",
		names: [
			"lists only secrets and never leaks their values ('json, value provided')",
			"lists only secrets and never leaks their values ('pretty, value provided')",
			"shows (none) when the base config has no secrets",
			"respects env-specific worker name when listing secrets",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "bulk"],
		status: "todo",
		names: [
			"patches the base config with all secrets",
			"creates secrets for empty dotenv values",
			"uploads JSON secrets from stdin",
			"uploads dotenv secrets from stdin",
			"supports --worker-name when bulk uploading secrets",
			"deletes secrets for null values, like `wrangler secret bulk`",
			"patches an empty env for empty input",
			"makes no API call when there is no input",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "bulk"],
		status: "skip",
		names: ["respects env-specific worker name when bulk uploading secrets"],
	},
	{
		file: "secrets-store.test.ts",
		ancestors: ["secrets-store help"],
		status: "todo",
		names: [
			"shows help text when no arguments are passed",
			"shows help when an invalid argument is passed",
		],
	},
	{
		file: "secrets-store.test.ts",
		ancestors: ["secrets-store secret commands", "secrets-store secret create"],
		status: "todo",
		names: ["errors in creating a secret when value is larger than 64 KiB"],
	},
	{
		file: "utils-collectKeyValues.test.ts",
		ancestors: ["collectKeyValues()"],
		status: "skip",
		names: [
			"should return an empty object when passed undefined",
			"should return an empty object when passed an empty array",
			"should parse a key:value string with no value by returning an empty string for the value",
			"should return an object with a single key/value pair when passed an array with a single string",
			"should return an object with multiple key/value pairs when passed an array with multiple strings",
			"should return an object with multiple key/value pairs when passed an array with multiple strings with multiple colons",
		],
	},
	{
		file: "versions/versions.deploy.test.ts",
		ancestors: ["versions deploy", "top-level deploy"],
		status: "todo",
		names: [
			"sends the default Durable Objects code update strategy from top-level deploy",
			"sends an unsafe code update strategy override to the deployments API",
		],
	},
	{
		file: "versions/versions.deploy.test.ts",
		ancestors: ["versions deploy"],
		status: "todo",
		names: [
			"sends the default Durable Objects code update strategy",
			"sends the immediate CLI code update strategy",
			"sends the deferred CLI code update strategy",
			"normalizes a unitless deferred Durable Objects code update delay",
			"sends a deferred code update delay with millisecond precision",
			"sends a millisecond-precision deferred code update delay near the maximum",
			"sends the maximum deferred code update delay",
			"sends the configured immediate Durable Objects code update strategy",
			"omits the configured delay for immediate Durable Objects code updates",
			"sends the configured deferred Durable Objects code update strategy",
			"defaults the configured deferred code update strategy delay",
			"prefers the CLI Durable Objects code update mode over configuration",
			"rejects invalid Durable Objects code update delay: invalid",
			"rejects invalid Durable Objects code update delay: s",
			"rejects invalid Durable Objects code update delay: -1s",
			"rejects invalid Durable Objects code update delay: 500us",
			"rejects invalid Durable Objects code update delay: 1.0005s",
			"rejects invalid Durable Objects code update delay: 86399.9995s",
			"rejects invalid Durable Objects code update delay: 86401s",
			"rejects invalid Durable Objects code update delay: 25h",
			"rejects invalid Durable Objects code update mode: invalid",
			"rejects invalid Durable Objects code update mode: deferred",
			"does not normalize arguments after the option terminator",
			"does not consume a duration-shaped positional after immediate",
			"ignores user variables without Container metadata: 'unrelated object'",
			"ignores user variables without Container metadata: 'scalar'",
			"ignores user variables without Container metadata: 'array'",
			"ignores user variables without Container metadata: 'null'",
			"does not infer Containers from user metadata bindings",
			"preserves application settings when deploying selected versions (false)",
			"preserves application settings when deploying selected versions (true)",
			"creates a consistent multi-version Container application once (first version without images: false)",
			"creates a consistent multi-version Container application once (first version without images: true)",
			"creates a name-only Container application after a selected version provisions its export",
			"rejects inconsistent multi-version Container 'name' before deploying",
			"rejects inconsistent multi-version Container 'class' before deploying",
			"rejects inconsistent multi-version Container 'namespace' before deploying",
			"does not create Container applications when the Worker deployment is rejected",
			"reports partial completion when Container application creation fails after deployment",
			"resolves all deployed Container namespaces before creating any applications",
		],
	},
	{
		file: "versions/versions.deploy.test.ts",
		ancestors: ["versions deploy", "with wrangler.toml"],
		status: "todo",
		names: ["no args"],
	},
	{
		file: "versions/versions.deploy.test.ts",
		ancestors: [
			"units",
			"assignAndDistributePercentages distributes remaining share of 100%",
		],
		status: "todo",
		names: [
			" 'from 1 specified value across 1 unspe…'",
			" 'from 1 specified value across 2 unspe…'",
			" 'from 2 specified values across 1 unsp…'",
			" 'from 2 specified values across 2 unsp…'",
			" 'limited to specified versionIds'",
			" 'zero when no share remains'",
			" 'unchanged when fully specified (addin…'",
			" 'unchanged when fully specified (addin…'",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
