// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import {
    normalizeClientOptionsWithAuth,
    type NormalizedClientOptionsWithAuth,
} from "../../../../../../../../BaseClient.js";
import * as core from "../../../../../../../../core/index.js";
import { mergeHeaders } from "../../../../../../../../core/headers.js";
import * as environments from "../../../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../../../errors/index.js";
import type * as CloudflareApi from "../../../../../../../index.js";
import * as CloudflareApiErrors from "../../../../../../../errors/index.js";

export declare namespace TimeseriesGroupsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TimeseriesGroupsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TimeseriesGroupsClient.Options>;

    constructor(options: TimeseriesGroupsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests classified as automated or human over time. Visit https://developers.cloudflare.com/radar/concepts/bot-classes/ for more information.
     *
     * @param {CloudflareApi.radar.http.BotClassTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.botClass({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public botClass(
        request: CloudflareApi.radar.http.BotClassTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.BotClassTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__botClass(request, requestOptions));
    }

    private async __botClass(
        request: CloudflareApi.radar.http.BotClassTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.BotClassTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/bot_class",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.BotClassTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/bot_class",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by user agent over time.
     *
     * @param {CloudflareApi.radar.http.BrowserTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.browser({
     *         name: ["main_series"],
     *         dateRange: ["7d"],
     *         limitPerGroup: 10
     *     })
     */
    public browser(
        request: CloudflareApi.radar.http.BrowserTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.BrowserTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__browser(request, requestOptions));
    }

    private async __browser(
        request: CloudflareApi.radar.http.BrowserTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.BrowserTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            limitPerGroup,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            limitPerGroup,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/browser",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.BrowserTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/browser",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by user agent family over time.
     *
     * @param {CloudflareApi.radar.http.BrowserFamilyTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.browserFamily({
     *         name: ["main_series"],
     *         dateRange: ["7d"],
     *         limitPerGroup: 10
     *     })
     */
    public browserFamily(
        request: CloudflareApi.radar.http.BrowserFamilyTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.BrowserFamilyTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__browserFamily(request, requestOptions));
    }

    private async __browserFamily(
        request: CloudflareApi.radar.http.BrowserFamilyTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.BrowserFamilyTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            limitPerGroup,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            limitPerGroup,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/browser_family",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.BrowserFamilyTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/browser_family",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by device type over time.
     *
     * @param {CloudflareApi.radar.http.DeviceTypeTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.deviceType({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public deviceType(
        request: CloudflareApi.radar.http.DeviceTypeTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.DeviceTypeTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deviceType(request, requestOptions));
    }

    private async __deviceType(
        request: CloudflareApi.radar.http.DeviceTypeTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.DeviceTypeTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/device_type",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.DeviceTypeTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/device_type",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by HTTP protocol (HTTP vs. HTTPS) over time.
     *
     * @param {CloudflareApi.radar.http.HttpProtocolTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.httpProtocol({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public httpProtocol(
        request: CloudflareApi.radar.http.HttpProtocolTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.HttpProtocolTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__httpProtocol(request, requestOptions));
    }

    private async __httpProtocol(
        request: CloudflareApi.radar.http.HttpProtocolTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.HttpProtocolTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/http_protocol",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.HttpProtocolTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/http_protocol",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by HTTP version over time.
     *
     * @param {CloudflareApi.radar.http.HttpVersionTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.httpVersion({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public httpVersion(
        request: CloudflareApi.radar.http.HttpVersionTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.HttpVersionTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__httpVersion(request, requestOptions));
    }

    private async __httpVersion(
        request: CloudflareApi.radar.http.HttpVersionTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.HttpVersionTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/http_version",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.HttpVersionTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/http_version",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by IP version over time.
     *
     * @param {CloudflareApi.radar.http.IpVersionTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.ipVersion({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public ipVersion(
        request: CloudflareApi.radar.http.IpVersionTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.IpVersionTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__ipVersion(request, requestOptions));
    }

    private async __ipVersion(
        request: CloudflareApi.radar.http.IpVersionTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.IpVersionTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/ip_version",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.IpVersionTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/ip_version",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by operating system over time.
     *
     * @param {CloudflareApi.radar.http.OsTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.os({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public os(
        request: CloudflareApi.radar.http.OsTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.OsTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__os(request, requestOptions));
    }

    private async __os(
        request: CloudflareApi.radar.http.OsTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.OsTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/os",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.OsTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/os",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by post-quantum support over time.
     *
     * @param {CloudflareApi.radar.http.PostQuantumTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.postQuantum({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public postQuantum(
        request: CloudflareApi.radar.http.PostQuantumTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.PostQuantumTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postQuantum(request, requestOptions));
    }

    private async __postQuantum(
        request: CloudflareApi.radar.http.PostQuantumTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.PostQuantumTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            tlsVersion,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            tlsVersion: Array.isArray(tlsVersion)
                ? tlsVersion.map((item) => item)
                : tlsVersion != null
                  ? tlsVersion
                  : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/post_quantum",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.PostQuantumTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/post_quantum",
        );
    }

    /**
     * @deprecated
     *
     * Retrieves the distribution of HTTP requests by TLS version over time.
     *
     * @param {CloudflareApi.radar.http.TlsVersionTimeseriesGroupsRequest} request
     * @param {TimeseriesGroupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CloudflareApi.BadRequestError}
     *
     * @example
     *     await client.radar.http.timeseriesGroups.tlsVersion({
     *         name: ["main_series"],
     *         dateRange: ["7d"]
     *     })
     */
    public tlsVersion(
        request: CloudflareApi.radar.http.TlsVersionTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.radar.http.TlsVersionTimeseriesGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__tlsVersion(request, requestOptions));
    }

    private async __tlsVersion(
        request: CloudflareApi.radar.http.TlsVersionTimeseriesGroupsRequest = {},
        requestOptions?: TimeseriesGroupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.radar.http.TlsVersionTimeseriesGroupsResponse>> {
        const {
            aggInterval,
            name,
            dateRange,
            dateStart,
            dateEnd,
            asn,
            location,
            continent,
            geoId,
            botClass,
            deviceType,
            httpProtocol,
            httpVersion,
            ipVersion,
            os,
            browserFamily,
            format,
        } = request;
        const _queryParams: Record<string, unknown> = {
            aggInterval: aggInterval != null ? aggInterval : undefined,
            name,
            dateRange,
            dateStart: Array.isArray(dateStart)
                ? dateStart.map((item) => item)
                : dateStart != null
                  ? dateStart
                  : undefined,
            dateEnd: Array.isArray(dateEnd) ? dateEnd.map((item) => item) : dateEnd != null ? dateEnd : undefined,
            asn,
            location,
            continent,
            geoId,
            botClass: Array.isArray(botClass) ? botClass.map((item) => item) : botClass != null ? botClass : undefined,
            deviceType: Array.isArray(deviceType)
                ? deviceType.map((item) => item)
                : deviceType != null
                  ? deviceType
                  : undefined,
            httpProtocol: Array.isArray(httpProtocol)
                ? httpProtocol.map((item) => item)
                : httpProtocol != null
                  ? httpProtocol
                  : undefined,
            httpVersion: Array.isArray(httpVersion)
                ? httpVersion.map((item) => item)
                : httpVersion != null
                  ? httpVersion
                  : undefined,
            ipVersion: Array.isArray(ipVersion)
                ? ipVersion.map((item) => item)
                : ipVersion != null
                  ? ipVersion
                  : undefined,
            os: Array.isArray(os) ? os.map((item) => item) : os != null ? os : undefined,
            browserFamily: Array.isArray(browserFamily)
                ? browserFamily.map((item) => item)
                : browserFamily != null
                  ? browserFamily
                  : undefined,
            format: format != null ? format : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                "radar/http/timeseries_groups/tls_version",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.radar.http.TlsVersionTimeseriesGroupsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new CloudflareApiErrors.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.CloudflareApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/radar/http/timeseries_groups/tls_version",
        );
    }
}
