import type { CommonYargsOptions, InferArgs } from "#lib/cli-types.js";
import type { ArgClassification } from "#lib/telemetry/index.js";
import type { SdkRequest } from "#sdk";
/**
 * update command
 * @generated from apis/overlays/zero-trust.ts
 */
import type { Argv, CommandModule } from "yargs";
import {
	createCommandClient,
	getAccountId,
	resolveAccountIdSilent,
} from "#lib/auth.js";
import { compactBody, parseBody, parseObjectArray } from "#lib/body-parser.js";
import { formatDryRun } from "#lib/dry-run.js";
import { resolveFileToken } from "#lib/input-validation.js";
import { LOCAL_ACCOUNT_ID } from "#lib/local.js";
import { formatOutput } from "#lib/output.js";
import { withProgress } from "#lib/progress.js";
import {
	promptForRequiredEnumField,
	promptForRequiredField,
} from "#lib/prompt.js";
import { runWithTelemetry } from "#lib/telemetry/index.js";

function builder(yargs: Argv<CommonYargsOptions>) {
	return yargs
		.usage(
			"$0 zero-trust devices posture rules update <rule-id>\n\nUpdates a device posture rule."
		)
		.positional("rule-id", {
			type: "string",
			description: "API UUID.",
			demandOption: true,
		})
		.option("description", {
			type: "string",
			description: "The description of the device posture rule.",
		})
		.option("expiration", {
			type: "string",
			description:
				"Sets the expiration time for a posture check result. If empty, the result remains valid until it is overwritten by new data from the WARP client.",
		})
		.option("input-exists", {
			type: "boolean",
			description: "Whether or not file exists.",
		})
		.option("input-operating-system", {
			type: "string",
			description: "Operating system.",
			choices: ["windows", "linux", "mac", "android", "ios", "chromeos"],
		})
		.option("input-path", { type: "string", description: "File path." })
		.option("input-sha256", { type: "string", description: "SHA-256." })
		.option("input-thumbprint", {
			type: "string",
			description: "Signing certificate thumbprint.",
		})
		.option("input-id", { type: "string", description: "List ID." })
		.option("input-domain", { type: "string", description: "Domain." })
		.option("input-operator", {
			type: "string",
			description: "Operator.",
			choices: ["<", "<=", ">", ">=", "=="],
		})
		.option("input-os-distro-name", {
			type: "string",
			description: "Operating System Distribution Name (linux only).",
		})
		.option("input-os-distro-revision", {
			type: "string",
			description: "Version of OS Distribution (linux only).",
		})
		.option("input-os-version-extra", {
			type: "string",
			description:
				"Additional operating system version details. For Windows, the UBR (Update Build Revision). For Mac or iOS, the Product Version Extra. For Linux, the distribution name and version.",
		})
		.option("input-version", { type: "string", description: "Version of OS." })
		.option("input-enabled", { type: "boolean", description: "Enabled." })
		.option("input-check-disks", {
			type: "string",
			array: true,
			description: "List of volume names to be checked for encryption.",
		})
		.option("input-require-all", {
			type: "boolean",
			description: "Whether to check all disks for encryption.",
		})
		.option("input-certificate-id", {
			type: "string",
			description: "UUID of Cloudflare managed certificate.",
		})
		.option("input-cn", {
			type: "string",
			description: "Common Name that is protected by the certificate.",
		})
		.option("input-check-private-key", {
			type: "boolean",
			description:
				"Confirm the certificate was not imported from another device. We recommend keeping this enabled unless the certificate was deployed without a private key.",
		})
		.option("input-extended-key-usage", {
			type: "string",
			array: true,
			description:
				"List of values indicating purposes for which the certificate public key can be used.",
		})
		.option("input-locations-paths", {
			type: "string",
			array: true,
			description: "List of paths to check for client certificate on linux.",
		})
		.option("input-locations-trust-stores", {
			type: "string",
			array: true,
			description: "List of trust stores to check for client certificate.",
		})
		.option("input-subject-alternative-names", {
			type: "string",
			array: true,
			description: "List of certificate Subject Alternative Names.",
		})
		.option("input-update-window-days", {
			type: "number",
			description:
				"Number of days that the antivirus should be updated within.",
		})
		.option("input-compliance-status", {
			type: "string",
			description: "Compliance Status.",
			choices: [
				"compliant",
				"noncompliant",
				"unknown",
				"notapplicable",
				"ingraceperiod",
				"error",
			],
		})
		.option("input-connection-id", {
			type: "string",
			description: "Posture Integration ID.",
		})
		.option("input-last-seen", {
			type: "string",
			description:
				"For more details on last seen, please refer to the Crowdstrike documentation.",
		})
		.option("input-os", { type: "string", description: "Os Version." })
		.option("input-overall", { type: "string", description: "Overall." })
		.option("input-sensor-config", {
			type: "string",
			description: "SensorConfig.",
		})
		.option("input-state", {
			type: "string",
			description:
				"For more details on state, please refer to the Crowdstrike documentation.",
			choices: ["online", "offline", "unknown"],
		})
		.option("input-version-operator", {
			type: "string",
			description: "Version Operator.",
			choices: ["<", "<=", ">", ">=", "=="],
		})
		.option("input-auth-state", {
			type: "string",
			array: true,
			description:
				"The set of Kolide device authentication states that pass the posture check. Device must match one of the specified states.",
		})
		.option("input-count-operator", {
			type: "string",
			description: "Count Operator.",
			choices: ["<", "<=", ">", ">=", "=="],
		})
		.option("input-issue-count", {
			type: "string",
			description: "The Number of Issues.",
		})
		.option("input-eid-last-seen", {
			type: "string",
			description:
				"For more details on eid last seen, refer to the Tanium documentation.",
		})
		.option("input-risk-level", {
			type: "string",
			description:
				"For more details on risk level, refer to the Tanium documentation.",
			choices: ["low", "medium", "high", "critical"],
		})
		.option("input-score-operator", {
			type: "string",
			description: "Score Operator.",
			choices: ["<", "<=", ">", ">=", "=="],
		})
		.option("input-total-score", {
			type: "number",
			description:
				"For more details on total score, refer to the Tanium documentation.",
		})
		.option("input-active-threats", {
			type: "number",
			description: "The Number of active threats.",
		})
		.option("input-infected", {
			type: "boolean",
			description: "Whether device is infected.",
		})
		.option("input-is-active", {
			type: "boolean",
			description: "Whether device is active.",
		})
		.option("input-network-status", {
			type: "string",
			description: "Network status of device.",
			choices: ["connected", "disconnected", "disconnecting", "connecting"],
		})
		.option("input-operational-state", {
			type: "string",
			description: "Agent operational state.",
			choices: [
				"na",
				"partially_disabled",
				"auto_fully_disabled",
				"fully_disabled",
				"auto_partially_disabled",
				"disabled_error",
				"db_corruption",
			],
		})
		.option("input-score", {
			type: "number",
			description:
				"A value between 0-100 assigned to devices set by the 3rd party posture provider.",
		})
		.option("match", {
			type: "string",
			description:
				"The conditions that the client must match to run the rule. Provide as a JSON array of objects or @path/to/file.json.",
		})
		.option("name", {
			type: "string",
			description: "The name of the device posture rule.",
		})
		.option("schedule", {
			type: "string",
			description:
				"Polling frequency for the WARP client posture check. Default: `5m` (poll every five minutes). Minimum: `1m`.",
		})
		.option("type", {
			type: "string",
			description: "The type of device posture rule.",
			choices: [
				"file",
				"application",
				"tanium",
				"gateway",
				"warp",
				"disk_encryption",
				"serial_number",
				"sentinelone",
				"carbonblack",
				"firewall",
				"os_version",
				"domain_joined",
				"client_certificate",
				"client_certificate_v2",
				"antivirus",
				"unique_client_id",
				"kolide",
				"tanium_s2s",
				"crowdstrike_s2s",
				"intune",
				"workspace_one",
				"sentinelone_s2s",
				"custom_s2s",
			],
		})
		.option("dry-run", {
			type: "boolean",
			description: "Validate and show what would happen without executing",
			default: false,
		})
		.option("body", {
			type: "string",
			description: "Raw JSON request body (bypasses individual flags)",
		})
		.conflicts("input-exists", [
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-operating-system", [
			"input-id",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-operator",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-path", [
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-sha256", [
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-thumbprint", [
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-id", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-operating-system",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-domain", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-operator", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-operating-system",
			"input-id",
			"input-domain",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
		])
		.conflicts("input-os-distro-name", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-os-distro-revision", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-os-version-extra", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-version", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-operating-system",
			"input-id",
			"input-domain",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.implies("input-version", ["input-operating-system", "input-operator"])
		.conflicts("input-enabled", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.implies("input-enabled", ["input-operating-system"])
		.conflicts("input-check-disks", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-require-all", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-certificate-id", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-cn", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.implies("input-cn", ["input-certificate-id"])
		.conflicts("input-check-private-key", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.implies("input-check-private-key", [
			"input-certificate-id",
			"input-operating-system",
		])
		.conflicts("input-extended-key-usage", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-locations-paths", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-locations-trust-stores", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-subject-alternative-names", [
			"input-exists",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-update-window-days",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-update-window-days", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-compliance-status",
			"input-connection-id",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-compliance-status", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-connection-id", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
		])
		.conflicts("input-last-seen", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-os", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-overall", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-sensor-config", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-state", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-version-operator", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-auth-state", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-count-operator", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-issue-count", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-operator",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-eid-last-seen", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-risk-level", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-score-operator", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-total-score", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
			"input-score",
		])
		.conflicts("input-active-threats", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-score",
		])
		.conflicts("input-infected", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-score",
		])
		.conflicts("input-is-active", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-score",
		])
		.conflicts("input-network-status", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-score",
		])
		.conflicts("input-operational-state", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-score",
		])
		.conflicts("input-score", [
			"input-exists",
			"input-operating-system",
			"input-path",
			"input-sha256",
			"input-thumbprint",
			"input-id",
			"input-domain",
			"input-os-distro-name",
			"input-os-distro-revision",
			"input-os-version-extra",
			"input-version",
			"input-enabled",
			"input-check-disks",
			"input-require-all",
			"input-certificate-id",
			"input-cn",
			"input-check-private-key",
			"input-extended-key-usage",
			"input-locations-paths",
			"input-locations-trust-stores",
			"input-subject-alternative-names",
			"input-update-window-days",
			"input-compliance-status",
			"input-last-seen",
			"input-os",
			"input-overall",
			"input-sensor-config",
			"input-state",
			"input-version-operator",
			"input-auth-state",
			"input-count-operator",
			"input-issue-count",
			"input-eid-last-seen",
			"input-risk-level",
			"input-score-operator",
			"input-total-score",
			"input-active-threats",
			"input-infected",
			"input-is-active",
			"input-network-status",
			"input-operational-state",
		])
		.implies("input-score", ["input-connection-id", "input-operator"]);
}

type Args = InferArgs<typeof builder>;

type Request = SdkRequest<"device-posture-rules-update-device-posture-rule">;
type Body = Request;

const command: CommandModule<CommonYargsOptions, Args> = {
	command: "update <rule-id>",
	describe: "Update posture rule",
	builder,
	handler: async (argv): Promise<void> =>
		runWithTelemetry(
			{
				command: "zero-trust devices posture rules update",
				classification: {
					safeFlags: [
						"input-exists",
						"input-operating-system",
						"input-operator",
						"input-enabled",
						"input-require-all",
						"input-check-private-key",
						"input-compliance-status",
						"input-state",
						"input-version-operator",
						"input-count-operator",
						"input-risk-level",
						"input-score-operator",
						"input-infected",
						"input-is-active",
						"input-network-status",
						"input-operational-state",
						"type",
						"dry-run",
					],
				} satisfies ArgClassification<Args>,
			},
			argv as Record<string, unknown>,
			async () => {
				if (argv.dryRun) {
					const __cfDryRunAccountId = await resolveAccountIdSilent();
					formatDryRun({
						command: "cf zero-trust devices posture rules update",
						method: "PUT",
						url: `https://api.cloudflare.com/client/v4/accounts/${__cfDryRunAccountId ?? "<account-id>"}/devices/posture/${argv["rule-id"] == null ? "<rule-id>" : encodeURIComponent(String(argv["rule-id"]))}`,
						pathParams: { "rule-id": String(argv["rule-id"] ?? "") },
						bodyKind: "json",
						body:
							argv.body !== undefined
								? parseBody(argv.body)
								: compactBody({
										description: resolveFileToken(
											argv["description"] as string | undefined,
											"description",
											"text"
										),
										expiration: resolveFileToken(
											argv["expiration"] as string | undefined,
											"expiration",
											"text"
										),
										input: {
											exists: argv["input-exists"],
											operating_system: resolveFileToken(
												argv["input-operating-system"] as string | undefined,
												"input-operating-system",
												"text"
											),
											path: resolveFileToken(
												argv["input-path"] as string | undefined,
												"input-path",
												"text"
											),
											sha256: resolveFileToken(
												argv["input-sha256"] as string | undefined,
												"input-sha256",
												"text"
											),
											thumbprint: resolveFileToken(
												argv["input-thumbprint"] as string | undefined,
												"input-thumbprint",
												"text"
											),
											id: resolveFileToken(
												argv["input-id"] as string | undefined,
												"input-id",
												"text"
											),
											domain: resolveFileToken(
												argv["input-domain"] as string | undefined,
												"input-domain",
												"text"
											),
											operator: resolveFileToken(
												argv["input-operator"] as string | undefined,
												"input-operator",
												"text"
											),
											os_distro_name: resolveFileToken(
												argv["input-os-distro-name"] as string | undefined,
												"input-os-distro-name",
												"text"
											),
											os_distro_revision: resolveFileToken(
												argv["input-os-distro-revision"] as string | undefined,
												"input-os-distro-revision",
												"text"
											),
											os_version_extra: resolveFileToken(
												argv["input-os-version-extra"] as string | undefined,
												"input-os-version-extra",
												"text"
											),
											version: resolveFileToken(
												argv["input-version"] as string | undefined,
												"input-version",
												"text"
											),
											enabled: argv["input-enabled"],
											checkDisks: argv["input-check-disks"],
											requireAll: argv["input-require-all"],
											certificate_id: resolveFileToken(
												argv["input-certificate-id"] as string | undefined,
												"input-certificate-id",
												"text"
											),
											cn: resolveFileToken(
												argv["input-cn"] as string | undefined,
												"input-cn",
												"text"
											),
											check_private_key: argv["input-check-private-key"],
											extended_key_usage: argv["input-extended-key-usage"],
											locations: {
												paths: argv["input-locations-paths"],
												trust_stores: argv["input-locations-trust-stores"],
											},
											subject_alternative_names:
												argv["input-subject-alternative-names"],
											update_window_days: argv["input-update-window-days"],
											compliance_status: resolveFileToken(
												argv["input-compliance-status"] as string | undefined,
												"input-compliance-status",
												"text"
											),
											connection_id: resolveFileToken(
												argv["input-connection-id"] as string | undefined,
												"input-connection-id",
												"text"
											),
											last_seen: resolveFileToken(
												argv["input-last-seen"] as string | undefined,
												"input-last-seen",
												"text"
											),
											os: resolveFileToken(
												argv["input-os"] as string | undefined,
												"input-os",
												"text"
											),
											overall: resolveFileToken(
												argv["input-overall"] as string | undefined,
												"input-overall",
												"text"
											),
											sensor_config: resolveFileToken(
												argv["input-sensor-config"] as string | undefined,
												"input-sensor-config",
												"text"
											),
											state: resolveFileToken(
												argv["input-state"] as string | undefined,
												"input-state",
												"text"
											),
											versionOperator: resolveFileToken(
												argv["input-version-operator"] as string | undefined,
												"input-version-operator",
												"text"
											),
											auth_state: argv["input-auth-state"],
											countOperator: resolveFileToken(
												argv["input-count-operator"] as string | undefined,
												"input-count-operator",
												"text"
											),
											issue_count: resolveFileToken(
												argv["input-issue-count"] as string | undefined,
												"input-issue-count",
												"text"
											),
											eid_last_seen: resolveFileToken(
												argv["input-eid-last-seen"] as string | undefined,
												"input-eid-last-seen",
												"text"
											),
											risk_level: resolveFileToken(
												argv["input-risk-level"] as string | undefined,
												"input-risk-level",
												"text"
											),
											scoreOperator: resolveFileToken(
												argv["input-score-operator"] as string | undefined,
												"input-score-operator",
												"text"
											),
											total_score: argv["input-total-score"],
											active_threats: argv["input-active-threats"],
											infected: argv["input-infected"],
											is_active: argv["input-is-active"],
											network_status: resolveFileToken(
												argv["input-network-status"] as string | undefined,
												"input-network-status",
												"text"
											),
											operational_state: resolveFileToken(
												argv["input-operational-state"] as string | undefined,
												"input-operational-state",
												"text"
											),
											score: argv["input-score"],
										},
										match: parseObjectArray(argv["match"], "match"),
										name: resolveFileToken(
											argv["name"] as string | undefined,
											"name",
											"text"
										),
										schedule: resolveFileToken(
											argv["schedule"] as string | undefined,
											"schedule",
											"text"
										),
										type: resolveFileToken(
											argv["type"] as string | undefined,
											"type",
											"text"
										),
									}),
					});
					return;
				}
				const client = await createCommandClient(argv);
				const accountId = argv.local ? LOCAL_ACCOUNT_ID : await getAccountId();
				argv.accountId = accountId;

				if (argv.body) {
					const bodyData = parseBody<Request>(argv.body);
					const result = await withProgress(`Updating`, async () =>
						client.zeroTrust.devices.posture.rules.update({
							...bodyData,
							account_id: accountId,
							rule_id: argv["rule-id"],
						} satisfies Request)
					);
					formatOutput(result, { successLabel: `Updated` });
					return;
				}
				if (argv["name"] === undefined) {
					argv["name"] = await promptForRequiredField(
						"name",
						"The name of the device posture rule."
					);
				}
				if (argv["type"] === undefined) {
					argv["type"] = await promptForRequiredEnumField(
						"type",
						"The type of device posture rule.",
						[
							"file",
							"application",
							"tanium",
							"gateway",
							"warp",
							"disk_encryption",
							"serial_number",
							"sentinelone",
							"carbonblack",
							"firewall",
							"os_version",
							"domain_joined",
							"client_certificate",
							"client_certificate_v2",
							"antivirus",
							"unique_client_id",
							"kolide",
							"tanium_s2s",
							"crowdstrike_s2s",
							"intune",
							"workspace_one",
							"sentinelone_s2s",
							"custom_s2s",
						] as const
					);
				}

				// Assemble request body from individual flags
				const bodyData = compactBody<Body>({
					description: resolveFileToken(
						argv["description"] as string | undefined,
						"description",
						"text"
					),
					expiration: resolveFileToken(
						argv["expiration"] as string | undefined,
						"expiration",
						"text"
					),
					input: {
						exists: argv["input-exists"],
						operating_system: resolveFileToken(
							argv["input-operating-system"] as string | undefined,
							"input-operating-system",
							"text"
						),
						path: resolveFileToken(
							argv["input-path"] as string | undefined,
							"input-path",
							"text"
						),
						sha256: resolveFileToken(
							argv["input-sha256"] as string | undefined,
							"input-sha256",
							"text"
						),
						thumbprint: resolveFileToken(
							argv["input-thumbprint"] as string | undefined,
							"input-thumbprint",
							"text"
						),
						id: resolveFileToken(
							argv["input-id"] as string | undefined,
							"input-id",
							"text"
						),
						domain: resolveFileToken(
							argv["input-domain"] as string | undefined,
							"input-domain",
							"text"
						),
						operator: resolveFileToken(
							argv["input-operator"] as string | undefined,
							"input-operator",
							"text"
						),
						os_distro_name: resolveFileToken(
							argv["input-os-distro-name"] as string | undefined,
							"input-os-distro-name",
							"text"
						),
						os_distro_revision: resolveFileToken(
							argv["input-os-distro-revision"] as string | undefined,
							"input-os-distro-revision",
							"text"
						),
						os_version_extra: resolveFileToken(
							argv["input-os-version-extra"] as string | undefined,
							"input-os-version-extra",
							"text"
						),
						version: resolveFileToken(
							argv["input-version"] as string | undefined,
							"input-version",
							"text"
						),
						enabled: argv["input-enabled"],
						checkDisks: argv["input-check-disks"],
						requireAll: argv["input-require-all"],
						certificate_id: resolveFileToken(
							argv["input-certificate-id"] as string | undefined,
							"input-certificate-id",
							"text"
						),
						cn: resolveFileToken(
							argv["input-cn"] as string | undefined,
							"input-cn",
							"text"
						),
						check_private_key: argv["input-check-private-key"],
						extended_key_usage: argv["input-extended-key-usage"],
						locations: {
							paths: argv["input-locations-paths"],
							trust_stores: argv["input-locations-trust-stores"],
						},
						subject_alternative_names: argv["input-subject-alternative-names"],
						update_window_days: argv["input-update-window-days"],
						compliance_status: resolveFileToken(
							argv["input-compliance-status"] as string | undefined,
							"input-compliance-status",
							"text"
						),
						connection_id: resolveFileToken(
							argv["input-connection-id"] as string | undefined,
							"input-connection-id",
							"text"
						),
						last_seen: resolveFileToken(
							argv["input-last-seen"] as string | undefined,
							"input-last-seen",
							"text"
						),
						os: resolveFileToken(
							argv["input-os"] as string | undefined,
							"input-os",
							"text"
						),
						overall: resolveFileToken(
							argv["input-overall"] as string | undefined,
							"input-overall",
							"text"
						),
						sensor_config: resolveFileToken(
							argv["input-sensor-config"] as string | undefined,
							"input-sensor-config",
							"text"
						),
						state: resolveFileToken(
							argv["input-state"] as string | undefined,
							"input-state",
							"text"
						),
						versionOperator: resolveFileToken(
							argv["input-version-operator"] as string | undefined,
							"input-version-operator",
							"text"
						),
						auth_state: argv["input-auth-state"],
						countOperator: resolveFileToken(
							argv["input-count-operator"] as string | undefined,
							"input-count-operator",
							"text"
						),
						issue_count: resolveFileToken(
							argv["input-issue-count"] as string | undefined,
							"input-issue-count",
							"text"
						),
						eid_last_seen: resolveFileToken(
							argv["input-eid-last-seen"] as string | undefined,
							"input-eid-last-seen",
							"text"
						),
						risk_level: resolveFileToken(
							argv["input-risk-level"] as string | undefined,
							"input-risk-level",
							"text"
						),
						scoreOperator: resolveFileToken(
							argv["input-score-operator"] as string | undefined,
							"input-score-operator",
							"text"
						),
						total_score: argv["input-total-score"],
						active_threats: argv["input-active-threats"],
						infected: argv["input-infected"],
						is_active: argv["input-is-active"],
						network_status: resolveFileToken(
							argv["input-network-status"] as string | undefined,
							"input-network-status",
							"text"
						),
						operational_state: resolveFileToken(
							argv["input-operational-state"] as string | undefined,
							"input-operational-state",
							"text"
						),
						score: argv["input-score"],
					},
					match: parseObjectArray(argv["match"], "match"),
					name: resolveFileToken(
						argv["name"] as string | undefined,
						"name",
						"text"
					),
					schedule: resolveFileToken(
						argv["schedule"] as string | undefined,
						"schedule",
						"text"
					),
					type: resolveFileToken(
						argv["type"] as string | undefined,
						"type",
						"text"
					),
				});
				const result = await withProgress(`Updating`, async () =>
					client.zeroTrust.devices.posture.rules.update({
						...bodyData,
						account_id: accountId,
						rule_id: argv["rule-id"],
					} satisfies Request)
				);
				formatOutput(result, { successLabel: `Updated` });
			}
		),
};

export default command;
